### PR TITLE
(DOCS)DOC-3896: Changing puppet-lookup to puppet lookup

### PR DESCRIPTION
**Pull request by hestonhoffman**
https://tickets.puppetlabs.com/browse/DOC-3896

### CODE REVIEW

**Comment by melissa** [comment]
Is `DOC-3896` a public ticket? I can never remember... If it is, then great! Otherwise, we should move it to a public ticket. Referencing private tickets in a public project is a bummer for community members who don't have access

**Comment by hestonhoffman** [comment]
@melissa Good point! Moved it to https://tickets.puppetlabs.com/browse/DOCUMENT-980

**Comment by melissa** [comment]
Awesome! Thanks for moving that ticket. You now need to update the commit message (`git commit --amend`) here to reference that new ticket. If you want any guidance, I'm happy to help out

**Comment by melissa** [comment]
@hestonhoffman I'm not sure how the docs team handles ticket lifecycles, so I'll leave updating the ticket to you. Thanks for the contribution!

**Pull request merged**
