### PR TITLE
(PUP-7115) Unvendor semantic puppet gem

### PR DESCRIPTION
**Pull request by jtappa**

### CODE REVIEW

**Comment by joshcooper** [comment]
LGTM. I do think we should merge this PR first, and then the puppetserver PR.

After this is merged, I think puppetserver will need to bump their puppet git submodule, before we merge the puppetserver PR to remove semantic puppet.. maybe? @Magisus

**Comment by Magisus** [comment]
Yes, a new agent with these changes will need to have passed CI. We update both our submodule and our agent SHA when that happens.

**Comment by joshcooper** [comment]
jenkins please test this on redhat7-64.,osx1012-64,windows2012r2-64

**Comment by joshcooper** [comment]
ah, forgot that puppet CI uses puppet-server... So I think this PR is blocked on getting semantic_puppet moved to the shared gem directory... Then we should be able to retest this & merge (as older 5.5.x servers know to look in the shared directory). Then we can merge the puppetserver PR.

**Comment by jtappa** [comment]
jenkins please test this on redhat7-64.,osx1012-64,windows2012r2-64

**Pull request merged**
