### PR TITLE
(PUP-9048) Make Debian init service provider default for Devuan

### PR DESCRIPTION
**Pull request by DarkGigaByte**
Since facter 3.7 Devuan will be detected as operatingsystem and should use the right service provider https://tickets.puppetlabs.com/browse/FACT-1579

### CODE REVIEW

**Comment by melissa** [comment]
Hi @DarkGigaByte!

Thank you for the contribution!

Could you add a test to `spec/unit/provider/service/debian_spec.rb` for this change as well? 

I noticed you targeted this change against the master branch. That means the next release this will be a part of will be Pupp 6.0. I have a feeling this will be useful to folks using the 5.5.x series as well. Could you retarget this PR? You should be able do that by editing this PR rather than opening a new one.

Let me know if you'd like any guidance!

**Comment by DarkGigaByte** [comment]
@melissa I did as you said, but this does not look right to me

**Comment by melissa** [comment]
Dang, I was hoping that would be a clean move. It looks like it'll be easiest to open a new PR in that case

**Comment by melissa** [comment]
The failure with travis is because of your commit message. You can either combine your testing change into your original commit, or amend your commit to add tests to have the `(maint)` prefix like your original commit has

**Comment by DarkGigaByte** [comment]
@melissa Have a look again, please.

**Comment by melissa** [comment]
The commits look good and the code looks good. However, this is still targeted at the master branch. We should get this change into 5.5.x! Would you like any help or guidance doing that?

**Comment by DarkGigaByte** [comment]
The more i think about it, the more i am confident that this should only be in version 6. I am changing default behaviour and thats a breaking change which does belong to a new major version.

**Comment by melissa** [comment]
Hey @DarkGigaByte I opened a ticket for this work https://tickets.puppetlabs.com/browse/PUP-9048. If you could update both your commit messages to change `(maint)` to `(PUP-9048)`, that'd be wonderful! Let me know if you want any guidance on how to do this

**Comment by DarkGigaByte** [comment]
Done.

**Comment by melissa** [comment]
Yeehaw! Let's get this in!

**Pull request merged**
