### PR TITLE
PUP-7685: puppet resource user may show double groups

### PR DESCRIPTION
**Pull request by jcpunk**
This patch resolves PUP-7685

### CODE REVIEW

**Comment by Magisus** [comment]
Would it be possible to update with some logic that will issue a debug message when it actually needs to do some deduplication? That might help users who know they should be seeing multiple groups to track down what Puppet is doing.

**Comment by jcpunk** [comment]
I've added a debug notice

**Comment by jhelwig** [comment]
@jcpunk I think @Magisus meant something along the lines of:
```ruby
dedup_groups = groups.uniq
if groups != dedup_groups
  debug("Duplicate groups have been removed")
end
dedup_groups.join(",")
```

This way the debug message only happens if there were duplicate groups.

**Comment by jcpunk** [comment]
I've updated the code based on the suggestion above

**Comment by Magisus** [comment]
Yes, that is the kind of thing I meant 👍

**Comment by jhelwig** [comment]
@jcpunk I tweaked the commit message a little to better fit with the convention we use (22312fd8d4e6d086d82e28ffcfcccf5993fc7cd1). The commit still credits you as the author, it just seemed a little silly to kick this out even further when the code itself looks fine. Thanks for doing this!

Merged via 21fda7d39d2cae5f83ca63071b1aa851274ed942.

**Comment by jhelwig** [comment]
Actually merged via 7f0c88fa0d8c35f6207498af9574f2a2ecb5742c (turns out that I pushed to the wrong repo for 21fda7d39d2cae5f83ca63071b1aa851274ed942 ☹️  ).

**Pull request closed without merging**
