### PR TITLE
(PUP-6430) Add Fedora 24 support for DNF

### PR DESCRIPTION
**Pull request by petems**
* Also add spec for default provider-ness

### CODE REVIEW

**Comment by whopper** [comment]
@petems thanks a bunch for doing this! You've been killing it lately! :D 

This is definitely good, and now the question is whether we should retarget it at stable for Puppet 4.5.3 (/cc @kylog). We even have F24 boxes in the vmpooler so I can hopefully test that F24 DNF plays nicely with the DNF provider.

**Comment by kylog** [comment]
I'm fine repointing this at stable for 4.5.3. Thanks @petems!

**Comment by whopper** [comment]
Gave this a quick manual test in F24, looks good! @petems I'll merge after you retarget this against stable! Thanks again!

**Comment by petems** [comment]
Re-opened against stable in https://github.com/puppetlabs/puppet/pull/5060 👍

**Pull request closed without merging**
