### PR TITLE
(maint) Adjust rake commit check for stable

### PR DESCRIPTION
**Pull request by MosesMendoza**
On PR https://github.com/puppetlabs/puppet/pull/5280 against puppet, the travis
CI commit check is failing because a prior commit unrelated to that PR be753a4
did not adhere to the commit guidelines and the underlying check code lists
commits unreachable from master to HEAD of the PR. This commit adjust this to
be stable, and this PR is intended for the stable branch only. On merge up to
master, the commit should be taken but master's version of this change
accepted (for example by doing git merge --no-commit, checking out master's version, and proceeding)

Signed-off-by: Moses Mendoza <moses@puppet.com>

### CODE REVIEW

**Comment by branan** [comment]
Instead of hard-coding this on any branches, can we just query it from the environment? (either git or Travis) Having it different on every branch is a great opportunity for us to break it during a merge-up or merge-down, and it is an extra thing to keep track of if we have to make additional branches

**Comment by branan** [comment]
It looks like there is a `TRAVIS_BRANCH` that shows the target of the PR

**Comment by MosesMendoza** [comment]
+1 on dynamically finding the branch. I just figured I'd make sure to do the merge-up, so we'd only have to handle it once, but I agree that's more brittle

**Comment by MosesMendoza** [comment]
@branan updated with dynamic check, but using `TRAVIS_COMMIT_RANGE` which actually works quite well for this purpose.

**Comment by Magisus** [comment]
Good catch on this! 👍 I find it funny that the commit that prompted us to look into this would have broken this check regardless...

**Pull request merged**
