### PR TITLE
(PUP-4712) fix environment scenario acceptance test nuances

### PR DESCRIPTION
**Pull request by er0ck**
This change fixes two environment scenario tests so they test against
the correct test environments.  Previously it erroneously used the
standard $codedir environmentpath.
This change also removes the duplicate explicit environment.conf test
which was incorrect and duplicated by another test.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
You should update your master branch, it doesn't appear to have appveyor.yml.

**Comment by MikaelSmith** [comment]
Which was the environment.conf test duplicating?

**Comment by er0ck** [comment]
I have an appveyor.yml

**Comment by er0ck** [comment]
the environment_scenario-with_explicit_environment_conf.rb test was duplicating, badly, this test: directory_environment_with_environment_conf.rb

**Comment by MikaelSmith** [comment]
Looks like it was your test in the first place; decided it was ill-advised?

**Comment by er0ck** [comment]
it does appear that way, but we really just split out a larger test of joshua partlow's. 
looks like neither one of us noticed the dupe...

**Comment by MikaelSmith** [comment]
:+1:

**Pull request merged**
