### PR TITLE
(PUP-10024) Add locking around environments

### PR DESCRIPTION
**Pull request by pcarlisle**
Lock when initializing properties on environment objects and when
handling the environment cache.

### CODE REVIEW

**Comment by Magisus** [comment]
From discussion in planning, the `ThreadLocalSingleton` class may also be applicable other places we use the singleton pattern, but it's unclear how many of those places _require_ it. I've filed https://tickets.puppetlabs.com/browse/PUP-10163 to track that work. I'll fill it in with the list of specific places soon.

**Comment by Magisus** [comment]
Does this PR need anything else or can it go in?

**Comment by justinstoller** [comment]
FWIW, I've used Patrick's testing tool and validated that I consistently get threading errors w/o this patch, but do not get them w/ this patch.  👍

**Comment by justinstoller** [comment]
Sorry, I just remembered two probably important things.
1) I included my in https://github.com/puppetlabs/puppet/pull/7745
2) the server did not shutdown correctly (though I assumed this was an issue with the jruby-utils PR)

**Comment by Magisus** [comment]
It seems like the shutdown issue may have to do with the combination of the jruby-utils PR and https://github.com/puppetlabs/puppetserver/commit/eb01e12aeb5d390b1b26591ffb1ddf759a539ccf, which causes shutdown to hang indefinitely. In the PR I've put up to integrate the new JRuby pool, I also revert that commit. Using that, shutdown seems to work fine for me.

**Pull request merged**
