### PR TITLE
(PUP-4466) Create acceptance tests for functions in the Puppet language

### PR DESCRIPTION
**Pull request by kurtwall**
(PUP-4466) Add new acceptance tests that validate basic user-level functionality where Puppet functions cross component boundaries. Unit testing already covers the 4x function API and specifically tests behavior around functions written in Puppet DSL.

### CODE REVIEW

**Comment by er0ck** [comment]
qpt2wdstbf7iufg.delivery.puppetlabs.net (master) executed in 1.74 seconds
tests/language/functions_in_puppet_language.rb passed in 6.62 seconds
      Test Suite: tests @ 2015-06-02 11:13:26 -0700

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 6.62 seconds
      Average Test Time: 6.62 seconds
              Attempted: 1
                 Passed: 1

**Comment by kylog** [comment]
Please amend the commit message to match CONTRIBUTING.md, specifically:
* prepend the ticket number surrouned by parens to the first line of the commit message
* put that first line in the imperative

Thanks!!

**Comment by er0ck** [comment]
@kurtwall puppet 4.2.0 is now on stable branch.  can you rebase this on stable and re-submit, please?

**Comment by hlindberg** [comment]
@fitteonge123 (e.g. in english "cuntbrat123", take your puerile nonsense elsewhere. If you are really bored, why not go an play blindfolded in heavy traffic today?).

**Comment by kurtwall** [comment]
Going to cherry pick the commit over to stable. Tried rebasing, ran into too many merge conflicts.

**Pull request closed without merging**
