### PR TITLE
Fixes #9224: Add assumeyes option to dnf module list

### LINKED ISSUE #9224: Provider dnfmodule prompts user to trust gpg key when performing module list
## Describe the Bug
When using the 'dnfmodule' provider, the following command is run: "/usr/bin/dnf module list -d 0 -e 1".  Because dnf module does not seem to use rpm imported gpg keys, the system prompts to trust the key.

## Expected Behavior
A puppet run should not fail due to a prompt for trusting the gpg key.  Perhaps adding the option "--assumeyes" or "-y" is needed.

## Steps to Reproduce
1. Install the REMI PHP repository on an Enterprise Linux v8 system - https://blog.remirepo.net/pages/Config-en.  
2. Configure the version of php to use
  ```
package {'php-module':
    name     => 'php',
    ensure   => "remi-8.1",
    provider => dnfmodule,
    require  => Package['remi-release'],
  }
```
3. A puppet run on client fails due to a prompt to trust the remi gpg key.  Note that importing beforehand, E.g., rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-remi* does not help with the initial dnf module list.

## Environment
 - Version = 7.28.0
 - Platform = Oracle Linux v8

### PR DESCRIPTION
**Pull request by loopiv**

### CODE REVIEW

**Comment by loopiv** [comment]
See #9224

**Review by joshcooper — APPROVED** [review]
agree it's consistent with the rest of the dnf commands that the provider executes

**Comment by joshcooper** [comment]
Can you rebase your changes on `main` to pickup a fix for Windows spec tests

**Comment by loopiv** [comment]
> Can you rebase your changes on `main` to pickup a fix for Windows spec tests

Rebased and pushed.

**Review by cthorn42 — APPROVED** [review]
@loopiv thank you for the contribution.

**Pull request merged**
