### PR TITLE
(PUP-8822) Remove Host type and provider

### PR DESCRIPTION
**Pull request by joshcooper**
The host type, provider, fixtures, and tests have been extracted to
https://github.com/puppetlabs/puppetabs-host_core.

### CODE REVIEW

**Comment by joshcooper** [comment]
jenkins please test this on debian9-64a,windows2012r2-64a,fedora27-64a,osx1013-64a,sles12-64a,solaris11-64a

**Comment by joshcooper** [comment]
Blocked on https://github.com/puppetlabs/puppet-agent/pull/1480 and getting a green CI post merge.

**Comment by joshcooper** [comment]
jenkins please test this on debian9-64a,windows2012r2-64a,fedora27-64a,osx1013-64a,sles12-64a,solaris11-64a

**Comment by melissa** [comment]
I verified these files are being included in the vendored_module directory from puppet-agent 5.99.1.55.g41aa8f4-1.el7
```
[root@xdp1b7u9owmw90p ~]# tree /opt/puppetlabs/puppet/vendor_modules/host_core/


/opt/puppetlabs/puppet/vendor_modules/host_core/
├── appveyor.yml
├── CHANGELOG.md
├── Gemfile
├── lib
│   └── puppet
│       ├── provider
│       │   └── host
│       │       └── parsed.rb
│       └── type
│           └── host.rb
├── metadata.json
├── Rakefile
├── README.md
├── REFERENCE.md
└── spec
    ├── acceptance
    │   ├── nodesets
    │   │   └── default.yml
    │   └── tests
    │       ├── create_spec.rb
    │       ├── destroy_spec.rb
    │       ├── modify_spec.rb
    │       └── query_all_spec.rb
    ├── default_facts.yml
    ├── fixtures
    │   └── unit
    │       └── provider
    │           └── host
    │               └── parsed
    │                   └── valid_hosts
    ├── lib
    │   └── puppet_spec
    │       └── files.rb
    ├── shared_behaviours
    │   └── all_parsedfile_providers.rb
    ├── spec_helper_acceptance.rb
    ├── spec_helper_local.rb
    ├── spec_helper.rb
    └── unit
        ├── provider
        │   └── host
        │       └── parsed_spec.rb
        └── type
            └── host_spec.rb

21 directories, 23 files
```

**Pull request merged**
