### PR TITLE
(PUP-4056) Use privatebindir to resolve ruby

### PR DESCRIPTION
**Pull request by joshcooper**
* Prepends privatebindir to the PATH environment used to execute `ruby` and `gem` on all hosts.
* For ruby-based ENC scripts executing on the master, resolve `ruby` relative to `privatebindir`.
* Moves the beaker pin to the version that contains the AIO pathing changes
* Removes the AIO path overrides from node config files

### CODE REVIEW

**Comment by joshcooper** [comment]
```
$ be rake ci:test:aio SHA=58fbddcf1973262126a3f6699fdb929e4e78a6a5 CONFIG=config/nodes/rhel7.yaml TESTS=tests
...
              - Test Case Summary for suite 'tests' -
       Total Suite Time: 7076.47 seconds
      Average Test Time: 26.70 seconds
              Attempted: 265
                 Passed: 212
                 Failed: 0
                Errored: 0
                Skipped: 52
                Pending: 1
                  Total: 265
```

**Comment by joshcooper** [comment]
This should be merged after PR #3698

**Comment by kylog** [comment]
:+1: 

Not following why the PR ordering matters though. Maybe it will all make sense with coffee :)

**Comment by joshcooper** [comment]
> Maybe it will all make sense with coffee :)

Hmm I think maybe I need more coffee... I was thinking moving the beaker pin had to be the last thing, but I don't think that's strictly true.

**Pull request merged**
