### PR TITLE
(PUP-7790) downgrading package with pkgin

### PR DESCRIPTION
**Pull request by andrewh1978**
Use `pkg_add -U` instead of pkgin

### CODE REVIEW

**Comment by joshcooper** [comment]
@andrewh1978 Thank you for your contribution. Do you have an idea when the upstream bug might be fixed? Are there any other behavior changes when moving to `pkg_add -U` (aside from fixing this one issue)?

**Comment by andrewh1978** [comment]
This will not affect behavior of anything else. I have no timescale for a resolution to the upstream bug, and even when it is fixed there will be users running old pkgsrc on old images. Given `pkgin` is a wrapper around `pkg_add` et al, this is arguably the right way to go anyway.

**Comment by Magisus** [comment]
Looks like some specs are failing. Can you update the tests to reflect your change?

**Comment by Magisus** [comment]
In order to fix the failing specs, you need to update the case that is failing to take into account the new `pkg_add` command. Line 28 of the `pkgin_spec` should be updated to
```
subject.expects(:pkg_add).with("-U", "vim-7.2.446").once()
```
since this is what your new code expects.

**Comment by Magisus** [comment]
Looks good now. @joshcooper could you take a look here and merge if this seems reasonable to you?

**Comment by branan** [comment]
I'm not really familiar enough with the *bsd package manager ecosystem to make a judgement call on this. My questions/comments:

* pkgin seems like it has its own database. Is this actually shared by pkg_add? Does this replacement of pkgin by pkg_add only work for locally-downloaded package files?

* The pkgin website seems to imply that there are cases where pkg_add doesn't work right, so just always calling out to pkg_add is a bit scary to me. Do you have any idea of the details of this other than the insinuation in the pkgin docs?

**Comment by MosesMendoza** [comment]
It looks like [the issue](https://github.com/NetBSDfr/pkgin/issues/73) has gotten some upstream attention:
> This diff appears to resolve the problem:...
> I think this is correct (ignore the downgrade problem if the package has been directly specified), but I'm going to leave it to bake in the SmartOS 2017Q3 builds first before committing here.

Commits were pushed 17 days ago. Since these formats do appear to use different databases and to avoid risk of unexpected regression, I'm inclined to leave this as-is and wait for upstream resolution, so I'm going to close this now. Thank you for bringing it to our attention.

**Pull request closed without merging**
