### PR TITLE
(PUP-5867) Add acceptance test for cached catalog status in report

### PR DESCRIPTION
**Pull request by whopper**

### CODE REVIEW

**Comment by whopper** [comment]
Blocked until 4.4.0 is tagged.

**Comment by seangriff** [comment]
Looks like a rebase is needed.

**Comment by whopper** [comment]
Rebased and verified with `TEST_TARGET=redhat7-64a MASTER_TEST_TARGET=redhat7-64ma`

**Comment by joshcooper** [comment]
LGTM, merging

**Pull request merged**
