### PR TITLE
(docs) Revise description of trusted_server_facts setting

### PR DESCRIPTION
**Pull request by nfagerlund**

### CODE REVIEW

**Comment by joshcooper** [comment]
After merging, please regenerate man pages, eg https://github.com/puppetlabs/puppet/pull/3947

**Comment by kylog** [comment]
@hkenney or @hlindberg can you review?

**Comment by hkenney** [comment]
:+1:  Looks good! One thought:

I'm not sure whether or not we need to explicitly make the distinction between what changes in an agent run vs apply. With an apply only the environment part of the hash will be present. That may be too low level for the user to care about, not sure.

**Comment by kylog** [comment]
@nfagerlund thoughts on ^ ??

**Comment by nfagerlund** [comment]
@hkenney @kylog I think the right place for that level of detail is probably in the language reference where we talk about these pre-populated variables, not in the list of settings. I'm cool with leaving the setting description pretty high-level.

**Comment by hkenney** [comment]
That seem's totally reasonable to me. I'm :+1: on merging this as is.

**Comment by ferventcoder** [comment]
Note that Travis CI ran a build but appveyor did not. :)

**Comment by ferventcoder** [comment]
This means the AppVeyor filters are working appropriately.

**Pull request merged**
