### PR TITLE
(PUP-6958) Fix gem packaging to properly include i18n files

### PR DESCRIPTION
**Pull request by Magisus**
This PR contains two commits, one of which ensures that the `locales` directory is properly packaged with the gem, and a second which removes the build-time dependency on the `gettext-setup` gem.

### CODE REVIEW

**Comment by underscorgan** [comment]
👍 looks reasonable from an RE standpoint

**Comment by Magisus** [comment]
Verified that it builds successfully (http://jenkins-release.delivery.puppetlabs.net/job/puppet-packaging-2017-01-12-11-43-41-8c89f5a2ee5c5025848790444492195277e2dc40/1/) and that the resulting gem contains the `locales` dir and runs correctly.

**Comment by MosesMendoza** [comment]
reviewing

**Comment by MosesMendoza** [comment]
Can we remove these two comments now? https://github.com/Magisus/puppet/blob/8c89f5a2ee5c5025848790444492195277e2dc40/lib/puppet.rb#L47-L56

**Comment by Magisus** [comment]
Yes, it can just use the local path. Updated.

**Comment by Iristyle** [comment]
👍

**Pull request merged**
