### PR TITLE
(maint) Add comment for updating limits with systemd

### PR DESCRIPTION
**Pull request by underscorgan**

### CODE REVIEW

**Comment by melissa** [comment]
I've already approved this PR, but here's a 👍 for posterity's sake.

**Comment by MosesMendoza** [comment]
Hi @underscorgan! Would you mind adding some context to the commit message about what this change does and why you're making it? Currently the commit message is empty. Also was there some ticket behind this change?

**Comment by underscorgan** [comment]
Hey @MosesMendoza , there's an internal RE ticket so I didn't reference it here.  I'll update the commit message.

**Comment by MosesMendoza** [comment]
Great, thanks!

**Pull request merged**
