### PR TITLE
(PUP-10240) Move development gem dependencies to .gemspec

### PR DESCRIPTION
**Pull request by joshcooper**
Move development gem dependencies from the Gemfile to .gemspec and project_data.yaml. As a result, the dependencies are included in the published puppet gem.

It is no longer possible to specify `RAKE_LOCATION` as an environment variable,
but that is no longer needed in 6.x, as we relaxed the constraint in 2c6bdea.

### CODE REVIEW

**Comment by joshcooper** [comment]
I forgot the `package:gem` task from the packaging repo uses `ext/project_data.yml` when building the gem 🤦‍♂ Let me update that.

**Comment by melissa** [comment]
@shrug can someone from RE take a look at this too?

**Comment by joshcooper** [comment]
ah, sorry, yeah, best to run `bundle exec rake package:gem`, which produces 4 gems in the pkg directory. If you run `gem dependency pkg/puppet*gem` on each, it'll spit out which dependencies are `runtime` vs `development`.

**Comment by joshcooper** [comment]
hmm something is not right:

```
root@sacred-brew:~# gem install --development puppet-6.12.0.56.gem
Fetching: rspec-support-3.9.2.gem (100%)
Successfully installed rspec-support-3.9.2
Fetching: rspec-core-3.9.1.gem (100%)
Successfully installed rspec-core-3.9.1
Fetching: rspec-3.9.0.gem (100%)
ERROR:  Error installing puppet-6.12.0.56.gem:
	rspec requires rspec-expectations (~> 3.9.0)
```

**Comment by melissa** [comment]
```
[root@rococo-vision ~]# gem install --development-all puppet-6.12.0.72.gem
ERROR:  While executing gem ... (Gem::Resolver::Molinillo::CircularDependencyError)
    There is a circular dependency between cucumber and rspec
```

**Comment by joshcooper** [comment]
Yeah, unfortunately I think `--development-all` means install the dev gems from all of the dependencies too, which we don't want. I even tried adding `rspec-expectations (~> 3.9.0)` to puppet's project_data.yaml and it didn't help... it so bizzare.

**Comment by jtappa** [comment]
Added @puppetlabs/release-engineering as a reviewer. :) 

Context: These are getting moved so they're available in the published gem for developers, not just here from running a development environment based on the repo.

**Comment by joshcooper** [comment]
Going to close this and revisit later

**Pull request closed without merging**
