### PR TITLE
(packaging) Update puppet version to 4.10.7

### PR DESCRIPTION
**Pull request by McdonaldSeanp**

### CODE REVIEW

**Comment by ehelms** [comment]
Does this mean we should be expecting a new release soon? I'm new to the repository and process, but eager to see my first patch out in the wild in a release.

**Comment by Magisus** [comment]
We will be releasing your patch soon, but not from this branch. Yours will go out in our upcoming 5.2.0 release off of master.

**Comment by ehelms** [comment]
Thanks for the info @Magisus . Might I still ask if there is a planned release timeline for 4.10.7? I assume since my patch went into this 4.10.x branch that it would be included there.

**Comment by Magisus** [comment]
Oh, yes it did, my bad. We are planning to release this in the first half of September.

**Comment by ehelms** [comment]
Thanks so much @Magisus

**Pull request merged**
