### PR TITLE
(PUP-11232) Add `frozen_string_literal` to lower memory consumption

### PR DESCRIPTION
**Pull request by luchihoratiu**
After changes from f8827f83cbbe316e0399b76f2e42f6411e532729, memory consumption of puppet/lib drops from `150653689` to `135704679`.

With 932d2f630a6b071639a142788f86bd666d6f596b, memory consumption of puppet/lib drops even further to `135338732`. This is achieved by adding `frozen_string_literal: true` in `lib/puppet/pops/model/factory.rb` and `lib/puppet/pops/types/type_formatter.rb` and calling `dup` method on strings that need to be modified during a run.

305be0d17f21080b736cc179bf2d277b6ade366b simply removes `freeze` method calls on Strings in `lib/puppet/pops/parser/lexer2.rb` since `frozen_string_literal: true` makes them unnecessary and aligns some code columns.

### CODE REVIEW

**Comment by luchihoratiu** [comment]
jenkins please test this on all

**Review by joshcooper — APPROVED** [review]
LGTM, I see a similar reduction, about 10% when running the full_memory benchmark:

Before `Total allocated: 149831113 bytes (2083692 objects)`
After `Total allocated: 134896393 bytes (1758330 objects)`

The remaining allocations are dominated by:
```
allocated memory by file
-----------------------------------
  53077807  /home/josh/work/puppet/lib/puppet/pops/parser/lexer2.rb
   9915153  /home/josh/work/puppet/lib/puppet/resource.rb
   6782888  /home/josh/work/puppet/lib/puppet/pops/model/factory.rb
```

I'm guessing the lexer2 allocations are due to the closure scope bound to each lambda? I'm thinking Ruby may be doing more work than is necessary to create the `Binding` as each token is scanned and the corresponding lambda is called? Or perhaps it's the `byteslice` calls? In any case, that's a separate issue from this PR.

**Comment by luchihoratiu** [comment]
jenkins please test this on all

**Comment by luchihoratiu** [comment]
@joshcooper, I've created [PUP-11236](https://tickets.puppetlabs.com/browse/PUP-11236) for lexer2 investigation and I've also added 2 more commits here. Please let us know if 932d2f630a6b071639a142788f86bd666d6f596b especially raises any concerns 😄

**Comment by luchihoratiu** [comment]
jenkins please test this with servertests

**Review by joshcooper — APPROVED** [review]
I wasn't sure if you had anything else planned, do I didn't merge, but it looks good to me

**Pull request merged**
