### PR TITLE
(maint) Set server in main section of conf

### PR DESCRIPTION
**Pull request by justinstoller**
The puppetserver ca cli tool needs the value of the server set in "main"
or "master" sections of the puppet.conf to function correctly.

Previously we updated the main portions of the autosign and certificate
extension tests to set server in the master section and removed our
passing of --server to the agent.

The agent however will not see the server setting in the master
section. This moves the server setting to the main section. It
additionally wraps the teardown calls to puppetserver ca in a
with_puppet_running to with server set.

### CODE REVIEW

**Comment by justinstoller** [comment]
Opened while I wait for the tests to actually run locally. If they do fine I'll queue up the whole suite here.

**Comment by justinstoller** [comment]
jenkins please test servertests

**Comment by justinstoller** [comment]
Didn't actually run the tests, failed with:
`java.lang.IllegalArgumentException: The 'ABS_RESOURCE_REQUESTS_beaker_servertests' build parameter is missing`

Will try again tomorrow.

**Comment by Magisus** [comment]
I think the invocation is "jenkins please test this". Maybe the "this" helps it know what resources to allocate?

**Comment by justinstoller** [comment]
jenkins please test this servertests

**Comment by justinstoller** [comment]
I think this is ready to go

**Comment by Magisus** [comment]
Does this need to go to 6.0.x? I a see a puppetserver job failing with these failures on that branch.

**Comment by Magisus** [comment]
Closing and reopening to fix Appveyor

**Comment by Magisus** [comment]
So I think something got kinda messed up here with the retargeting. I dropped these changes on top of 6.0.x and put that up here: https://github.com/puppetlabs/puppet/pull/7271 Going to run the tests there and see if things clear up.

**Comment by justinstoller** [comment]
Oh weird. I totally see what the problem is, I don't know why a rebase would have changed that...

**Comment by Magisus** [comment]
I hear that the Travis issue is unrelated and should be ignored.

**Comment by justinstoller** [comment]
jenkins please test this servertests

**Pull request merged**
