### PR TITLE
(PUP-3539) add specs globbing ACL in fileserver.conf

### PR DESCRIPTION
**Pull request by er0ck**
ENTERPRISE-361 reported on regression in fileserver.conf which did not
allow globbing subdomains.  Allow in
file_serving/configuration/parser.rb sets simple comma separated allows
in mount.allow, which inherits from network/authconf allow, where most
of the testing lives. This change adds tests that ensure we are sending
the correct patterns to mount.allow.

### CODE REVIEW

**Comment by kurtwall** [comment]
Passed on stable and master:
```
[kwall@breve puppet]$ bundle exec rspec -fd spec//unit/file_serving/configuration/parser_spec.rb
Run options: exclude {:broken=>true, :benchmark=>true}

Puppet::FileServing::Configuration::Parser
  Puppet::FileServing::Configuration::Parser  when parsing
    should allow comments
    should allow blank lines
    should create a new mount for each section in the configuration
    should return a hash of the created mounts
    should only allow mount names that are alphanumeric plus dashes
    should fail if the value for path/allow/deny starts with an equals sign
    should validate each created mount
    should fail if any mount does not pass validation
    should return comprehensible error message, if invalid line detected
  Puppet::FileServing::Configuration::Parser  when parsing mount attributes
    should set the mount path to the path attribute from that section
    should tell the mount to allow any allow values from the section
    should support inline comments
    should tell the mount to deny any deny values from the section
    should return comprehensible error message, if failed on invalid attribute
  Puppet::FileServing::Configuration::Parser  when parsing the modules mount
    should create an instance of the Modules Mount class
    should warn if a path is set
  Puppet::FileServing::Configuration::Parser  when parsing the plugins mount
    should create an instance of the Plugins Mount class
    should warn if a path is set

Finished in 0.03696 seconds (files took 0.49008 seconds to load)
18 examples, 0 failures
```

**Comment by ferventcoder** [comment]
AppVeyor failures are the rdoc parser

**Comment by kurtwall** [comment]
Merging. Failures are unrelated.

**Comment by kurtwall** [comment]
Merging. Failures are unrelated.

**Pull request merged**
