### PR TITLE
(PUP-9932) Add locking around loaders

### PR DESCRIPTION
**Pull request by pcarlisle**

### CODE REVIEW

**Comment by pcarlisle** [comment]
haven't had a chance to test anything with this yet

**Comment by Magisus** [comment]
This does not seem to fix the issues I'm seeing when using environment caching.

Example, this pair of errors from our `thread_test/test.rb`:
```
"Server Error: Class 'threader::params_class' is already defined (file: /Users/aileen/code/server/puppetserver/ext/thread_test/environments/production/modules/threader/manifests/params_class.pp, line: 1); cannot redefine (file: /Users/aileen/code/server/puppetserver/ext/thread_test/environments/production/modules/threader/manifests/params_class.pp, line: 1) on node testone"
```
```
"Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::threader::params_class for testtwo (file: /Users/aileen/code/server/puppetserver/ext/thread_test/environments/funky/manifests/init.pp, line: 9, column: 1) on node testtwo"
```

**Comment by Magisus** [comment]
I filed https://tickets.puppetlabs.com/browse/PUP-10318 for the first two errors I mention above. Since this PR is supposed to address 3x functions, I guess it makes sense that it fixes the third error, since that the the 3x function in our test. Note that that last error also only manifests when using environment caching, which is why we hadn't seen it till we started playing around with that.

**Comment by Magisus** [comment]
Jenkins please test this with servertests

**Comment by Magisus** [comment]
Is there something else blocking this? Notice it still has "DO NOT MERGE".

**Comment by tvpartytonight** [comment]
The catalog benchmark, `benchmark:full_catalog:run`, doesn't show any real noticeable diffs with the average, so I think we are safe merging this from the perspective.

> PR
> 30 iterations
> > total:   156.890000   4.910000 161.800000 ( 71.256732)
> > avg:       5.229667   0.163667   5.393333 (  2.375224)
> 
> Master
> On master with 30
> > total:   144.660000   4.650000 149.310000 ( 67.900437)
> > avg:       4.822000   0.155000   4.977000 (  2.263348)

**Comment by justinstoller** [comment]
Is that MRI or JRuby?

**Comment by tvpartytonight** [comment]
It is in jruby 9.2.9.0.

**Pull request merged**
