### PR TITLE
(PUP-6318) Add --no-batch-files option to install.rb

### PR DESCRIPTION
**Pull request by McdonaldSeanp**
Cherry-pick https://github.com/puppetlabs/puppet/pull/4968 and https://github.com/puppetlabs/puppet/pull/4979 to stable

### CODE REVIEW

**Comment by geoffnichols** [comment]
👍

**Comment by joshcooper** [comment]
Ping @McdonaldSeanp @geoffnichols does this need to be merged to stable

**Comment by McdonaldSeanp** [comment]
@joshcooper This is a judgement call. During a previous mergeup from master to stable of P-A we grabbed some of the windows/vanagon work, which caused some breakages. The breakages happened because I added some --no-batch-files options to the puppet/facter/hiera/mco configs in P-A which were carried over during the mergeup. But the component changes to actually create those options weren't picked up yet. 

So this is one of those component changes to create the option. The judgement call comes in because the builds are no longer failing, during the build process there will be a warning about this option not existing, but nothing will fail.

Because we are not shipping the windows/vanagon MSI for 1.5.3 this can be left alone and should not affect any other platform.

**Comment by joshcooper** [comment]
So sounds like we can close the PR?

**Comment by McdonaldSeanp** [comment]
I believe so yes.

**Pull request closed without merging**
