### PR TITLE
(PUP-7599) Fix authorized keys acceptance tests

### PR DESCRIPTION
**Pull request by LuvCurves**
New version of beaker exposed an oversight in the tests that
the user would be root, this is not the case on Cisco Nexus

### CODE REVIEW

**Comment by Magisus** [comment]
So log name is already getting set somewhere?

**Comment by LuvCurves** [comment]
@Magisus It's set as part of the environment when you login.

**Comment by johnduarte** [comment]
@Magisus yeah, I scratched my head on that for a sec too. `LOGNAME` is a POSIX env var that is available to the session.
@LuvCurves can you add a comment about the nature of `LOGNAME`? I don't know if this will cause problems with Windows when/if we migrate off of Cygwin.

**Comment by LuvCurves** [comment]
@johnduarte This test is not run on windows, or it would have broken too (there is no root on Windows)

**Comment by LuvCurves** [comment]
@johnduarte I'll push a comment to the commit shortly.

**Comment by LuvCurves** [comment]
@johnduarte Added comment to commit about LOGNAME

**Comment by LuvCurves** [comment]
@Magisus tested:
      Test Suite: tests @ 2017-05-26 21:16:32 +0000

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 6.24 seconds
      Average Test Time: 1.56 seconds
              Attempted: 4
                 Passed: 3
                 Failed: 0
                Errored: 0
                Skipped: 1
                Pending: 0
                  Total: 4

      - Specific Test Case Status -

**Pull request merged**
