### PR TITLE
(PUP-6621) Log corrective_change exceptions at info instead of error level

### PR DESCRIPTION
**Pull request by branan**
Previously, when a custom type was incompatible with corrective
change, it would log any exception caught at the error level. This
causes Puppet to fail the transaction.

Instead, we should log at a lower level, so that users can look into
making their types compatible without causing catalog applications to
fails in the meantime.

### CODE REVIEW

**Comment by kbarber** [comment]
Warning instead? I don't mind dropping it from an error though.

**Comment by branan** [comment]
@kbarber The problem is that it's not necessarily in the user's control - 3rd party modules are a pretty likely source of custom types. Spitting out a bunch of warnings at users when it's not their fault isn't super cool. I'd rather log at a lower level, and be able to give them instructions "If corrective change isn't being reported for certain resources, you can find out what error your type is having by looking at the logs"

**Comment by branan** [comment]
Specifically, a ton of stuff in our Cisco integrations isn't playing nice (some horrible munge/validate things that I'm going to try to fix). Having every user of that end up with lots of warnings in their logs and reports sounds nasty to me :(

**Comment by kbarber** [comment]
Well, info will show up in their logs and reports anyway. So you're concern isn't the volume of data, its the level and I guess the CLI log color that is chosen. I'm okay with whatever tbh. To debug, it will require --trace at the end of the day, so as long as that works the same I think we can deal with whatever choices we make.

**Comment by branan** [comment]
@kbarber Info level avoids upsetting the sorts of users that have their cron jobs set to email them any time a job prints "warning". It happens, and they tend to be grumpy when we introduce new warnings that they can't silence :)

**Comment by branan** [comment]
I'd rather it still be printed and in logs for visibility on manual expansion, just trying to be at a level that avoids automated tooling waking people up at night

**Comment by kbarber** [comment]
As an aside I'm +1 on allowing log_exception to accept different levels, I want to use this in app_modeling (so outside of puppet core), since sometimes our tests throw exceptions in third party code that is impossible to debug if we just grab the exception message.

**Pull request merged**
