### PR TITLE
(docs) fixing an outdated link.

### PR DESCRIPTION
**Pull request by jtappa**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
@kylog I don't see the commits task failing. It should fail on `(docs)` (as opposed to `(doc)`).

**Comment by kylog** [comment]
@MikaelSmith good catch! Thanks. Addressed in #4122.

**Comment by kylog** [comment]
And in hiera at https://github.com/puppetlabs/hiera/pull/284

**Comment by MikaelSmith** [comment]
@jtappa can you change the commit prefix to `(doc)`?

**Comment by jtappa** [comment]
@MikaelSmith does the whole PR have to change, or just the commit?

**Comment by MikaelSmith** [comment]
Just the title of the commit, with `git commit --amend` and force push.

**Comment by jtappa** [comment]
@MikaelSmith done

**Pull request merged**
