### PR TITLE
(docs) lib/puppet/type/exec.rb `unless` `grep(1)` anchors

### PR DESCRIPTION
**Pull request by photograveur**
The shown `grep(1)` example is missing begin‑of‑line/end‑of‑line anchors.

### CODE REVIEW

**Comment by joshcooper** [comment]
Hi @photograveur, thank you for your contribution! We no longer have a trivial patch exemption. You can read more about that here https://puppet.com/blog/puppets-updated-contributor-license-agreement-cla/ If you amend your commit message and sign the CLA, we will gladly merge this.

**Comment by photograveur** [comment]
Hi @joshcooper, thank you for your response. How should I amend my commit message?

**Comment by joshcooper** [comment]
Hi @photograveur, ah yeah, sorry we need to update https://github.com/puppetlabs/puppet/blob/main/CONTRIBUTING.md#making-trivial-changes We'll fix that in https://tickets.puppetlabs.com/browse/PUP-8241

In the meantime, could remove the sentence "I claim the TPE applies." from your git commit and force push to your feature branch?

**Comment by joshcooper** [comment]
Hi @photograveur thank you for your contribution! I think there was an issue with your rebase, so I cherry picked your first commit into a new PR, against 6.x, while preserving you as the original author. This will be released in the next 6.x and 7.x releases. Thanks!

**Pull request closed without merging**
