### PR TITLE
Task/5.3.x/pup 8459/add test for enc regression

### PR DESCRIPTION
**Pull request by ericldelaney**
Update a subset of the enc tests
Add a test to verify that we're only compiling and caching the catalog once. (The test catches the regression on agent 5.3.4)

### CODE REVIEW

**Comment by ericldelaney** [comment]
jenkins please test this on arista4-32,ciscoxr-64,cumulus25-64,debian7-32a,osx1011-64,redhat5-64,sles11-64,solaris11-64,windows2012r2-64,fedora26-64

**Comment by jhelwig** [comment]
In one of the commit messages "quoating" -> "quoting"

**Comment by ericldelaney** [comment]
jenkins please test this on arista4-32,ciscoxr-64,cumulus25-64,debian7-32a,osx1011-64,redhat5-64,sles11-64,solaris11-64,windows2012r2-64,fedora26-64

**Comment by joshcooper** [comment]
PR testing is blocked on https://github.com/puppetlabs/ci-job-configs/pull/4107

**Comment by joshcooper** [comment]
jenkins please test this on arista4-32,ciscoxr-64,cumulus25-64,debian7-32a,osx1011-64,redhat5-64,sles11-64,solaris11-64,windows2012r2-64,fedora26-64

**Comment by joshcooper** [comment]
jenkins please test this on arista4-32,ciscoxr-64,cumulus25-64,debian7-32a,osx1011-64,redhat5-64,sles11-64,solaris11-64,windows2012r2-64,fedora26-64 with agent 5.3.x

**Comment by joshcooper** [comment]
For some reason it doesn't look like my ci-job-configs PR switched `SERVER_VERSION` from `nil` to `5.1.5`. I manually rekicked this PR test with the right `SERVER_VERSION`, but @ericldelaney can you look into why the initial PR job doesn't have the right `SERVER_VERSION`?

**Comment by ericldelaney** [comment]
jenkins please test this

**Comment by ericldelaney** [comment]
jenkins please test this on arista4-32,ciscoxr-64,cumulus25-64,debian7-32a,osx1011-64,redhat5-64,sles11-64,solaris11-64,windows2012r2-64,fedora26-64 with agent 5.3.x

**Comment by ericldelaney** [comment]
jenkins please test this on arista4-32,ciscoxr-64,cumulus25-64,debian7-32a,osx1011-64,redhat5-64,sles11-64,solaris11-64,windows2012r2-64,fedora26-64

**Comment by ericldelaney** [comment]
jenkins please test this

**Comment by ericldelaney** [comment]
jenkins please test this on arista4-32,ciscoxr-64,cumulus25-64,debian7-32a,osx1011-64,redhat5-64,sles11-64,solaris11-64,windows2012r2-64,fedora26-64

**Pull request merged**
