### PR TITLE
(PUP-11976) adjust package/service providers for Amazon Linux 2023

### PR DESCRIPTION
**Pull request by vchepkov**

### CODE REVIEW

**Comment by joshcooper** [comment]
Jenkins please test this on amazon6-64a,amazon7-64a,fedora36-64a,redhat6-64a,redhat6-32a,redhat7-64a,redhat8-64a,redhat9-64a,redhatfips7-64a,redhatfips8-64a,almalinux8-64a,rocky8-64a

**Comment by joshcooper** [comment]
Jenkins please test this on amazon6-64a,amazon7-64a,fedora36-64a,redhat6-64a,redhat6-32a,redhat7-64a,redhat8-64a,redhat9-64a,redhatfips7-64a,redhatfips8-64a,almalinux8-64a,rocky8-64a with agent 7.x

**Comment by joshcooper** [comment]
Jenkins please test this on amazon7-64a,fedora36-64a,redhat7-64a,redhat8-64a,redhat9-64a,redhatfips7-64a,redhatfips8-64a,almalinux8-64a,rocky8-64a

**Review by joshcooper — APPROVED** [review]

**Comment by joshcooper** [comment]
@vchepkov I assume we want this in 7.x? If so, you could rebase this change on 7.x and change the base branch for the PR?

**Comment by vchepkov** [comment]
> @vchepkov I assume we want this in 7.x? If so, you could rebase this change on 7.x and change the base branch for the PR?

Yes, I need this in LTS. I will rebase. thank you

**Comment by vchepkov** [comment]
rebase fails, I will try to create new commit on top of 7.x

**Pull request merged**
