### PR TITLE
(PUP-6844) Ignore Mercurial artifacts

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by Iristyle** [comment]
Do we want to add the "for pluginsync" qualifier to the PR / ticket / commit msg?

**Comment by branan** [comment]
Yeah, I'd like to see the commit message be a bit more fleshed out

**Comment by ghoneycutt** [comment]
From the contributors perspective, this process is not awesome :(

I think you can squash and merge and change my commit message. Or let me know what it should be and I'm happy to change it. Having me wait three weeks to say the commit message could be improved is not a great experience.

**Comment by whopper** [comment]
Sorry @ghoneycutt, agreed that sucks and we need to do better. I'll take care of the message and get this merged in.

**Comment by whopper** [comment]
Closing in favor of https://github.com/puppetlabs/puppet/pull/5392

**Comment by ghoneycutt** [comment]
Thanks everyone, the work is much appreciated! I was attempting to be constructive with my criticism above and hope it was received that way.

**Pull request closed without merging**
