### PR TITLE
(PUP-10670) Create `serverport` setting and alias

### PR DESCRIPTION
**Pull request by GabrielNagy**
This commit creates a `serverport` setting which serves the same
functionality as `masterport`. Update the puppet code itself to use the
new setting, and add a hook to the old one to always set the new one as
well.

TBD: are we deprecating the `masterport` setting?

### CODE REVIEW

**Comment by ciprianbadescu** [comment]
The behavior does not look right:
```cbadescu@ciprian:~/puppetlabs/puppet$ bx puppet config set masterport 9876
cbadescu@ciprian:~/puppetlabs/puppet$ bx puppet config print masterport
Warning: Setting 'masterport' is being deprecated in favor of 'serverport'.
   (location: /home/cbadescu/puppetlabs/puppet/lib/puppet/defaults.rb:1368:in `block in initialize_default_settings!')
9876
cbadescu@ciprian:~/puppetlabs/puppet$ bx puppet config print serverport
Warning: Setting 'masterport' is being deprecated in favor of 'serverport'.
   (location: /home/cbadescu/puppetlabs/puppet/lib/puppet/defaults.rb:1368:in `block in initialize_default_settings!')
9876
```

**Comment by GabrielNagy** [comment]
@ciprianbadescu I removed that warning, it's kinda noisy as it shows up for any setting you query if you have the `masterport` set somewhere.

We have some more `masterport` references in the `ext/` directory. I left them as is, but something tells me these aren't used anymore:
```
ext/suse/server.init
45:[ -n "$PUPPETMASTER_PORTS" ] && PUPPETMASTER_OPTS="${PUPPETMASTER_OPTS} --masterport=${PUPPETMASTER_PORTS[0]}"

ext/redhat/server.init
27:[ -n "$PUPPETMASTER_PORTS" ] && PUPPETMASTER_OPTS="${PUPPETMASTER_OPTS} --masterport=${PUPPETMASTER_PORTS[0]}"

ext/debian/puppetmaster.init
53:            --startas $DAEMON -- $NAME $DAEMON_OPTS --masterport=$PORT
```

**Comment by GabrielNagy** [comment]
jenkins please test this with servertests

**Comment by ciprianbadescu** [comment]
> We have some more `masterport` references in the `ext/` directory. I left them as is, but something tells me these aren't used anymore:
> 
> ```
> ext/suse/server.init
> 45:[ -n "$PUPPETMASTER_PORTS" ] && PUPPETMASTER_OPTS="${PUPPETMASTER_OPTS} --masterport=${PUPPETMASTER_PORTS[0]}"
> 
> ext/redhat/server.init
> 27:[ -n "$PUPPETMASTER_PORTS" ] && PUPPETMASTER_OPTS="${PUPPETMASTER_OPTS} --masterport=${PUPPETMASTER_PORTS[0]}"
> 
> ext/debian/puppetmaster.init
> 53:            --startas $DAEMON -- $NAME $DAEMON_OPTS --masterport=$PORT
> ```

I think they can be set from places like `/etc/sysconfig/puppet`, I suppose should be adapted

**Comment by joshcooper** [comment]
> TBD: are we deprecating the masterport setting?

I think we shouldn't deprecate it (or other things like `puppet config set external_nodes <...> --section master`) because of the noise factor. At some point in the future we can deprecate (probably 7.x) and remove in 8.

> ext/suse/server.init, ext/debian/puppetmaster.init

I believe those scripts are left over from the ruby puppet master (webrick & passenger) and can be removed. I'd be fine filing a separate ticket to clean up that directory.

**Comment by joshcooper** [comment]
jenkins please test this with servertests

**Comment by GabrielNagy** [comment]
Filed PUP-10685 for cleaning up the `ext/` directory.

**Review by joshcooper — APPROVED** [review]

**Pull request merged**
