### PR TITLE
(PUP-8762) deprecate `puppet module build` in favor of the PDK

### PR DESCRIPTION
**Pull request by DavidS**

### CODE REVIEW

**Comment by joshcooper** [comment]
jenkins please test this

**Comment by DavidS** [comment]
jenkins please test this

**Comment by DavidS** [comment]
Updated `build_basic` test to not fail on deprecation warning. There is also a spurious fail of a missing mco link, for which I do not feel responsible:

```
  Test Case tests/ensure_puppet-agent_paths.rb reported: #<Beaker::DSL::Outcomes::FailTest: 
 Failed to find expected symbolic link '/opt/puppetlabs/bin/mco' on agent 'lxbojbcri23opzf.delivery.puppetlabs.net'
 >
     Test line: tests/ensure_puppet-agent_paths.rb:176:in `block (3 levels) in run_test'
```

**Comment by DavidS** [comment]
I've got a fix for the ruby warnings failure queued up locally, but I don't want to disturb the jenkins run.

**Comment by joshcooper** [comment]
There's a bug in ci configuration that tries to merge your puppet change into puppet-agent#master, but run the acceptance tests from this branch based off of 5.5.x. I would fix the ruby warning, and rekick this with "jenkins please test this with agent 5.5.x"

**Comment by DavidS** [comment]
jenkins please test this with agent 5.5.x

**Pull request merged**
