### PR TITLE
(docs)(PUP-8292) Fix Markdown in 'unique'.

### PR DESCRIPTION
**Pull request by gguillotte**
- Correctly uses three code fence symbols instead of two on L73, fixing the code block.
- Updates code fences to use backticks.

### CODE REVIEW

**Comment by hlindberg** [comment]
Earlier we were told to prefer the use of three tildes syntax over backticks in documentation. Has that changed?
Change is fine otherwise.

**Comment by gguillotte** [comment]
@hlindberg Prior to 2016, the docs site couldn't handle backtick-fenced code blocks. That changed in January 2016 per Nick Fagerlund when we adopted the GitHub-Flavored Markdown parser in Kramdown, where he stated that backtick fences should be preferred.

GitHub itself has formally preferred backticks for all code strings and spans, and primarily uses backticks for code fences, since adopting the [GFM spec](https://github.github.com/gfm/#code-spans) in March 2017.

Tilde-fenced code spans still work in both GitHub and the docs site, but the GFM spec formally added strikethrough as a function of tildes, while backticks always represent code.

**Comment by joshcooper** [comment]
It looks like a number of the other 3 and 4 functions use `~~~`. Should they be modified too?

**Comment by gguillotte** [comment]
@joshcooper Yes, but it's not necessary, and to reduce confusion I'll just resubmit with the tilde fix instead.

**Pull request closed without merging**
