### PR TITLE
(PUP-8878) Remove scheduled_task from puppet

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by melissa** [comment]
jenkins please test this on windows2012r2-64

**Comment by melissa** [comment]
screen shot 2018-07-20 at 2 30 25 pm

**Comment by melissa** [comment]
This probably shouldn't be merged until https://github.com/puppetlabs/puppet-agent/pull/1492 goes in

**Comment by melissa** [comment]
I'd still love to get sign off from someone from the windows team on this PR

**Comment by joshcooper** [comment]
need to remove:

```
lib/puppet/pops/loader/static_loader.rb:      Scheduled_task
spec/unit/pops/loaders/static_loader_spec.rb:      Scheduled_task
```

**Comment by melissa** [comment]
🤦‍♂️ thanks for catching that @joshcooper. I also pulled out selmodule and selboolean, it looks like I forgot those when I was extracting selinux.

**Comment by melissa** [comment]
Got AppVeyor to pass!

**Comment by melissa** [comment]
@Iristyle @glennsarti would either of you have time to chime on on this?

**Comment by Iristyle** [comment]
The files we started with for the module are at https://github.com/puppetlabs/puppetlabs-scheduled_task/tree/f6ffc726ec9910d532d751dd89f1758c2ff5e3cb:

* acceptance/tests/resource/scheduled_task/should_create.rb
* acceptance/tests/resource/scheduled_task/should_destroy.rb
* acceptance/tests/resource/scheduled_task/should_modify.rb
* acceptance/tests/resource/scheduled_task/should_query.rb
* lib/puppet/provider/scheduled_task/win32_taskscheduler.rb
* lib/puppet/type/scheduled_task.rb
* lib/puppet/util/windows/taskscheduler.rb
* spec/unit/provider/scheduled_task/win32_taskscheduler_spec.rb
* spec/unit/type/scheduled_task_spec.rb

By 0.1 we had removed / replaced the acceptance tests, and the `win32_taskscheduler.rb` provider was removed along with `type/scheduled_task.rb`, `util/windows/taskscheduler.rb` and `spec/unit/type/scheduled_task_spec.rb`. 

Once we better understood the interaction between Puppet and a module with duplicate types / definitions, we were able to restore `type/scheduled_task.rb` (with its test `spec/unit/puppet/type/scheduled_task_spec.rb` and restore / evolve `win32_taskscheduler.rb` as well (for the sake of removing its default status).

The only file that we've been relying on being in Puppet still is `lib/puppet/util/windows/taskscheduler.rb` as this is general purpose utility code that does the heavy lifting of interacting with the V1 COM APIs. In reality, we *only* use it now in tests that compare behavior between old / new APIs at these two locations:

https://github.com/puppetlabs/puppetlabs-scheduled_task/blob/e826a634faeeead2d1bfcb9af6449ef9520f60ac/spec/integration/puppet_x/puppetlabs/scheduled_task/v1adapter_spec.rb#L4

https://github.com/puppetlabs/puppetlabs-scheduled_task/blob/e826a634faeeead2d1bfcb9af6449ef9520f60ac/spec/unit/puppet/provider/scheduled_task/win32_taskscheduler_spec.rb#L4

The thinking was that we didn't want to drag in code that would redefine code already present in Puppet, etc. So we'll have to address that in the module to keep our tests passing /cc @glennsarti @michaeltlombardi 

This is a long-winded way of saying this PR looks good to me, and that we have one minor thing to do in the module code as a result.

**Comment by melissa** [comment]
jenkins please test this on windows2012r2-64

**Comment by jtappa** [comment]
jenkins please test this on windows2012r2-64

**Comment by jtappa** [comment]
Looks like acceptance tests were failing last week because there weren't any available jenkins' builds, so kicking again.

**Comment by Iristyle** [comment]
PR to add code back to scheduled tasks module is at https://github.com/puppetlabs/puppetlabs-scheduled_task/pull/55

**Pull request merged**
