### PR TITLE
(PUP-8495) Systemd support, Ubuntu 17.04 and 17.10

### PR DESCRIPTION
**Pull request by kbarmen**
This is a trivial patch that adds support for Ubuntu 17.04 and 17.10.

### CODE REVIEW

**Comment by kbarmen** [comment]
This is very trivial, no CLA needed.

**Comment by melissa** [comment]
Hi! I apologize this is taking so long on my end. I'm waiting on some resources from IT before I can move forward with this, but hopefully I'll have what I need before too long.

**Comment by michaeljs1990** [comment]
Can we add 18.04 as well since that will also need this?

**Comment by kbarmen** [comment]
Indeed - a more permanent and correct solution is to make systemd default for both Debian and Ubuntu, and leave the old behaviour for just the legacy releases.

**Comment by michaeljs1990** [comment]
Yeah if versioning allows something like ">= 15.04" that would be awesome but I think would make this diff a bit more work.

**Comment by jkroepke** [comment]
@kbarmen Can you add 18.04, too?

**Comment by melissa** [comment]
You're welcome to add 18.04 if you like, or we can open a new PR for it. Please note that because we are adding these OS's here does not mean we will be creating packages for them. That is handled by a seperate set of automation. You can see tickets for 17.04 at https://tickets.puppetlabs.com/browse/PA-873 (it looks like that's not happening at all), and 18.04 at https://tickets.puppetlabs.com/browse/PA-1869. I couldn't find anything for 17.10.

**Comment by jkroepke** [comment]
@melissa For the moment Debian 9 packages are working fine for Ubuntu 18.04

**Comment by melissa** [comment]
Also, unfortunately the `defaultfor` mechanism requires an array of values. I haven't dug into it too much, but there are no existing examples where we defined something like `>= 15.05`. I agree it would be very nice to be able to do that.

**Pull request merged**
