### PR TITLE
(PUP-8470) Unable to modify groups or users when forcelocal is true

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by ericldelaney** [comment]
jenkins please test this

**Comment by melissa** [comment]
I still need to add tests to this

**Comment by ericldelaney** [comment]
@melissa I figured as much but I wanted a build to play with on a linux box

**Comment by jhelwig** [comment]
@melissa Re-target at master since there are no planned 5.4.x releases?

**Comment by melissa** [comment]
I've retargeted this to the master branch

**Pull request merged**
