### PR TITLE
Merge 4.10.x -> 5.3.x

### PR DESCRIPTION
**Pull request by Magisus**

### CODE REVIEW

**Comment by Magisus** [comment]
jenkins please test this

**Comment by branan** [comment]
The failures in this are weird - shouldn't `puppet master` still work in 5.3.x?

**Comment by Magisus** [comment]
I certainly thought so.

**Comment by Magisus** [comment]
The tests on the 5.5.x mergeup PR passed.

**Comment by branan** [comment]
jenkins please test this

**Comment by branan** [comment]
let's just try it again and see if it was a fluke

**Comment by joshcooper** [comment]
ah so I think it's coming from the beaker helpers that implement `with_puppet_running_on`. We likely didn't bump the beaker-puppet versions in these older branches.

**Comment by Magisus** [comment]
So is there something we can actually do to fix these failures? Sorry, little confused by Josh's comment... this PR does bump beaker-puppet, but I'm assuming you mean something different.

**Comment by joshcooper** [comment]
jenkins please test this with agent 5.3.x

**Comment by joshcooper** [comment]
I'm not entirely sure what's up. It seems like we're running the acceptance tests from 5.3.x against a puppet-agent package containing puppet#master code...

**Comment by joshcooper** [comment]
```
15:55:16 * verify help displays something for puppet master
15:55:16 
15:55:16 tfmucns6lqinv1m.delivery.puppetlabs.net (tfmucns6lqinv1m.delivery.puppetlabs.net) 22:55:16$ puppet master --help
15:55:16   Error: Unknown Puppet subcommand 'master'
```

The test exists in 5.3.x but the package that was installed is based off of master...

**Comment by justinstoller** [comment]
From what I understand talking to folks the PR testing is broken against this target branch (ie it won't test Puppet 5.3.x and so is incorrectly installing Puppet's master branch). If that's correct I should be able to verify this merge up with a manual run, correct? I'm currently running:
```
be rake ci:test:aio SHA=5.3.7 SUITE_VERSION=5.3.8 TEST_TARGET=redhat7-64a
```
locally and will report back on the outcome.

**Comment by justinstoller** [comment]
This failed locally for me with the same issue in PR testing. This seems to be the culprit:
```
Install Puppet Server
  lmtbnm0kmmnrh1n.delivery.puppetlabs.net (lmtbnm0kmmnrh1n.delivery.puppetlabs.net) 09:09:11$ rpm --replacepkgs -Uvh http://nightlies.puppet.com/yum/puppet-nightly/puppet-nightly-release-el-7.noarch.rpm
    warning: /var/tmp/rpm-tmp.hBI20o: Header V4 RSA/SHA512 Signature, key ID ef8d349f: NOKEY
    Retrieving http://nightlies.puppet.com/yum/puppet-nightly/puppet-nightly-release-el-7.noarch.rpm
    Preparing...                              ########################################
    Updating / installing...
    puppet-nightly-release-1.0.0-2.el7        ########################################


....snip.....


  lmtbnm0kmmnrh1n.delivery.puppetlabs.net (lmtbnm0kmmnrh1n.delivery.puppetlabs.net) 09:09:13$ yum -y  install puppetserver
    Loaded plugins: product-id, search-disabled-repos, subscription-manager
    This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
    Resolving Dependencies
    --> Running transaction check
    ---> Package puppetserver.noarch 0:6.0.0.master-0.1SNAPSHOT.2018.08.19T2214.el7 will be installed
    --> Processing Dependency: puppet-agent >= 5.5.0 for package: puppetserver-6.0.0.master-0.1SNAPSHOT.2018.08.19T2214.el7.noarch
    --> Processing Dependency: java-1.8.0-openjdk-headless for package: puppetserver-6.0.0.master-0.1SNAPSHOT.2018.08.19T2214.el7.noarch
    --> Running transaction check
    ---> Package java-1.8.0-openjdk-headless.x86_64 1:1.8.0.171-8.b10.el7_5 will be installed
    --> Processing Dependency: tzdata-java >= 2015d for package: 1:java-1.8.0-openjdk-headless-1.8.0.171-8.b10.el7_5.x86_64
    --> Processing Dependency: nss-softokn(x86-64) >= 3.36.0 for package: 1:java-1.8.0-openjdk-headless-1.8.0.171-8.b10.el7_5.x86_64
    --> Processing Dependency: nss(x86-64) >= 3.36.0 for package: 1:java-1.8.0-openjdk-headless-1.8.0.171-8.b10.el7_5.x86_64
    --> Processing Dependency: copy-jdk-configs >= 2.2 for package: 1:java-1.8.0-openjdk-headless-1.8.0.171-8.b10.el7_5.x86_64
    --> Processing Dependency: chkconfig >= 1.7 for package: 1:java-1.8.0-openjdk-headless-1.8.0.171-8.b10.el7_5.x86_64
    --> Processing Dependency: chkconfig >= 1.7 for package: 1:java-1.8.0-openjdk-headless-1.8.0.171-8.b10.el7_5.x86_64
    --> Processing Dependency: lksctp-tools(x86-64) for package: 1:java-1.8.0-openjdk-headless-1.8.0.171-8.b10.el7_5.x86_64
    --> Processing Dependency: libjpeg.so.62(LIBJPEG_6.2)(64bit) for package: 1:java-1.8.0-openjdk-headless-1.8.0.171-8.b10.el7_5.x86_64
    --> Processing Dependency: jpackage-utils for package: 1:java-1.8.0-openjdk-headless-1.8.0.171-8.b10.el7_5.x86_64
    --> Processing Dependency: libjpeg.so.62()(64bit) for package: 1:java-1.8.0-openjdk-headless-1.8.0.171-8.b10.el7_5.x86_64
    ---> Package puppet-agent.x86_64 0:5.3.7-1.el7 will be updated
    ---> Package puppet-agent.x86_64 0:5.99.2.231.gf095aac-1.el7 will be an update
```

**Comment by joshcooper** [comment]
Ah, that makes sense @justinstoller. The 5.x pipelines set a `SERVER_VERSION` environment variable (I believe based on the last passing version for puppetserver). For example, in 5.5.x we set: `SERVER_VERSION=5.3.6.SNAPSHOT.2018.09.04T2050`. Ideally PR testing would do the same?

**Comment by joshcooper** [comment]
Changes to 4.10.x reverted in cb6a4c50a4, and merged up to 5.3.x in fd4efa3d9c, and 5.5.x in 6cec8e0459. Closing this PR.

**Pull request closed without merging**
