### PR TITLE
(PUP-10853) Remove usage of legacy facts

### PR DESCRIPTION
**Pull request by GabrielNagy**
This PR aims to replace all usage of legacy facts with structured facts. The minimum Facter dependency also has to be bumped since Facter 2 does not have structured facts.

### CODE REVIEW

**Comment by luchihoratiu** [comment]
Jenkins, please test this

**Comment by luchihoratiu** [comment]
jenkins please test this

**Comment by luchihoratiu** [comment]
jenkins please test this

**Comment by GabrielNagy** [comment]
jenkins please test this on all

**Comment by GabrielNagy** [comment]
jenkins please test this on all

**Comment by gimmyxd** [comment]
jenkins please test this on all

**Review by gimmyxd — APPROVED** [review]

**Pull request merged**
