### PR TITLE
(PUP-6513) Log lookup explainer info at debug level

### PR DESCRIPTION
**Pull request by thallgren**
This PR ensures that a lookup explainer is present when
`Puppet[:debug]` is `true` and that the information that it collects
is logged. For cases when `Puppet[:debug]` is `true` and an explainer is
present already (as when using the lookup command with --explain or
--explain-options), then the information from that explainer is mirrored
to the debug logger.

### CODE REVIEW

**Comment by hlindberg** [comment]
What happens if the CLI `lookup` is used with `--explain` and `--debug` at the same time?

**Comment by thallgren** [comment]
Then the info from the explainer is mirrored to the debug logger.

**Comment by hlindberg** [comment]
Want tests that shows: "Does not log explanation when log level is < 'debug'" as a guard against future regressions.

**Comment by hlindberg** [comment]
Good to merge when travis goes green.

**Pull request merged**
