### PR TITLE
(PUP-3908) Tidy type is too verbose when working of directories containing lot of files

### PR DESCRIPTION
**Pull request by amuraru**

### CODE REVIEW

**Comment by ScottGarman** [comment]
@amuraru Thanks for this contribution. Can you update the commit message to reflect the ticket number, e.g:

(PUP-3908) Tidy type is too verbose for directories with a lot of files

**Comment by peiriannydd** [comment]
Could this be updated to output the number of files Tidied at 'notice' and additionally each file Tidied in 'debug'?

I would like to know some level of what happened on my system.

**Comment by ScottGarman** [comment]
PR Triage notes: @amuraru could you make the requsted changes (including @peiriannydd's suggestion)?

**Comment by ScottGarman** [comment]
@amuraru We'd like to accept this PR once the changes have been made, but please be aware that we won't be able to accept it until after Puppet 4.0.0 is released.

**Comment by kylog** [comment]
I like @peiriannydd's suggestion, so we don't lose all notices about tidy.

Also, a nit: the commit message should be in the imperative e.g. "(PUP-3908) Make tidy type less verbose".

@amuraru thoughts on the above?

**Comment by ffrank** [comment]
+1 on @peiriannydd 's request for a brief notice, if only for reporting purposes.

**Comment by kylog** [comment]
@amuraru have you had a chance to address the above conerns? It's fine if you haven't, but what we'll do is close it at our next triage a week from now if we haven't heard back. Of course, you can reopen the PR at any time, so that doesn't mean we don't value the contribution. Thanks!!

**Comment by branan** [comment]
Closing in favor of #3693

**Pull request closed without merging**
