### PR TITLE
(maint) Only ci:test:quick ruby files

### PR DESCRIPTION
**Pull request by joshcooper**
Previously, the quick task was trying to run `.sh` files as beaker tests
which were recently modified.

This commit ensures we only try to run files ending in `.rb`. If those
are not beaker tests then they need to be in a different directory
other than `tests`.

Depends on https://github.com/puppetlabs/puppet/pull/5743.

### CODE REVIEW

**Comment by joshcooper** [comment]
I need to test this after the other PR is merged up to master.

/cc @puppetlabs/agent-team

**Comment by joshcooper** [comment]
Rebased, and verified it's capturing the expected set of ruby test files:

```
  "tests": [
        "tests/direct_puppet/cached_catalog_remediate_local_drift.rb",
        "tests/environment/environment_scenario-default.rb",
        "tests/face/loadable_from_modules.rb",
        "tests/language/functions_in_puppet_language.rb",
        "tests/lookup/merge_strategies.rb",
        "tests/modules/install/basic_install.rb",
        "tests/node/check_woy_cache_works.rb",
        "tests/parser_functions/calling_all_functions.rb",
        "tests/parser_functions/puppet_lookup_cmd.rb",
        "tests/pluginsync/4420_pluginfacts_should_be_resolvable_on_agent.rb",
        "tests/puppet_apply_basics.rb",
        "tests/resource/cron/should_match_existing.rb",
        "tests/resource/cron/should_remove_cron.rb",
        "tests/resource/cron/should_remove_matching.rb",
        "tests/resource/cron/should_update_existing.rb",
        "tests/resource/file/content_attribute.rb",
        "tests/resource/file/should_create_directory.rb",
        "tests/resource/file/should_create_empty.rb",
        "tests/resource/file/should_create_symlink.rb",
        "tests/resource/file/should_remove_dir.rb",
        "tests/resource/file/should_remove_file.rb",
        "tests/resource/group/should_create.rb",
        "tests/resource/group/should_destroy.rb",
        "tests/resource/group/should_modify_gid.rb",
        "tests/resource/group/should_not_create_existing.rb",
        "tests/resource/group/should_not_destoy_unexisting.rb",
        "tests/resource/group/should_query.rb",
        "tests/resource/group/should_query_all.rb",
        "tests/resource/host/pup_2289_should_not_destroy_data_when_malformed.rb",
        "tests/resource/host/should_create.rb",
        "tests/resource/host/should_create_aliases.rb",
        "tests/resource/host/should_destroy.rb",
        "tests/resource/host/should_modify_alias.rb",
        "tests/resource/host/should_modify_ip.rb",
        "tests/resource/host/should_not_create_existing.rb",
        "tests/resource/host/should_query_all.rb",
        "tests/resource/host/ticket_4131_should_not_create_without_ip.rb",
        "tests/resource/package/yum.rb",
        "tests/resource/service/AIX_service_provider.rb",
        "tests/resource/service/puppet_mcollective_service_management.rb",
        "tests/resource/service/ticket_4123_should_list_all_running_redhat.rb",
        "tests/resource/service/ticket_4124_should_list_all_disabled.rb",
        "tests/resource/service/ticket_5024_systemd_enabling_masked_service.rb",
        "tests/resource/sshkey/create.rb",
        "tests/resource/user/should_create.rb",
        "tests/resource/user/should_create_with_gid.rb",
        "tests/resource/user/should_destroy.rb",
        "tests/resource/user/should_manage_shell.rb",
        "tests/resource/user/should_modify_gid.rb",
        "tests/resource/user/should_not_create_existing.rb",
        "tests/resource/user/should_not_destoy_unexisting.rb",
        "tests/resource/user/should_query.rb",
        "tests/resource/user/should_query_all.rb",
        "tests/resource/zone/dataset.rb",
        "tests/resource/zone/set_ip.rb",
        "tests/resource/zone/should_be_created_and_removed.rb",
        "tests/resource/zone/should_be_idempotent.rb",
        "tests/ssl/puppet_cert_generate_and_autosign.rb",
        "tests/ticket_4622_filebucket_diff_test.rb",
        "tests/utf8/utf8-in-puppet-describe.rb"
  ],
```

**Comment by MosesMendoza** [comment]
@joshcooper dependent PR https://github.com/puppetlabs/puppet/pull/5743 went into stable - should this go there too?

**Comment by joshcooper** [comment]
I should retarget this for stable, so we don't have the same problem on those branches

**Comment by joshcooper** [comment]
Let me create a new PR. Originally I targeted master because that's where the failure showed up (due to .sh changing permissions)

**Pull request closed without merging**
