### PR TITLE
Make cache and values fully thread-safe

### PR DESCRIPTION
**Pull request by mensfeld**
Not locking the default initialization can lead to race-conditions.

Note: not sure if I should use one or two mutexes as I am not familiar with this code enough to make the judgment.

ref: https://github.com/ruby-concurrency/concurrent-ruby/issues/970

### CODE REVIEW

**Review by joshcooper — CHANGES_REQUESTED** [review]
@mensfeld thanks for letting us know! Is the recommended pattern now to use `compute_if_absent`?

```ruby
@cache = Concurrent::Hash.new do |hash, key|
  hash.compute_if_absent(key) { Concurrent::Hash.new }
end
```

**Comment by mensfeld** [comment]
@joshcooper if you want it to be thread-safe yes.

**Comment by joshcooper** [comment]
@mensfeld could you update your PR to call `compute_if_absent` instead of creating a mutex?

**Comment by mensfeld** [comment]
@joshcooper not really. This PR is one year old. Feel free to close and apply the PR alongside other changes or ignore. Sorry but I no longer have puppet setup on my machine :pray:

**Comment by joshcooper** [comment]
I added a new PR and added you as an author. Thanks for your help!

**Pull request closed without merging**
