### PR TITLE
(PUP-10393) Fix ruby 2.7 warning

### PR DESCRIPTION
**Pull request by lucaskanashiro**

### CODE REVIEW

**Comment by lucaskanashiro** [comment]
This is a trivial change but the [url pointed by the bot](http://docs.puppet.com/community/trivial_patch_exemption.html) is not working for me.

**Comment by GabrielNagy** [comment]
Hi @lucaskanashiro, thanks for your contribution!

Looks like the ticket you opened refers to puppet 5 as well. To get this change in the puppet5 stream as well, you'd have to retarget this pull request to the 5.5.x branch. After it gets merged, the changes will be promoted automatically to master when nightly CI passes.

**Comment by GabrielNagy** [comment]
Hi @lucaskanashiro, thanks for your contribution!

Looks like the ticket you opened refers to puppet 5 as well. We generally don't backport support for new ruby versions to older puppet branches, so this will only get into master (puppet 6 and higher).

**Comment by lucaskanashiro** [comment]
> Looks like the ticket you opened refers to puppet 5 as well. We generally don't backport support for new ruby versions to older puppet branches, so this will only get into master (puppet 6 and higher).

OK. Is it missing something to get it merged into master?

**Comment by GabrielNagy** [comment]
We're tracking Ruby 2.7 support on https://tickets.puppetlabs.com/browse/PUP-10247. This deprecation warning shows up in more places, along with other warnings, but it's fine to merge as is.

Thanks for the contribution!

**Pull request merged**
