### PR TITLE
(PUP-9994) Trusted external facts

### PR DESCRIPTION
**Pull request by joshcooper**
Supersedes PR https://github.com/puppetlabs/puppet/pull/7813

### CODE REVIEW

**Comment by joshcooper** [comment]
jenkins please test this on redhat7-64a,windows2019-64a

**Comment by joshcooper** [comment]
When `trusted_external_command` is enabled:

```
[root@soapy-mercury ~]# puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Caching catalog for soapy-mercury.delivery.puppetlabs.net
Info: Applying configuration version '1573445555'
Notice: {"authenticated"=>"remote", "certname"=>"soapy-mercury.delivery.puppetlabs.net", "extensions"=>{}, "hostname"=>"soapy-mercury", "domain"=>"delivery.puppetlabs.net", "external"=>{"doot"=>"soapy-mercury.delivery.puppetlabs.net"}}
Notice: /Stage[main]/Main/Notify[hi]/message: defined 'message' as {
  'authenticated' => 'remote',
  'certname' => 'soapy-mercury.delivery.puppetlabs.net',
  'extensions' => {

  },
  'hostname' => 'soapy-mercury',
  'domain' => 'delivery.puppetlabs.net',
  'external' => {
    'doot' => 'soapy-mercury.delivery.puppetlabs.net'
  }
}
```

When `trusted_external_command` is disabled (default). Note `external` is an empty hash like `extensions` instead of undef:

```
[root@soapy-mercury ~]# puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Caching catalog for soapy-mercury.delivery.puppetlabs.net
Info: Applying configuration version '1573445676'
Notice: {"authenticated"=>"remote", "certname"=>"soapy-mercury.delivery.puppetlabs.net", "extensions"=>{}, "hostname"=>"soapy-mercury", "domain"=>"delivery.puppetlabs.net", "external"=>{}}
Notice: /Stage[main]/Main/Notify[hi]/message: defined 'message' as {
  'authenticated' => 'remote',
  'certname' => 'soapy-mercury.delivery.puppetlabs.net',
  'extensions' => {

  },
  'hostname' => 'soapy-mercury',
  'domain' => 'delivery.puppetlabs.net',
  'external' => {

  }
}
```

**Comment by joshcooper** [comment]
jenkins please test this on redhat7-64a,windows2019-64a with servertests

**Comment by joshcooper** [comment]
Need to update a different test that isn't expecting the new key

```
00:52:08   Test Case tests/ssl/certificate_extensions.rb reported: #<Beaker::DSL::Outcomes::FailTest: 
00:52:08 --- expected
00:52:08 +++ actual
00:52:08 @@ -1 +1 @@
00:52:08 -{"authenticated"=>"remote", "certname"=>"wooden-weave.delivery.puppetlabs.net-extensions", "extensions"=>{"pp_uuid"=>"b5e63090-5167-11e3-8f96-0800200c9a66", "pp_instance_id"=>"i-3fkva", "1.3.6.1.4.1.34380.1.2.1"=>"db-server", "1.3.6.1.4.1.34380.1.2.2"=>"webops"}, "hostname"=>"wooden-weave", "domain"=>"delivery.puppetlabs.net-extensions"}
00:52:08 +{"authenticated"=>"remote", "certname"=>"wooden-weave.delivery.puppetlabs.net-extensions", "extensions"=>{"pp_uuid"=>"b5e63090-5167-11e3-8f96-0800200c9a66", "pp_instance_id"=>"i-3fkva", "1.3.6.1.4.1.34380.1.2.1"=>"db-server", "1.3.6.1.4.1.34380.1.2.2"=>"webops"}, "hostname"=>"wooden-weave", "domain"=>"delivery.puppetlabs.net-extensions", "external"=>{}}
```

**Comment by joshcooper** [comment]
jenkins please test this on redhat7-64a,windows2019-64a with servertests

**Comment by gimmyxd** [comment]
jenkins please test this on redhat7-64a,windows2019-64a with servertests

**Pull request merged**
