### PR TITLE
(maint) change noop_pending in transaction/report.rb to attr_accessor

### PR DESCRIPTION
**Pull request by wkalt**
This will make it easier to spec test from PuppetDB.

### CODE REVIEW

**Comment by branan** [comment]
`noop_pending` is intended to be used/accessed the same way as `status` - it's computed in `finalize` based on the individual resources status information. It shouldn't be any harder to test than `status` which is also an `attr_reader`. I'm not sure why it needs to be directly settable when `status` doesn't.

**Comment by wkalt** [comment]
@branan having it settable directly lets us to test our logic around handling versions of puppet where the parameter is and is not defined. We don't have this issue with status since status is present in all versions we support.

**Comment by wkalt** [comment]
@branan bump

**Comment by branan** [comment]
This PR definitely breaks encapsulation, but the "correct" API of adding events to the report and finalizing it is a lot of complexity to PuppetDB's tests, for very little safety gain in any real-world use of the report API. I'm going to go ahead and merge this.

**Pull request merged**
