### PR TITLE
(PUP-11667) document version range support for apt, yum and dnf

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by joshcooper** [comment]
Thanks for your PR @evgeni Can you provide steps to show how this change corrects the documentation?

**Comment by evgeni** [comment]
The rendered docs for the package type (eg https://www.puppet.com/docs/puppet/7/types/package.html) should list apt, dnf and yum with `version_ranges` in the "Supported features" list.

**Comment by joshcooper** [comment]
The diff of `puppet doc -r type` before and after looks correct:

```
1734c1734
< apt              |             | *X*      |              | *X*             | *X*         |                  | *X*       |               |                  |            |                   | *X*           | *X*         |                | *X*         | *X*              |
---
> apt              |             | *X*      |              | *X*             | *X*         |                  | *X*       |               |                  |            |                   | *X*           | *X*         | *X*            | *X*         | *X*              |
1738c1738
< dnf              |             |          | *X*          | *X*             | *X*         |                  | *X*       |               |                  |            |                   | *X*           | *X*         |                | *X*         | *X*              |
---
> dnf              |             |          | *X*          | *X*             | *X*         |                  | *X*       |               |                  |            |                   | *X*           | *X*         | *X*            | *X*         | *X*              |
1771c1771
< yum              |             |          | *X*          | *X*             | *X*         |                  | *X*       |               |                  |            |                   | *X*           | *X*         |                | *X*         | *X*              |
---
> yum              |             |          | *X*          | *X*             | *X*         |                  | *X*       |               |                  |            |                   | *X*           | *X*         | *X*            | *X*         | *X*              |
2038c2038
<     * Supported features: `holdable`, `install_options`, `installable`, `purgeable`, `uninstallable`, `upgradeable`, `versionable`, `virtual_packages`.
---
>     * Supported features: `holdable`, `install_options`, `installable`, `purgeable`, `uninstallable`, `upgradeable`, `version_ranges`, `versionable`, `virtual_packages`.
2071c2071
<     * Supported features: `install_only`, `install_options`, `installable`, `purgeable`, `uninstallable`, `upgradeable`, `versionable`, `virtual_packages`.
---
>     * Supported features: `install_only`, `install_options`, `installable`, `purgeable`, `uninstallable`, `upgradeable`, `version_ranges`, `versionable`, `virtual_packages`.
2400c2400
<     * Supported features: `install_only`, `install_options`, `installable`, `purgeable`, `uninstallable`, `upgradeable`, `versionable`, `virtual_packages`.
---
>     * Supported features: `install_only`, `install_options`, `installable`, `purgeable`, `uninstallable`, `upgradeable`, `version_ranges`, `versionable`, `virtual_packages`.
```

@evgeni Could you rebase your commit on 7.x?

**Comment by evgeni** [comment]
@joshcooper done

**Comment by joshcooper** [comment]
GH is confused about which checks to run. Closing and reopening to retrigger with the correct list.

**Review by joshcooper — APPROVED** [review]
Thanks @evgeni!

**Pull request merged**
