### PR TITLE
Avoid downcasing facts in service provider

### PR DESCRIPTION
**Pull request by ekohl**
If the os.name or os.family fact is missing this will result in nil.downcase. In practice that's unlikely, but in some test scenarios it can happen. By using the properly cased values it removes the need to downcase, which is also slightly faster.

### CODE REVIEW

**Review by bastelfreak — APPROVED** [review]

**Review by ekohl — COMMENTED** [review]
I started to realize how I hit this. In testing we configure a different Facter runtime with dummy facts. Then `os.name` doesn't return in some cases. What probably happens is that the facts are only evaluated once (when loading the type).

`Puppet::Confine::Variable` does have a reset so it can clear the cached value so what you really want is something like `confine_not 'os.name' => [:debian, :ubuntu]`. But AFAIK there's no opposite of confine.

**Comment by bastelfreak** [comment]
hey @ekohl, the issue was magically fixed in https://github.com/voxpupuli/puppet-keepalived/pull/293. I rebased the PR and the tests pass now. I saw other modules recently with the same error, but I cannot find those anymore... Do you remember where it happened?

**Comment by ekohl** [comment]
I've seen it locally when some facts weren't present. I also just saw it in https://github.com/theforeman/puppet-qpid/pull/187 and can't quite explain it. My theory is that the provider is loaded before the facts are overridden in CI and then the provider is determined. Perhaps a proper solution is to use a callable so it resolves at the correct time. That appears to be supported.

**Comment by joshcooper** [comment]
Retriggering checks

**Review by joshcooper — COMMENTED** [review]
LGTM, after this PR is merged https://github.com/puppetlabs/puppet/pull/9146 can you rebase and retarget 7.x?

**Comment by ekohl** [comment]
The 7.x branch has conflicts: there it uses the legacy facts by default. I've created  https://github.com/puppetlabs/puppet/pull/9082 as a new PR instead of retargetting this PR.

**Review by joshcooper — APPROVED** [review]

**Pull request merged**
