### PR TITLE
(PUP-6756) Puppet::FileBucket::Dipper specs fail silently

### PR DESCRIPTION
**Pull request by shawnferry**
dipper_spec assumes gnu diff AND executes diff via ``s
notably this fails on Solaris but may also fail on other platforms.

On Solaris 11+ dipper_spec now invokes 'gdiff' and on all platforms
uses Puppet::Util::Execution.execute which causes the test to fail
if diff cannot be executed.

### CODE REVIEW

**Comment by whopper** [comment]
Thanks for the contribution @shawnferry! Would you mind squashing your commits together just to keep the git history clean for this fix?

**Comment by shawnferry** [comment]
@whopper all set

**Comment by joshcooper** [comment]
Thanks for your contribution @shawnferry. I think your changes improve the current test and I'm happy to merge as is. I did have a couple of ideas for improvements, either in this ticket or a different one if you're up for it:

1. We try to avoid executing commands in unit tests, so I'd recommend stubbing out the execute calls in the dipper unit test, e.g. `Puppet::Util::Execution.stubs(:execute).with(regexp_matches(/#{file1} #{file2}/).returns("some expected diff output")`.
1. It sounds like puppet's default `diff` and `diff_args` settings should be different for Solaris 11 and up? For example, on AIX we use different [`diff_args`](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/defaults.rb#L3-L8). And on Windows, we change the default diff command to empty string since there isn't a [suitable command installed by default](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/defaults.rb#L367).
1. If we change the defaults for Solaris, it would be a good idea to add an integration test for `Puppet::Util::Diff` to ensure it when it executes the diff command and args, it returns the expected output on different platforms.

**Comment by shawnferry** [comment]
@joshcooper I'd happily replace that execution with the expected output. It was my first inclination but I didn't understand why the test was explicitly using `diff` and munging the output so I just cleaned up the behavior. 

The test in question has never been valid for Solaris it was just failing silently (dumping noise to stderr) because the invocation error wasn't being caught. 

Using the stock/default diff seems to be fine it was just the inline execution in the test assumed gnu diff options and I didn't spend enough time digging to see that it's just executing diff under the covers.

**Comment by shawnferry** [comment]
@joshcooper looking further into this the vast majority of the tests are doing a mess of integration style testing. Just stubbing out the return here isn't going to be enough and I can't currently commit to refactoring it all out into integration tests at the moment. 

I created https://tickets.puppetlabs.com/browse/PUP-6769 for the remaining work.

**Comment by ScottGarman** [comment]
:+1:

**Pull request merged**
