### PR TITLE
(maint) Merge 6.x to main (ca2d869)

### PR DESCRIPTION
**Pull request by joshcooper**

### CODE REVIEW

**Comment by joshcooper** [comment]
jenkins please test this with servertests

**Comment by joshcooper** [comment]
looks to be a valid failure because we're skipping the node request, and the first failure occurs during pluginsync:

```
    puppet_agent: *UNEXPECTED FAILURE*
    -------------------------------------------------------------------------------
    Expected the output:
    Info: Retrieving pluginfacts
    Error: /File[/opt/puppetlabs/puppet/cache/facts.d]: Could not evaluate: Could not retrieve information from environment testing source(s) puppet:///pluginfacts
    Error: Failed to apply catalog: Failed to retrieve pluginfacts: Could not retrieve information from environment testing source(s) puppet:///pluginfacts
    
    To match: (?-mix:(Warning|Error).*(404|400).*Could not find environment 'testing')
```

Need to figure out why it didn't fail in 6.x

**Comment by GabrielNagy** [comment]
I can take a look at this today, at a first glance it seems that the 404 on the catalog request does not show up. 

This is from a good run:
```
Error: Could not retrieve catalog from remote server: Find /puppet/v3/catalog/mythic-teasing.delivery.puppetlabs.net resulted in 404 with the message: {"message":"Not Found: Could not find environment 'testing'","issue_kind":"RUNTIME_ERROR"}
```

**Comment by GabrielNagy** [comment]
So there are 2 things:
1. between 6.x and main the value of `ignore_plugin_errors` changed from `true` to `false` which causes the run to fail fast just after the pluginsync (we don't get to the catalog request):
```sh-session
> puppet agent -t (main - after #8691)
Info: Retrieving pluginfacts
Error: /File[/opt/puppetlabs/puppet/cache/facts.d]: Could not evaluate: Could not retrieve information from environment testing source(s) puppet:///pluginfacts
Error: Failed to apply catalog: Failed to retrieve pluginfacts: Could not retrieve information from environment testing source(s) puppet:///pluginfacts
```

2. due to the node request removal, we no longer get a 404 node request error from the server; this is how it looked on main prior to my PR:
```sh-session
> puppet agent -t --environment testing (6.x - before #8691)
Warning: Unable to fetch my node definition, but the agent run will continue:
Warning: Find /puppet/v3/node/sublime-secret.delivery.puppetlabs.net resulted in 404 with the message: {"message":"Not Found: Could not find environment 'testing'","issue_kind":"RUNTIME_ERROR"}
Info: Retrieving pluginfacts
Error: /File[/opt/puppetlabs/puppet/cache/facts.d]: Could not evaluate: Could not retrieve information from environment testing source(s) puppet:///pluginfacts
Error: Failed to apply catalog: Failed to retrieve pluginfacts: Could not retrieve information from environment testing source(s) puppet:///pluginfacts
```
This would have matched the `%r{(Warning|Error).*(404|400).*Could not find environment '#{env}'` expectation.

On 6.x, as `ignore_plugin_errors` is true, the agent eventually requests its catalog and errors with a message that matches the expectation above:
```sh-session
> puppet agent -t (6.x - after #8691)
Info: Retrieving pluginfacts
Error: /File[/opt/puppetlabs/puppet/cache/facts.d]: Could not evaluate: Could not retrieve information from environment testing source(s) puppet:///pluginfacts
Info: Retrieving plugin
Error: /File[/opt/puppetlabs/puppet/cache/lib]: Could not evaluate: Could not retrieve information from environment testing source(s) puppet:///plugins
Info: Retrieving locales
Error: /File[/opt/puppetlabs/puppet/cache/locales]: Could not evaluate: Could not retrieve information from environment testing source(s) puppet:///locales
Error: Could not retrieve catalog from remote server: Find /puppet/v3/catalog/sublime-secret.delivery.puppetlabs.net resulted in 404 with the message: {"message":"Not Found: Could not find environment 'testing'","issue_kind":"RUNTIME_ERROR"}
```

----------------

So, for main I think we just need to change the expected error message. 6.x can remain as is because of the failed catalog request (we can also change that to be more specific if we want). I'll push a commit with this change.

**Comment by GabrielNagy** [comment]
jenkins please test this with servertests

**Comment by GabrielNagy** [comment]
`tests/environment/environment_scenario-bad.rb passed in 74.75 seconds`

We have other failures which are due to test ordering, but I believe they should be fixed by #8720, so I think we're safe to merge this.

**Review by ciprianbadescu — APPROVED** [review]

**Pull request merged**
