### PR TITLE
(PUP-8632) device --apply works without a cert

### PR DESCRIPTION
**Pull request by tphoney**
puppet device --apply, doesnt error without having to register it with a puppet master.

### CODE REVIEW

**Comment by tphoney** [comment]
@joshcooper Thanks for the last merge, i need some feedback on this PR. When writing the logs/reports for the first time (specifically when creating the folders), it would fail. This PR makes the directory creation like "mkdir -p". 
The tests i removed relied on the fact that folder creation fails on nested folders. I removed them, but i am open to alternatives.

**Comment by joshcooper** [comment]
I'd rather not change uniquefile to create parent directories. I would think the device application just needs to call `Puppet.settings.use` with the sections it needs. We had similar problems with `puppet apply` fixed in https://github.com/puppetlabs/puppet/commit/f3f1702b490a9ae0291bd4335916d9b05cf0f957.

**Comment by tphoney** [comment]
@joshcooper No worries, i have changed the approach so there is less impact outside of device. 
I could not use settings :device as it would require a cert being setup. This just makes sure the cache folder structure exists.

**Comment by tphoney** [comment]
@joshcooper can you have another look please.

**Comment by joshcooper** [comment]
Sorry was out on PTO. I don't have an opinion on the changes, but it'd be good to have a test.

**Comment by tphoney** [comment]
Hope you had a good break @joshcooper . I added tests around the logic. @DavidS can you merge

**Pull request merged**
