### PR TITLE
(maint) Remove f19/f18, add f21, in acceptance

### PR DESCRIPTION
**Pull request by melissa**
Fedora 19 went EOL on 2015-01-06, and Fedora 18 went EOL on 2014-01-14.
We no longer have repos or packages available for fedora 18, and will
soon be removing our repos and packages for fedora 19. These two
versions no longer need to be tested with acceptance, but instead, we
should be testing fedora 21.

### CODE REVIEW

**Comment by melissa** [comment]
@kylog I'm not super familiar with acceptance, so I'm not sure this is the best thing to do, but I'd love you view on it. I'm running the tests right now

**Comment by kylog** [comment]
:+1: 

/cc @justinstoller

**Comment by melissa** [comment]
and I'm having trouble running acceptance... any advice?

**Comment by melissa** [comment]
So, I ran acceptance with the fedora21.yaml config, and everything looks good. I'd be shocked if changing from f18 to f21 broke things in the all_linux.yaml and all_but_windows.yaml, but I'm not positive

**Comment by joshcooper** [comment]
:+1: We don't use `all_linux.yaml` or `all_but_windows.yaml` in acceptance so that should be fine. 

Also do we want to add fedora 21 to https://jenkins.puppetlabs.com/view/Puppet/view/3.x/job/Puppet-Package-Acceptance-3x/?

**Comment by melissa** [comment]
@joshcooper I'm :+1: to that idea

**Comment by joshcooper** [comment]
Waiting for 3.x build failures to clear up, I will merge after

**Comment by melissa** [comment]
@joshcooper ping! Tests are green, and I'd love to see this get in!

**Comment by joshcooper** [comment]
I'll go ahead and merge, but it looks like we're not able to build f21 packages:

```
$ git grep fedora-
...
ext/build_defaults.yaml:final_mocks: 'pl-el-5-i386 pl-el-6-i386 pl-el-7-x86_64 pl-fedora-20-i386'
```

So I'll leave the jenkins config as is for 3.x

**Comment by joshcooper** [comment]
puppet 3.x future parser acceptance was testing against [fedora19](https://jenkins.puppetlabs.com/view/Puppet/view/3.x/job/Puppet-Acceptance-Future-Parser-3x/), I bumped that to fedora20 like we do in normal linux acceptance.

**Comment by melissa** [comment]
@joshcooper for some reason I forgot packages were needed for acceptance testing :) We aren't going to build puppet 3.x for fedora 21, but we will for 4.x (in the form of puppet-agent packages). 4.x already has the updated acceptance configs

**Comment by melissa** [comment]
And thank you for merging!

**Pull request merged**
