### PR TITLE
(PUP-7122) Add wrapper for gettext:update_pot rake task

### PR DESCRIPTION
**Pull request by Magisus**
This adds a wrapper rake task for a new update_pot task that has been
added to the gettext-setup gem. This task will cache the old POT file,
generate a new one, diff them, and only replace the old one if actual
string changes have occurred. This can be used to reduce churn from
changing dates and SHAs.

The second commit adds the `vendor` directory to the ignore list for gettext-setup. Vendored code should handle its own internationalization.

### CODE REVIEW

**Comment by Magisus** [comment]
This is blocked on https://github.com/puppetlabs/gettext-setup-gem/pull/19 and a subsequent release of that gem.

**Comment by Magisus** [comment]
The gettext gem version 0.13 with the new rake task has been released, so this PR is now unblocked.

**Comment by McdonaldSeanp** [comment]
👍

**Comment by Magisus** [comment]
Rebased this onto 5.0, since that's where all the string externalization is getting merged to.

**Comment by ScottGarman** [comment]
:+1:

**Pull request merged**
