### PR TITLE
(PUP-4562) Fix 'bsd' service provider and tweak description

### PR DESCRIPTION
**Pull request by jasperla**

### CODE REVIEW

**Comment by peterhuene** [comment]
Hi @jasperla.  Thanks for the contribution!  Sadly this looks like it's been broken for quite some time, so thanks for the spec coverage.  The changes look good to me, so I'll likely go over this PR in tomorrow's triage and consider it a candidate for merge.

One minor thing, could we reword the commit message?  "Unbreak" can be a little confusing.  Perhaps `Fix BSD service provider and tweak description`?  I'll leave it to your best judgement.  Cheers.

**Comment by jasperla** [comment]
Thanks, I've changed this PR's title and the commit message. Fix or unbreak, either way, at least now it works and provides a better base to work on.

**Comment by peterhuene** [comment]
@jasperla Thanks!

Triage note: CI failure is the spurious rdoc spec failure on Windows and can be ignored.

**Comment by peterhuene** [comment]
@infracaninophile as a fellow BSD user, do these changes make sense to you?

**Comment by infracaninophile** [comment]
Looks pretty reasonable to me.  This is presumably the provider for NetBSD (which I haven't used at all, really) because FreeBSD, DFly and OpenBSD do things sufficiently differently for this not to work, but then again, those OSes have their own providers.

**Comment by jasperla** [comment]
I've actually got an rcng provider for NetBSD/CargOS specifically which will subclass from this provider. I'll open a PR for that when this one is merged.

**Comment by peterhuene** [comment]
@infracaninophile Thanks for looking it over :+1: 

@jasperla Thanks again for the contribution!  This should appear in Puppet 4.2.

**Pull request merged**
