### PR TITLE
(PUP-1077) Remove nagios types from Puppet now that they're shipped in their own module

### PR DESCRIPTION
**Pull request by jhelwig**

### CODE REVIEW

**Comment by joshcooper** [comment]
Also need to remove references to Nagios in:

```
lib/puppet/pops/loader/static_loader.rb:      Nagios_command
lib/puppet/pops/loader/static_loader.rb:      Nagios_contact
lib/puppet/pops/loader/static_loader.rb:      Nagios_contactgroup
lib/puppet/pops/loader/static_loader.rb:      Nagios_host
lib/puppet/pops/loader/static_loader.rb:      Nagios_hostdependency
lib/puppet/pops/loader/static_loader.rb:      Nagios_hostescalation
lib/puppet/pops/loader/static_loader.rb:      Nagios_hostgroup
lib/puppet/pops/loader/static_loader.rb:      Nagios_hostextinfo
lib/puppet/pops/loader/static_loader.rb:      Nagios_service
lib/puppet/pops/loader/static_loader.rb:      Nagios_servicedependency
lib/puppet/pops/loader/static_loader.rb:      Nagios_serviceescalation
lib/puppet/pops/loader/static_loader.rb:      Nagios_serviceextinfo
lib/puppet/pops/loader/static_loader.rb:      Nagios_servicegroup
lib/puppet/pops/loader/static_loader.rb:      Nagios_timeperiod
```

**Comment by joshcooper** [comment]
Also not sure about these?

```
.rubocop.yml:    - 'lib/puppet/external/nagios/parser.rb'
acceptance/fixtures/manifest_large_exported_classes_node.pp:        # this is a vserver on this host, so register correctly in nagios
acceptance/fixtures/manifest_large_exported_classes_node.pp:        $nagios_parent = "ic.black.co.at"
ext/debian/copyright:Files: lib/puppet/external/nagios/parser.rb
ext/redhat/puppet.spec.erb:for f in external/nagios.rb relationship.rb; do
```

**Comment by jhelwig** [comment]
The `acceptance/fixtures/` ones don't actually use any nagios types, they just have the comment & variable with "nagios" in the name. The other ones all look legit to remove. I'll update the PR. 👍

**Comment by joshcooper** [comment]
👋 nagios

**Pull request merged**
