### PR TITLE
(maint) run cron tests on fedora using cronie

### PR DESCRIPTION
**Pull request by gimmyxd**
Skip cron tests on Fedora 29

### CODE REVIEW

**Comment by gimmyxd** [comment]
passing build of agent with this changes: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/408/
Also i guess this should be referenced to a PUP ticket not PA.

**Comment by ScottGarman** [comment]
I'm :+1: on the code changes, and agree with Enis' request for the commit message.

**Comment by gimmyxd** [comment]
@ekinanp @ScottGarman 
rather than skipping fedora tests, i changed the code to install cronie on fedora. Now the cron tests are running and passing on fedora-28/29

https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/411/

**Comment by ekinanp** [comment]
@gimmyxd Interesting. @branan or @caseywilliams might be interested in that. We do use cronie to run cron tests on some other platforms as well.

**Comment by ScottGarman** [comment]
Yeah, F29 uses systemd to manage cron now. Until we have acceptance tests that make use of this (which we'll want for the upcoming RHEL 8), this workaround seems reasonable.

**Comment by gimmyxd** [comment]
Can this be merged?

**Pull request merged**
