### PR TITLE
(PUP-8586) Improve missing library debug message

### PR DESCRIPTION
**Pull request by Sharpie**
This commit re-words the debug message emitted when a library required by a
feature could not be loaded. The new message clarifies that an optional feature
is not being enabled and removes the word "fail" which ensnares folks who are
attempting to debug problems unrelated to the feature system.

### CODE REVIEW

**Comment by joshcooper** [comment]
Thanks @Sharpie! Would you be up for eliminating other sources of spam/scary messages as described in https://tickets.puppetlabs.com/browse/PUP-8586?

**Comment by Sharpie** [comment]
Thought there might be another ticket out there for this :)

I'll take a look at replacing the items called out in PUP-8902 with calls to `debug_once`.

**Comment by Sharpie** [comment]
I've updated the feature load message to use `debug_once` from `Puppet::Util::Warnings` which does a nice job of cutting down on the spam. Will look at the server port and provider feature messages listed in PUP-8586.

However, the feature library load still has some redundancy:

    Debug: Could not load library 'msgpack' required to enable feature 'msgpack': cannot load such file -- msgpack

The bit after the `:` comes from the `LoadError` message, but is completely redundant given the rest of the message. Since a `LoadError` is an expected failure, I'm thinking we should log this plainly at `debug` level:

    Debug: Could not load library 'msgpack' required to enable feature 'msgpack'

And log other errors classes at `warn` or `error` given something unusual probably happened:

    Warning: Could not load library 'msgpack' required to enable feature 'msgpack': some unexpected exception occurred!

**Comment by melissa** [comment]
@Sharpie this change looks good. We just need to rebase and get tests passing, and we should be able to merge this! Let us know if we can do anything to help out with that.

**Comment by Sharpie** [comment]
Thanks for the ping! This one slipped through the cracks.

Looks like I got 2/3rds of the way through PUP-8586 as the current PR addresses the messages around loading feature libraries and connections, but does not help the repeated provider messages. I think I got bogged down there trying to find a sane way to de-duplicate that where memory usage wasn't going to scale with the number of resources in the catalog.

If 2/3rds is fine, I can re-base this and get the tests passing.

**Comment by jhelwig** [comment]
Even if this doesn't completely address the ticket, improvements are still improvements. Do you expect that addressing the repeated provider messages would have a large impact on the work already in this PR?

**Comment by Sharpie** [comment]
Nope, the ticket was a grab-bag of three disjoint issues that all had "noisy/unhelpful log messages" as their symptom. Solving the provider messages just turned into a bit of a tarpit.

I'll rebase this onto master and split the provider logging issue out to a separate ticket.

**Comment by Sharpie** [comment]
Changes rebased, tests fixed, and [PUP-9510](https://tickets.puppetlabs.com/browse/PUP-9510) opened to address the logging around provider features.

**Pull request merged**
