### PR TITLE
(man): fixed typo error

### PR DESCRIPTION
**Pull request by 0xflotus**

### CODE REVIEW

**Comment by melissa** [comment]
Hey @0xflotus thank you for the contribution!

This looks great, but the tests are failing because of how the commit is formatted.

For ease, here's the error it's giving us.
```
	This commit summary didn't match CONTRIBUTING.md guidelines:
		(man): fixed typo error
	The commit summary (i.e. the first line of the commit message) should start with one of:
		(PUP-<digits>) # this is most common and should be a ticket at tickets.puppet.com
		(docs)
		(docs)(DOCUMENT-<digits>)
		(maint)
		(packaging)
		(L10n)
	This test for the commit summary is case-insensitive.
```
so rather than starting your commit with `(man):` could you change that to `(docs)`?

Once you do that, we can merge in this change!

**Comment by melissa** [comment]
If you want any help changing your commit message, I'm happy to walk you through the process either here or on slack at puppetcommunity.slack.com

**Comment by melissa** [comment]
Hi @0xflotus, it's been a while! We're happy to merge this PR once you update the commit message.

Otherwise, we try not to leave pull requests open for too long. If we don't hear back from you in 2 weeks, we'll close this PR. You're always able to re-open the closed PR or open a new one if you still want this change to get in.

Again, we're always happy to help you make PR changed if you want help!

**Comment by shrug** [comment]
Closing due to lack of activity, feel free to reopen if you'd like to continue with this.

Thanks!

**Pull request closed without merging**
