### PR TITLE
(maint) Merge 6.0.x to 6.4.x 

### PR DESCRIPTION
**Pull request by gimmyxd**

### CODE REVIEW

**Comment by gimmyxd** [comment]
Jenkins please test this on osx1014-64,redhat7-64,ubuntu1604-64,windows2012r2-64

**Comment by DavidS** [comment]
This seems to be reverting https://github.com/puppetlabs/puppet/commit/92ffa950dd3ce1d22e0129383d92d352e6b7eaab This might already be an issue with the 6.0.x mergeup. We can discuss going ahead with the mergeup as is, and reopen PUP-9047 again, re-apply the fix and run the gauntlet again? I'm not sure how yous want to handle this.

**Comment by gimmyxd** [comment]
@DavidS seems that this was introduced in 5.5.x to 6.0.x mergeup https://github.com/puppetlabs/puppet/pull/7537/files#diff-04320a89c8d93fd690987c658c04d842
We can submit a different PR to fix the issue in 6.0.x and wait for the next mergeup.

**Comment by mihaibuzgau** [comment]
the issue that @DavidS mentioned is fixed in the following PR: https://github.com/puppetlabs/puppet/pull/7550

👍  to merge this.

**Pull request merged**
