### PR TITLE
(PUP-9092) Improve process termination handling on Windows

### PR DESCRIPTION
**Pull request by joshcooper**
@onyxmaster noticed we always wait a minimum of 1 second when launching external processes on Windows, which can greatly slow down puppet when there are a large number of exec resources. Now we wait at most 1 second, and repeat as necessary until the process exits or we're interrupted. Credit to @onxymaster for finding this and submitting a PR.

This supersedes PR#7038.

### CODE REVIEW

**Comment by joshcooper** [comment]
Earlier versions of ruby could not interrupted if the main thread was blocked in a native Win32 call. So for example calling `WaitForSingleObject` with a 1 second timeout, means it could be slow to respond to interruption. See my comment on an earlier version of the PR: https://github.com/puppetlabs/puppet/pull/7033#issuecomment-417436281. But in my testing it seems instantaneous, so perhaps ruby has gotten better about that?

**Comment by onyxmaster** [comment]
@joshcooper I remember Ruby working in the same way you described (handling signals only at predefined cancellation points, which did not include system calls) when I was actively using it about 7 years ago (this was the reasoning behind setting the `WAIT_INTERVAL` to 15ms instead of something larger).
Maybe Ruby got smarter, or [FFI](https://github.com/ffi/ffi) is able to handle async exceptions in a smart way.

**Comment by joshcooper** [comment]
So I take back what I said about `my testing it seems instantaneous`. Setting the timeout to a larger value, ruby doesn't interrupt while blocked in the `WaitForSingleObject` call. So I think we need to choose a timeout that works for interactive users, while minimizing CPU utilization due to polling. Does 200ms seem ok?

**Comment by onyxmaster** [comment]
I believe that anything below 250-300ms is OK. I think that 15ms will do fine though, without wasting CPU and/or power.

The proposed value of 15ms (actually 15.625ms) might be actually better than you believe, since it's the default scheduling quantum on Windows (it's not that simple, but [GetSystemTimeAdjustment](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724394(v=vs.85).aspx) returns 156250, so it appears that it still holds). 

Since this is a service thread (so no priority boosts), I guess that thread priority and process priority class are default ones, any non-zero-timeout sleep reschedules the thread to run in ceil(time/15.625)*15.625 milliseconds. So, sleeping for 1ms under normal circumstances will still block the thread for 15.625 ms (if it does nothing but sleeping in a loop).
But (there is always a "but") some programs (neither of which should be run on server) mess with the timer resolution (this, for example, includes old versions Chrome and lots of other software), so sleeping for 1ms might be unsafe, hence the 15ms wait time (no higher precision is available in wait functions).

If you prefer to be on the safe side (and I agree with you), I believe that picking the value that is 10 times larger (150ms) will not spend any significant amount of CPU and will produce the "instant" perception of signal handling.

P.S. Before I started writing this reply, I built and started a program that calls Win32 Sleep(15) in an endless loop. The system believes that it spent 31ms of CPU time for its lifetime of 1020 seconds, which makes it (31ms -cpu-time/ 1020seconds-running) * 86400seconds-per-day / 1000milliseconds-per-second = 2.626 seconds per day of CPU time spent.

**Comment by onyxmaster** [comment]
I would like to add that I tested the "pure" case (a "while (true)" loop with only a Sleep inside, written in C#). We certainly must consider the const of the system call itself (I think that waiting on a handle is more complex than relinquishing the control), overhead of Ruby FFI and the cost of Ruby "native" sleep, so in practice 15ms might be just a little too fast.
As for my proposal of 150ms -- you already adjusted the value to 200ms, I believe that you should leave as it is, I don't think that many people will feel the difference of 50ms =)

**Pull request merged**
