### PR TITLE
(PUP-7141) stop dup of frozen string in 3x converter

### PR DESCRIPTION
**Pull request by hlindberg**
This removes the logic that duplicated frozen strings before giving them to the 3.x "runtime API". That was done because some resource types mutated their given arguments. (Notably the user resource type). 

This PR changes the runtime3converter (no longer duplicates frozen strings) as well as user resource type and a questionable mutating gsub! in the windows package.

### CODE REVIEW

**Comment by thallgren** [comment]
jenkins please test this

**Comment by joshcooper** [comment]
Won't this break existing custom providers in modules that try to mutate the value like we were doing, e.g. https://github.com/cisco/cisco-network-puppet-module/blob/release_1.9.0/lib/puppet/type/cisco_command_config.rb#L100-L107

**Comment by hlindberg** [comment]
Yes it will break custom providers that mutate their input. They should not do that. I understand if we don't want to break them, but types/providers should really be fixed.
There are alternatives: a) serialize and deserialize the catalog also in the apply scenario (not sure what kind of overhead that is compared to all the copies that are created - could be a wash), b) not dup when running as master as no providers will run, still risk of breaking if a resource type is doing this - I think the cisco example would possibly break (would work if using generate types though).

**Comment by hlindberg** [comment]
@joshcooper I made a commit that performs the dup on frozen string when not running in master mode. Then we at least get rid of these on a compile master (where no mutating resource types/providers are present).

**Comment by hlindberg** [comment]
jenkins please test this

**Comment by hlindberg** [comment]
@joshcooper ok to merge now?

**Comment by joshcooper** [comment]
@hlindberg the changes make sense... I'm wondering what the impact would be to make it a hard error always? This is our opportunity to make breaking changes for things that are clearly wrong. But I don't have a feel for how many modules (type/provider/functions) would be affected?

**Comment by hlindberg** [comment]
@joshcooper Really hard to say. I am in favor of always having this as an error. If a type/provider encounters this error it will be very clear what is wrong and it should be easy to fix - so while there is a risk things break - it is clearly a bug, and there is a clear error. The alternative; allowing mutation can lead to hard to find (silent) problems.

Trying to deprecate this is very hard as the attempt to mutate will raise an error so cannot just log this and continue.

Your call if the last commit should be present or not (the one that does a dup when on agent).

**Comment by joshcooper** [comment]
yeah let's drop the last commit

**Comment by joshcooper** [comment]
It looks like there are only 2 instances on the forge that would be affected:

```
ag 'gsub!' */lib/puppet/type/*.rb
darin-zypprepo-1.0.2/lib/puppet/type/zypprepo.rb
112:        reposdir.gsub!(/[\n,]/, " ")
138:      reposdir.gsub!(/[\n,]/, " ")

mikeknox-zypprepo-0.0.1/lib/puppet/type/zypprepo.rb
129:                reposdir.gsub!(/[\n,]/, " ")
159:            reposdir.gsub!(/[\n,]/, " ")

puppetlabs-ciscopuppet-1.1.0/lib/puppet/type/cisco_command_config.rb
104:      value.gsub!(/^\s*$\n/, '')
106:      value.gsub!(/^(#{indent_level})/, '') # remove extra indentation

swindlife-emc_vnx-0.1.3/lib/puppet/type/vnx_storagesystemcache.rb
11:      value.gsub!(/\s+/, "")
```

The `zypprepo` does the `gsub!` in a different part of the code, so not during property munging. The cisco one we already knew about. Can you file a MODULES ticket for them to fix that and reach out to https://forge.puppet.com/swindlife/emc_vnx to have them update their module?

**Comment by hlindberg** [comment]
Will drop the last commit, and reach out to emc_vnx

**Comment by hlindberg** [comment]
Created ticket: https://tickets.puppetlabs.com/browse/PUP-9098 for MODULES

**Comment by hlindberg** [comment]
reached out to emc_vnx here: https://github.com/thecodeteam/puppet-vnx/issues/10

**Comment by hlindberg** [comment]
@joshcooper PR updated (last commit which only made the change apply to master-mode is now dropped). Also freshly rebased on current master.

**Pull request merged**
