### PR TITLE
(PUP-8441) Add to_json method to Error datatype

### PR DESCRIPTION
**Pull request by adreyer**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Can you describe the problem this solves in the [commit?[](url)](url)

**Comment by hlindberg** [comment]
I think it is not a good design to force objects to have `to_json`. Instead a serializer / converter should use the hash with the attributes of the object.
We spent a lot of effort in *removing* 'to_this' and 'to_that' in the codebase to make serialization independent of the data elements being serialized as that causes problems.

There is a converter that can be used to turn a structure into json-able data - simply use `ToDataConverter.convert(x).to_json` where `x` is the entire structure to convert.

**Comment by joshcooper** [comment]
@adreyer Should we close this?

**Comment by hlindberg** [comment]
Closing as we need to provide support for transformed results as discussed in the associated ticket.

**Pull request closed without merging**
