### PR TITLE
(PA-652) Bump Puppet version to 4.8.1

### PR DESCRIPTION
**Pull request by Magisus**
This updates the Puppet version to 4.8.1 following the release of 4.8.0
as part of puppet-agent 1.8.0.

### CODE REVIEW

**Comment by Magisus** [comment]
Travis commit checker is failing because it requires a PUP ticket. Do we want to allow to fail, or switch to maint? Might it be worthwhile to add PA tickets to the whitelist?

**Comment by joshcooper** [comment]
For this sort of thing I usually use `(packaging)` as the prefix.

**Comment by MosesMendoza** [comment]
+1 to `(packaging)`

**Comment by Magisus** [comment]
Updated

**Comment by MosesMendoza** [comment]
👍

**Pull request merged**
