### PR TITLE
Revert "Merge pull request #7220 from hlindberg/pup-9294_report-illeg…

### PR DESCRIPTION
**Pull request by joshcooper**
…al-3x-function-defining-methods"

This reverts commit ff88975f06c7ac5931d5b9894bbdb9ac7560ea8d, reversing
changes made to e7c3983cd82f16c01cf98f601f993f7083b918e9.

### CODE REVIEW

**Comment by Magisus** [comment]
How was this found?

**Comment by joshcooper** [comment]
@Magisus Sorry should have linked the failure. PEZ is failing with this change.

**Comment by hlindberg** [comment]
I have a PR up with a fix for the problem. https://github.com/puppetlabs/puppet/pull/7284

**Comment by McdonaldSeanp** [comment]
Due to the failing pipelines and the pending release I am going to push this revert through so we might get green 6.0/master testing through this evening.

**Pull request merged**
