### PR TITLE
(PUP-5804) update acceptance test to support cisco

### PR DESCRIPTION
**Pull request by LuvCurves**

### CODE REVIEW

**Comment by LuvCurves** [comment]
This requires the next version of beaker (2.33.0+) and beaker-hostgenerator (0.3.2+)

**Comment by kylog** [comment]
This is making me wonder if we should look at a scheme for moving which-test-to-run-for-a-platform outside the repo itself. Thoughts @LuvCurves or @johnduarte or @joshcooper?

**Comment by johnduarte** [comment]
@kylog I actually find it valuable to see the confines directly in the tests. This provides direct feedback on where the test is either not applicable or where there are known issues.

just my 2 cents.

**Comment by LuvCurves** [comment]
@kylog I like the idea of having a single location to make changes like this.  I'm certain I'll have to do this exercise again when cisco-7 is ready and then again when Huawei is ready.

**Comment by kylog** [comment]
I realize my comment above was an implementation detail without a motivating concern :)

FWIW then, my concern was that this approach means issuing releases of components *just* so that we can skip tests in those components. Avoiding that was why we went through the b-hg exercise in December so this feels like a regression in that regard.

**Comment by LuvCurves** [comment]
Beaker 2.34.0 is available

**Comment by sbeaulie** [comment]
Is this ready to go?

**Comment by LuvCurves** [comment]
@sbeaulie Nope.  There are a few tests I'm currently skipping that I need to get a root cause on their failure.

**Comment by LuvCurves** [comment]
Closing. Will refactor against latest stable branch

**Pull request closed without merging**
