### PR TITLE
(maint) Use correct local variable name

### PR DESCRIPTION
**Pull request by ccaviness**

### CODE REVIEW

**Comment by branan** [comment]
Thanks for the typo fix!

Please update the commit message to follow our guidelines - since there's no ticket for a change like this you can use `(maint)` to make our automated tooling happy.

**Comment by ccaviness** [comment]
Done.

**Comment by ccaviness** [comment]
... or not? github web UI not doing what I ask.

**Comment by ccaviness** [comment]
There you go.

**Comment by branan** [comment]
@ccaviness updating the PR name doesn't update the actual commit message (and vice-versa). You'll need to use `git commit --amend` and `git push --force` to change the actual commit

**Comment by ccaviness** [comment]
Ok, I think that did it. Serves me right for doing this in the web UI.

**Comment by branan** [comment]
Looks good. Thanks again!

**Pull request merged**
