### PR TITLE
(PUP-7292) Change to allow set of password_warn_days

### PR DESCRIPTION
**Pull request by Klaas-**
some of the spec tests for useradd are not working for me, all tests I've modified work though

### CODE REVIEW

**Comment by Magisus** [comment]
Thanks for opening this! It seems like a reasonable feature request. We will take a closer look when we get a chance.

**Comment by Klaas-** [comment]
I added this a couple oft months ago... Do you you rebase this against the current master yourselves? I haven't checked of you modified the code I change for puppet5

**Comment by Magisus** [comment]
Since there are no conflicts against the base branch right now, we probably won't rebase. However, feel free to do so if you'd like. In general if there are conflicts, we prefer rebasing to merging because it keeps the history cleaner.

**Comment by MosesMendoza** [comment]
@Klaas- - this is great, thank you! thanks for adding great tests too

validated command flags on solaris, linux (deb/ubuntu), aix

👍

**Comment by Klaas-** [comment]
@MosesMendoza thanks for the merge, I had already forgotten about this :)

**Pull request merged**
