### PR TITLE
(PUP-8601) Add rich data formats

### PR DESCRIPTION
**Pull request by pcarlisle**
Add two new network formats for representing rich data over json and
msgpack. This allows server and agent to negotiate rich data support and
maintain compatibility across versions.

This slightly changes the behavior of `preferred_serialization_format`.
This now controls the underlying format (json vs msgpack) and the
`rich_data` setting controls whether the rich data variant will be used.

For example, if `preferred_serialization_format` is set to `json` and
`rich_data` is enabled, puppet will list
`application/vnd.puppet.rich+json` first in the list of formats. If
`rich_data` is not enabled then it will list `application/json` first and
not include `application/vnd.puppet.rich+json`.

This also enables rich data by default.

### CODE REVIEW

**Comment by joshcooper** [comment]
jenkins please test this with servertests

**Comment by hlindberg** [comment]
Since, rich_data must be turned on at both ends for the catalog format to be rich data we must provide a variable that can be used in manifests for conditional compilation since neither looking at agent version nor `$settings::rich_data` will be correct. What we could possibly do is to make `$settings::rich_data` reflect the effective value in the context.

**Comment by pcarlisle** [comment]
jenkins please test this with servertests

**Comment by tvpartytonight** [comment]
I cannot resist but leave this image: rich mime

**Comment by tvpartytonight** [comment]
jenkins please test this with servertests

**Comment by pcarlisle** [comment]
acceptance passed, going to just push a fix to warnings

**Pull request merged**
