### PR TITLE
(PUP-9652) Delete audit:delete acceptance tests

### PR DESCRIPTION
**Pull request by johnduarte**
This PR deletes acceptance tests that were previously audited and tagged with the `audit:delete`.

### CODE REVIEW

**Comment by justinstoller** [comment]
Does anyone from @puppetlabs/platform-core want to take a look at and/or merge this before I do?

**Comment by melissa** [comment]
jenkins please test this

**Comment by melissa** [comment]
We'll probably have to modify https://github.com/puppetlabs/puppet/blob/master/acceptance/Rakefile#L36-L48 since some of these tests are going to be removed

**Comment by johnduarte** [comment]
Thanks for pointing out the rake task @melissa I have added a commit to remove the test affected from the Rakefile.

**Comment by melissa** [comment]
jenkins please test this

**Pull request merged**
