### PR TITLE
(PUP-8575) Remove network_device type/provider code

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by melissa** [comment]
jenkins please test this

**Comment by melissa** [comment]
there are more ad hoc pipelines I want to run with this before we merge

**Comment by melissa** [comment]
jenkins please test this on aix61-POWER,aix71-POWER,amazon6-64,arista4-32,ciscoxr-64,cumulus25-64,debian7-32a,osx1011-64,redhat5-64,sles11-64,solaris10-SPARC,solaris11-64,solaris11-SPARC,ubuntu1604-POWER,windows2012r2-64

**Comment by melissa** [comment]
jenkins please test this on ciscoxr-64,cumulus25-64,arista4-32

**Comment by melissa** [comment]
jenkins please test this on ciscoxr-64,cumulus25-64,arista4-32

**Comment by melissa** [comment]
Building cisco keeps timing out 
```
09:48:48 cd /tmp/tmp.XXXXVWEFBx/leatherman/tests && /opt/pl-build-tools/bin/g++   -DBOOST_LOG_WITHOUT_WCHAR_T -DBOOST_SYSTEM_NO_DEPRECATED -DLEATHERMAN_LOCALE_INSTALL=\"/opt/puppetlabs/puppet/share/locale\" -DLEATHERMAN_LOGGING_NAMESPACE=\"leatherman.test\" -DPROJECT_DIR=\"/tmp/tmp.XXXXVWEFBx/leatherman\" -DPROJECT_NAME=\"leatherman\" -Wno-maybe-uninitialized -fPIC -fPIC  -O3 -DNDEBUG -I/tmp/tmp.XXXXVWEFBx/leatherman/ruby/inc -I/tmp/tmp.XXXXVWEFBx/leatherman/execution/inc -I/tmp/tmp.XXXXVWEFBx/leatherman/dynamic_library/inc -I/tmp/tmp.XXXXVWEFBx/leatherman/curl/inc -I/tmp/tmp.XXXXVWEFBx/leatherman/file_util/inc -I/tmp/tmp.XXXXVWEFBx/leatherman/json_container/inc -I/tmp/tmp.XXXXVWEFBx/leatherman/src/rapidjson/include -I/tmp/tmp.XXXXVWEFBx/leatherman/rapidjson/inc -I/tmp/tmp.XXXXVWEFBx/leatherman/logging/inc -I/tmp/tmp.XXXXVWEFBx/leatherman/locale/inc -I/tmp/tmp.XXXXVWEFBx/leatherman/util/inc -I/tmp/tmp.XXXXVWEFBx/leatherman/nowide/../vendor/nowide/include -I/tmp/tmp.XXXXVWEFBx/leatherman/nowide/inc -I/tmp/tmp.XXXXVWEFBx/leatherman/src/Catch-1.10.0/single_include -I/tmp/tmp.XXXXVWEFBx/leatherman/catch/inc -I/opt/puppetlabs/puppet/include -I/opt/pl-build-tools/include    -Wextra -std=c++11 -Wall -Werror -Wno-unused-parameter -Wno-unused-local-typedefs -Wno-unknown-pragmas -Wno-missing-field-initializers -Wno-maybe-uninitialized -fPIC -fPIC  -o CMakeFiles/leatherman_test.dir/__/ruby/tests/api-test.cc.o -c /tmp/tmp.XXXXVWEFBx/leatherman/ruby/tests/api-test.cc
12:00:05 Write failed: Broken pipe
```

**Comment by melissa** [comment]
jenkins please test this on ciscoxr-64,cumulus25-64,arista4-32

**Comment by melissa** [comment]
Ah hah! Tests FINALLY passed!! https://jenkins-platform.delivery.puppetlabs.net/job/platform_puppet-agent-extra_puppet-agent-integration-suite_pr/474/
screen shot 2018-07-18 at 8 13 19 am

I'm going to also run the cisco_ios adhoc pipeline with these builds

**Comment by melissa** [comment]
In the nightly tests, we keep getting errors like
```
12:31:49 vvg57a9906xxzrm.delivery.puppetlabs.net (centos7-64-1) 19:31:49$ service pe-puppetserver restart
12:31:49   Redirecting to /bin/systemctl restart  pe-puppetserver.service
12:31:49   Failed to restart pe-puppetserver.service: Unit not found.
12:31:49 
12:31:49 vvg57a9906xxzrm.delivery.puppetlabs.net (centos7-64-1) executed in 0.07 seconds
12:31:49 Exited: 5
12:31:49 
12:31:49 An error occurred in a `before(:suite)` hook.
12:31:49 Failure/Error: on(host, 'service pe-puppetserver restart', acceptable_exit_codes: [0, 1])
12:31:49 Beaker::Host::CommandFailure:
12:31:49   Host 'vvg57a9906xxzrm.delivery.puppetlabs.net' exited with 5 running:
12:31:49    service pe-puppetserver restart
12:31:49   Last 10 lines of output were:
12:31:49   	Redirecting to /bin/systemctl restart  pe-puppetserver.service
12:31:49   	Failed to restart pe-puppetserver.service: Unit not found.
```

There's really not a good way to run the cisco_ios pipeline with this new version of puppet. I say we move forward with this, and keep an eye on the networking module pipelines over the next week.

**Comment by shermdog** [comment]
@melissa lets at least get a manual run done first.  We have some customer fixes coming up that need to go out for the cisco_ios module and would hate for this to block that work.

cc @davidmalloncares

**Comment by melissa** [comment]
Alright, I was able to run tests against a puppet-agent built with these changes
```
Finished in 24 minutes 38 seconds (files took 27.19 seconds to load)
75 examples, 0 failures, 2 pending
```

I set up a pe puppet master on a centos-7 box, and verified I could run tests against one of the cisco machines.

Locally, I set up a `device.conf` and `cisco.yaml` to point to `cisco-c6503e.delivery.puppetlabs.net`. I also set some env vars, because it looked like those were necessary for tests.
```
$ cat ~/.puppetlabs/etc/puppet/device.conf
[target]
  type cisco_ios
  url file:///Users/Melissa/.puppetlabs/etc/puppet/cisco.yaml
$ cat ~/.puppetlabs/etc/puppet/cisco.yaml
address = cisco-c6503e.delivery.puppetlabs.net
username = admin
password = bayda.dune.inca.nymph
enable_password = bayda.dune.inca.nymph
$  export DEVICE_IP=cisco-c6503e.delivery.puppetlabs.net
$  export DEVICE_USER=admin
$  export DEVICE_PASSWORD=bayda.dune.inca.nymph
$  export DEVICE_ENABLE_PASSWORD=bayda.dune.inca.nymph
```

I ran `$ BEAKER_provision=yes BEAKER_destroy=no PUPPET_INSTALL_TYPE=pe BEAKER_set=vmpooler BEAKER_debug=true bundle exec rspec spec/acceptance/banner_spec.rb` first to make sure the tests worked. Once I verified that was good, I ssh'd to the master that had been set up, and I installed my newer puppet-agent package on that machine. I manually verified the cisco files had all been removed as expected by checking `/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/network_device`, `/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type`, and `/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/provider`.

I then ran `BEAKER_provision=no BEAKER_destroy=no PUPPET_INSTALL_TYPE=pe BEAKER_set=vmpooler BEAKER_debug=true bundle exec rspec spec/acceptance/banner_spec.rb` to make sure everything was still functional. Here I ran into an issue where is couldn't find the `cisco_ios` module. It was being copied over to `/etc/puppetlabs/puppet/modules`, but puppet couldn't find it. I moved it to `/etc/puppetlabs/code/modules` and the test passed as expected.

I then ran the whole test suite and everything passed!

I did look back through the output to make sure it did look like it was connecting to `cisco-c6503e.delivery.puppetlabs.net`, and it did.

@shermdog any other manual testing beyond this that you would like to see?

**Comment by joshcooper** [comment]
nit, conflict with static loader stuff

**Pull request merged**
