### PR TITLE
(PUP-3094) - Support for dynamic SELinux domain transition

### PR DESCRIPTION
**Pull request by lzap**
Do not merge, this is for initial discussion.

Here is what we think is the best approach to allow dynamic transition into
target SELinux domains required for hardening master and ca processes as
discussed in

https://groups.google.com/forum/#!topic/puppet-dev/VTb2o-Nuxkw

This replaces wrappers which were proposed in

https://github.com/puppetlabs/puppet/pull/2997

Let me know if you like this approach in comments and I will go ahead and test
this (this is a draft really). Thanks. @domcleal

### CODE REVIEW

**Comment by MikaelSmith** [comment]
PR Triage Notes:
* Assigning to @haus and RelEng to review.

**Comment by lzap** [comment]
Guys it's on my radar, not finished yet. Hope to get to this soon.

**Comment by joshcooper** [comment]
PR Triage Notes:

* @haus to finish review and comment

**Comment by kylog** [comment]
@camlow325 or @cprice404 how would this best be handled in puppet-server? Going forward, that seems like the app where we would want this support.

**Comment by cprice404** [comment]
@haus @waynr seems like we need to look into doing something like this for the clojure apps generally, then?

**Comment by kylog** [comment]
@lzap looks like this has a failing spec on 1.8.7 but good news: we've dropped 1.8.7. I think if you rebase that may clear up the travis failure.

**Comment by lzap** [comment]
I am afraid this will not work on JRuby since there are no SELinux bindings available. Does the code need to be working on JRuby or not?

**Comment by haus** [comment]
@ahpook @cprice404 see above about jruby.

**Comment by cprice404** [comment]
AFAIK this should only affect ruby command-line commands.  We have no intention of those ever being run under JRuby, we only use JRuby in the server process.  So I think this should be OK.

**Comment by camlow325** [comment]
One thing we will need to understand if we don't already is how this would affect any new command-line commands we would create that could run under Java - whether there's anything special we need to do to support SELinux domain transition, whether/how the Java processes need to be made distinct to support application of different policies per each, etc.  @haus - is this something we've already covered?

**Comment by haus** [comment]
@cprice404 @camlow325 and I discussed this some today. Any code being run via the commandline and jruby would live in puppet-server and not puppet, so it shouldn't be a concern or blocker for this work.

**Comment by ScottGarman** [comment]
PR Triage notes: We appreciate your contribution but at this time we're preparing to release Puppet 4.0.0, and we need to hold this PR for merge until the release is completed.

**Comment by ScottGarman** [comment]
@lzap also, can you look into why the Travis build failed? It might just need an update for rspec v3.

**Comment by kylog** [comment]
The travis failure is on 1.8.7 which puppet/master doesn't support any more. So a rebase might clean that up.

**Comment by ScottGarman** [comment]
A simple rebase to the latest master passes Travis CI. I've opened [PR-3627](https://github.com/puppetlabs/puppet/pull/3627) to supercede this PR

**Pull request closed without merging**
