### PR TITLE
    (PUP-4695) New acceptance test for hiera function calls from with templates

### PR DESCRIPTION
**Pull request by segatspiretech**
Until now we had no acceptance tests for verifying behavior of hiera
    function calls (hiera(), hiera_array(), hiera_hash(), and hiera_include()) f
    within a template (erb or epp).

    This test calls hiera functions from with in an erb template and from within
    an epp template.  The master is configured with a manifest.  The client
    applies the manifest using the puppet agent -t call.  The file created by
    templates are examined to determine whether the hiera function calls returne
    the expected values.

    hiera_include() is called from the epp template.  The included sub-modules
    each create a file that is then checked for correctness.

### CODE REVIEW

**Comment by peterhuene** [comment]
Hi @segatspiretech.  Thanks for the contribution!  @er0ck and @johnduarte, would you mind looking over this acceptance test to verify and confirm the coverage hole?  Thanks!

**Comment by er0ck** [comment]
do we have a list of github accounts that are PL employees?  @segatspiretech is Sean on the QA team.  :100:

**Comment by er0ck** [comment]
see comments on previous PR: https://github.com/puppetlabs/puppet/pull/4222 for context.

new PR required due to git snafus.

we do have a test-coverage hole here, and this was deemed high risk.  

i'm :+1:  to merge

**Comment by joshcooper** [comment]
@segatspiretech it looks like the commit message has leading spaces, which is causing travis to fail:

```
commit 1554fd0f81da04f30c535becffb9199afbb19e01
Author: Sean Griffin <sean@puppetlabs.com>
Date:   Fri Sep 4 14:44:46 2015 -0700

        (PUP-4695) New acceptance test for hiera function calls from with templates

        Until now we had no acceptance tests for verifying behavior of hiera
```

**Comment by segatspiretech** [comment]
Closing to try again with a new PR for this ticket.

**Pull request closed without merging**
