### PR TITLE
(PUP-10509) Drop support for Ruby < 2.5

### PR DESCRIPTION
**Pull request by GabrielNagy**
Drop distinction between Bignum and Fixnum (they were unified as Integer in 2.4), remove some monkey patches and conditional spec logic.

### CODE REVIEW

**Comment by GabrielNagy** [comment]
Apparently jruby 9.2.8.0 does not know about `OpenSSL::X509::Name#to_utf8`.

Should we keep the monkey patch only for jruby? @joshcooper 

I see the method was added in https://github.com/ruby/openssl/pull/143 for MRI, but the jruby-openssl still doesn't have it (https://github.com/jruby/jruby-openssl).

**Comment by joshcooper** [comment]
Some background context, requiring 'openssl' in fips-enabled puppetserver will raise, so we do https://github.com/puppetlabs/puppet/blob/3b720e6e2ebbbffd73e7e4ecd6b12746c162cfbb/lib/puppet/ssl/openssl_loader.rb#L8

When running non-fips puppetserver, we still require 'openssl' but I don't believe we ever execute code paths that call `Name#to_utf8`. For example puppetserver installs its own HTTP client via `Puppet::Network::HttpPool.http_client_class=`, which bypasses the SSLProvider, CertProvider, Verifier, etc.

To answer your question, I have a slight preference to keep the monkey patch so that we get additional test coverage, even if the code doesn't execute on puppetserver.

**Review by joshcooper — APPROVED** [review]

**Comment by joshcooper** [comment]
Travis sometimes gets confused about build status so I'm going to ignore that.

I want to get PE CI green again before merging this, so probably will be next Monday.

**Comment by joshcooper** [comment]
jenkins please test this on redhat7-64a,ubuntu1804-64a,windows2019-64a with servertests

**Pull request merged**
