### PR TITLE
(PUP-9026) create rich data catalog acceptance test

### PR DESCRIPTION
**Pull request by er0ck**
* remove old catalogs
* create manifest with a Binary type
* turn on rich data
* hilarity ensues

### CODE REVIEW

**Comment by Magisus** [comment]
It's not your commit that's failing, seems like it grabbed a bad range (happens sometimes). I'm not sure why there are two Travis runs though... Seems like "push" shouldn't be here.

**Comment by Magisus** [comment]
The appveyor thing is transient. Rekicked.

**Comment by er0ck** [comment]
oh.  maybe because i pushed the branch to `puppetlabs`?  
old habit so anyone can contribute to my branch.  if that's not the right way i can use my fork... next time

**Comment by Magisus** [comment]
Ah yeah, that would probably do it. The range on the "push" travis job must be weird.

**Pull request closed without merging**
