### PR TITLE
(docs) Clarify `period => never`

### PR DESCRIPTION
**Pull request by hestonhoffman**
A Puppet docs site feedback provider asked for clarification on this attribute.

### CODE REVIEW

**Comment by melissa** [comment]
Should we get this into an earlier branch, or is master fine?

**Comment by hestonhoffman** [comment]
I think master is fine. I'll add the note in to 5.5+ manually on our side so they show up on the docs site.

**Comment by melissa** [comment]
What about 6.0 and 6.4?

**Comment by hestonhoffman** [comment]
Yes sorry, I'll elaborate. I'll add it to the docs from 5.5 all the way up to the previous OSP release. So 5.5, 6.0, 6.1, 6.2, and 6.3. These versions of the docs are not generated from the .rb files in this repo.

**Pull request merged**
