### PR TITLE
Revert "(PUP-9324) Ensure logs denote corrective changes"

### PR DESCRIPTION
**Pull request by melissa**
This reverts commit cd4b5d9bfc585ad643fb4d4fb1fc56b0278e0f1b.

### CODE REVIEW

**Comment by melissa** [comment]
I can also pull this out of 6.2.0 once it lands there, if that's easier than removing it here

**Comment by caseywilliams** [comment]
Hmm @melissa that would be fine with me -- I'll leave it up to your team whether to merge this. If not, I'll ping people when it merges up.

**Comment by melissa** [comment]
I think I like the idea of reverting this in the master branch rather than here, that'll mean we don't have to wait for all the merge ups to happen again to get it out of 6.2.0

**Comment by melissa** [comment]
I'll keep an eye on master and open a revert commit once this gets merged up to that branch

**Pull request closed without merging**
