### PR TITLE
(maint) Sort ci:test:quick tests

### PR DESCRIPTION
**Pull request by joshcooper**
Sort ci:test:quick tests in lexicographical order.

```
$ bundle exec rake ci:test:quick
...
    "tests": [
        "tests/direct_puppet/cached_catalog_remediate_local_drift.rb",
        "tests/environment/environment_scenario-default.rb",
        "tests/face/loadable_from_modules.rb",
        "tests/language/functions_in_puppet_language.rb",
        "tests/lookup/hiera3_custom_backend.rb",
        "tests/modules/install/basic_install.rb",
        "tests/node/check_woy_cache_works.rb",
        "tests/parser_functions/calling_all_functions.rb",
        "tests/pluginsync/4420_pluginfacts_should_be_resolvable_on_agent.rb",
        "tests/puppet_apply_basics.rb",
        "tests/resource/file/content_attribute.rb",
        "tests/resource/package/yum.rb",
        "tests/resource/service/puppet_mcollective_service_management.rb",
        "tests/resource/service/ticket_5024_systemd_enabling_masked_service.rb",
        "tests/ssl/puppet_cert_generate_and_autosign.rb",
        "tests/ticket_4622_filebucket_diff_test.rb",
        "tests/utf8/utf8-in-function-args.rb",
        "tests/zzzz_configuration_interpolation.rb"
    ],
    "xml": true,
    "forge_host": "forge-aio01-petest.puppetlabs.com",
    "is_puppetserver": true,
    "use-service": true,
    "puppetservice": "puppetserver",
    "puppetserver-confdir": "/etc/puppetlabs/puppetserver/conf.d",
    "pre_suite": [
        "setup/common/pre-suite/000-delete-puppet-when-none.rb",
        "setup/aio/pre-suite/010_Install.rb",
        "setup/aio/pre-suite/020_InstallCumulusModules.rb",
        "setup/aio/pre-suite/021_InstallAristaModule.rb",
        "setup/common/pre-suite/025_StopFirewall.rb",
        "setup/common/pre-suite/040_ValidateSignCert.rb",
        "setup/aio/pre-suite/045_EnsureMasterStarted.rb"
    ],
    "hosts_file": "/Users/josh/work/puppet/acceptance/hosts.yaml",
    "command_line": "/Users/josh/work/puppet/acceptance/.bundle/ruby/2.2.0/bin/beaker --options-file merged_options.rb --hosts=hosts.yaml --tests=tests/direct_puppet/cached_catalog_remediate_local_drift.rb,tests/environment/environment_scenario-default.rb,tests/face/loadable_from_modules.rb,tests/language/functions_in_puppet_language.rb,tests/lookup/hiera3_custom_backend.rb,tests/modules/install/basic_install.rb,tests/node/check_woy_cache_works.rb,tests/parser_functions/calling_all_functions.rb,tests/pluginsync/4420_pluginfacts_should_be_resolvable_on_agent.rb,tests/puppet_apply_basics.rb,tests/resource/file/content_attribute.rb,tests/resource/package/yum.rb,tests/resource/service/puppet_mcollective_service_management.rb,tests/resource/service/ticket_5024_systemd_enabling_masked_service.rb,tests/ssl/puppet_cert_generate_and_autosign.rb,tests/ticket_4622_filebucket_diff_test.rb,tests/utf8/utf8-in-function-args.rb,tests/zzzz_configuration_interpolation.rb",
...
```

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
👍

**Comment by Magisus** [comment]
Do we want this on the LTS too? Seems weird to change the test ordering on only some of the branches...

**Comment by McdonaldSeanp** [comment]
@Magisus I think we can actually close this, as we resolved the underlying issue that caused us to try this. /cc @joshcooper

**Comment by joshcooper** [comment]
I was thinking sorting the tests would ensure a more consistent test environment, so we don't get random order-dependent test failures when running `ci:test:quick`, but not when running `ci:test:aio`. Agree about targeting for LTS-1.7, that would be weird to get different behavior across branches.

**Comment by branan** [comment]
I agree that this is useful even without a known ordering issue, and with the LTS re-target.

**Comment by Magisus** [comment]
I'm with Josh on this one too.

**Comment by joshcooper** [comment]
k, let me close this out and open a new PR targeted at LTS-1.7

**Pull request closed without merging**
