### PR TITLE
{WIP}Merge branch '4.10.x' into 5.0.x

### PR DESCRIPTION
**Pull request by glennsarti**
Merge branch '4.10.x' into 5.0.x

### CODE REVIEW

**Comment by Iristyle** [comment]
I'm not sure this is merging up to the correct branch... and it looks out of date.

**Comment by glennsarti** [comment]
so should be going to 5.2.x?  Docs say 4.10 -> 5.0 -> 5.1 -> 5.2

**Comment by glennsarti** [comment]
also the merge up to 5.2 is even worse.

**Comment by branan** [comment]
5.0.x, 5.1.x, and 5.2.x are not getting any new releases, and we should probably just delete those branches. 4.10.x should be merged up to 5.3.x (And then master) if that's not current.

**Comment by branan** [comment]
Whoops, didn't mean to close. 4.10->5.3 does look like a much cleaner merge-up than this, at least

**Comment by glennsarti** [comment]
ok..Closing for now.

**Pull request closed without merging**
