### PR TITLE
(maint) Merge branch 6.x into main

### PR DESCRIPTION
**Pull request by mihaibuzgau**
puppetlabs/6.x:
*  (docs) mark documentation examples as source code
*  (maint) stub Facter request to external services

 Conflicts:
*	spec/spec_helper.rb

### CODE REVIEW

**Review by joshcooper — APPROVED** [review]

**Comment by GabrielNagy** [comment]
I think the OpenSSL version may have changed on the GH Actions Ubuntu workers, which causes that spec to fail.

**Comment by GabrielNagy** [comment]
Passing: https://github.com/puppetlabs/puppet/runs/2131250735 (OpenSSL Library Version - OpenSSL 1.1.1j  16 Feb 2021)
Failing: https://github.com/puppetlabs/puppet/pull/8544/checks?check_run_id=2140754928 (OpenSSL Library Version - OpenSSL 1.1.1  11 Sep 2018)

**Comment by luchihoratiu** [comment]
Not a lot of options for workarounds by default:
```
> runner@fv-az65-464:~/openssl$ openssl version
OpenSSL 1.1.1  11 Sep 2018
> runner@fv-az65-464:~/openssl$ apt list -a openssl
Listing... Done
openssl/bionic-updates,bionic-security,now 1.1.1-1ubuntu2.1~18.04.8 amd64 [installed]
openssl/bionic 1.1.0g-2ubuntu4 amd64
```

**Comment by GabrielNagy** [comment]
Looks like reinstalling openssl should get us back to the newer version: https://github.com/actions/virtual-environments/issues/2977#issuecomment-802170811

However, it would be good to (try to) make the test work regardless of OpenSSL version.

**Comment by joshcooper** [comment]
I'll update the test.

**Comment by GabrielNagy** [comment]
So we were somehow getting a newer openssl version through a third-party PPA which was removed from the Ubuntu image, and now we're back to the stock version that ships with 18.04.

**Pull request merged**
