### PR TITLE
(PUP-4503, PUP-2023) Debian for systemd

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by sathieu** [comment]
Note that this is not sufficient, because both "debian" dans 'systemd' provider are default. How can I do an "confine :noexists => "/run/systemd/system" in the debian provider ?

**Comment by sathieu** [comment]
The double default provider is fixed in revision 2

**Comment by sathieu** [comment]
NB: there is still this bug to be solved: https://bugs.debian.org/751638

**Comment by leepa** [comment]
This change won't work for the reasons stated on PUP-4503 and the version attached in the Gist on that ticket is probably best until the Puppetlabs guys solve it.

The Debian bug is unlikely to be fixed anytime soon. Shown by the fact it's a year old and during the RCs they didn't fix it.

Please don't merge this change.

**Comment by melissa** [comment]
Closed in favor of https://github.com/puppetlabs/puppet/pull/3916

**Pull request closed without merging**
