### PR TITLE
(PUP-5545) Remove non-existent rake task

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
This was merged with a rake task that will not exist. This is meant to fix that.

**Comment by ghoneycutt** [comment]
@andersonmills This is a fix to the PR that you merged regarding rubucop. Could you take a look as this needs to be merged quick.

**Comment by MikaelSmith** [comment]
👍

**Comment by ghoneycutt** [comment]
Thanks @MikaelSmith

**Pull request merged**
