### PR TITLE
(maint) test Travis on Ruby >= 2.0

### PR DESCRIPTION
**Pull request by mihaibuzgau**
Travis has changed the base docker container used for "ruby" based builds.
A few days ago they changed from Ubuntu 14.04.5 LTS to Ubuntu 16.04.6 LTS. 

Even thou Ubuntu 16.04.6 LTS has /bin/systemctl executable, it is not suitable for the systemd provider because systemd is not started as pid 1.

Test for testing if a platform is suitable for systemd provider were added here: https://github.com/puppetlabs/puppet/pull/7628

This PR removes old tests.

### CODE REVIEW

**Comment by mihaibuzgau** [comment]
`rvm use 1.9.3 --install --binary --fuzzy` is not working on an ubuntu:16.04 docker container:
```
root@18ec478285ba:/# rvm use 1.9.3 --install --binary --fuzzy
Required ruby-1.9.3 is not installed - installing.
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm ruby-1.9.3 do rvm gemset create ' first, or append '--create'.
```

this used to work on ubuntu:14.04:
```
@eafa0d5860dc:/# rvm use 1.9.3 --install --binary --fuzzy
Required ruby-1.9.3-p551 is not installed - installing.
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/14.04/x86_64/ruby-1.9.3-p551.tar.bz2
Checking requirements for ubuntu.
Installing requirements for ubuntu.
Updating system...
Installing required packages: patch, gawk, g++, gcc, autoconf, automake, bison, libc6-dev, libffi-dev, libgdbm-dev, libncurses5-dev, libsqlite3-dev, libtool, libyaml-dev, make, patch, pkg-config, sqlite3, zlib1g-dev, libgmp-dev, libreadline6-dev, libssl-dev..............................
Requirements installation successful.
ruby-1.9.3-p551 - #configure
ruby-1.9.3-p551 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.3M  100 13.3M    0     0  4307k      0  0:00:03  0:00:03 --:--:-- 4308k
ruby-1.9.3-p551 - #validate archive
ruby-1.9.3-p551 - #extract
ruby-1.9.3-p551 - #validate binary
ruby-1.9.3-p551 - #setup
ruby-1.9.3-p551 - #gemset created /usr/local/rvm/gems/ruby-1.9.3-p551@global
ruby-1.9.3-p551 - #importing gemset /usr/local/rvm/gemsets/global.gems............................................
ruby-1.9.3-p551 - #generating global wrappers.......
ruby-1.9.3-p551 - #gemset created /usr/local/rvm/gems/ruby-1.9.3-p551
ruby-1.9.3-p551 - #importing gemsetfile /usr/local/rvm/gemsets/default.gems evaluated to empty gem list
ruby-1.9.3-p551 - #generating default wrappers.......
Using /usr/local/rvm/gems/ruby-1.9.3-p551
```

**Comment by mihaibuzgau** [comment]
Updated PR to also remove the build on Ruby 1.9.3. 
Ruby 1.9.3 was `end of life` on the 23rd of Feb 2015: https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

In order to make RVM install ruby 1.9.3 on ubuntu:16.04 container, we need to:
```
rvm pkg install openssl
rvm install 1.9.3 -C --with-openssl-dir=$HOME/.rvm/usr
```
increasing the test time by ~ 5 minutes.

**Comment by jtappa** [comment]
This seems sane to me, but I'm not sure if there are still other 5.5.x projects dependent on this one testing in Ruby 1.9.3. I seem to recall something in server needing this a while back? ping @Magisus or maybe @justinstoller would know

**Comment by kris-bosland** [comment]
@mihaibuzgau , I think there is a hard dependency for Puppet 5.5.x on JRuby (for server) for a 1.9.x ruby.

**Comment by mihaibuzgau** [comment]
closing in favor of: https://github.com/puppetlabs/puppet/pull/7650

**Pull request closed without merging**
