### PR TITLE
(PUP-9974) allow_virtual set to true matches too much for dpkg

### PR DESCRIPTION
**Pull request by loopinu**

### CODE REVIEW

**Comment by loopinu** [comment]
please do not merge yet, there are still some tests that need work.

**Comment by loopinu** [comment]
Jenkins, please test this on all!

**Comment by loopinu** [comment]
jenkins please test this on all

**Comment by GabrielNagy** [comment]
jenkins please test this

**Comment by loopinu** [comment]
closing this PR due to revert of the feature

**Pull request closed without merging**
