### PR TITLE
(PUP-3802) Fix yaourt on Arch linux.

### PR DESCRIPTION
**Pull request by wiccan2**

### CODE REVIEW

**Comment by jhelwig** [comment]
Thanks for the submission!

Unfortunately, I don't think this is quite doing what's intended. It looks like it's intending to prepend `/usr/bin/sudo -S -u nobody` to the command that gets run, however it's unshifting on to `cmd` after the command has already been run by `yaourt *cmd` on the previous line (The `yaourt` method is created by the `commands :yaourt => "/usr/bin/yaourt" if yaourt?` earlier in the file, and runs `/usr/bin/yaourt` via `Puppet::Util::Execution.execute`). Since `cmd` is the arguments passed to `/usr/bin/yaourt`, it can't be used to run `/usr/bin/yaourt` using sudo, and `cmd` is supposed to be already split into individual arguments, so there wouldn't be any parsing of "`/usr/bin/sudo -S -u nobody`" by the shell.

We'd need to use the [`execute` method](https://github.com/puppetlabs/puppet/blob/7d6318c212c595fa05662e08fbc474af2ea95663/lib/puppet/provider.rb#L98-L107) directly to run the command, instead of using the `yaourt` helper to be able to run `yaourt` under `sudo`. Hard-coding the user to `nobody` also feels like we shouldn't be doing that, and instead should be exposing that as something that can be set (though defaulting to `nobody` seems entirely reasonable).

**Comment by wiccan2** [comment]
@jhelwig Thanks for that explanation.

I'm still getting used to Ruby and that syntax is clearly doing something quite different to what I assumed it was.

Looking deeper into the code I can now see how the method is being constructed and how cmd is the list of arguments to be passed.

With some rework I reckon I can get this working correctly. 

I will take a look tonight at what I can do.

The thing that puzzles me is how this seemed to work in my Vagrant box, knowing the syntax now; there is no way it could have ever worked. I will have to take a look into that.

**Comment by wiccan2** [comment]
So my mistake in testing seemed to be that I didn't run puppet as root. Thus yaourt was executing as the vagant user anyway.

After reworking my entire approach and running my tests as root it seems to work.

The test for this are failing however. From what I can tell its because I am using `Puppet::Util::Execution.execute` directly and the test is not expecting this to happen.

Can anyone offer some help in modifying the tests?

**Comment by wiccan2** [comment]
I'm having some trouble replicating the test results, mine are coming up different. There is obviously something up with my environment. I'm getting issues with temporary files not being writable:

```
Puppet::ExecutionFailure:
       Execution of '/usr/bin/yaourt --noconfirm --noprogressbar -R package' returned 1: ==> ERROR: /tmp/rspecrun20180310-11742-1twohxi is not writable
```

I'm note quite sure what is causing this. Permissions on the tmp folder seem to be correct and I am running as root. The results I get are completely different to the ones in travis. Any help in getting me set up to work on this properly would be greatly appreciated.

I'm currently running in a clean ArchLinux vagrant box with latest ruby. I do a bundle install before running the tests.

<details>
 <summary>Full rspec output:</summary>

```
[root@archlinux puppet]# bundle exec rake spec TEST=spec/unit/provider/package/pacman_spec.rb 
rspec spec/unit/provider/package/pacman_spec.rb
Run options: exclude {:broken=>true, :benchmark=>true}
.F....F........F..........................

Failures:

  1) Puppet::Type::Package::ProviderPacman when installing should call yaourt to install the right package quietly when yaourt is installed
     Failure/Error: raise Puppet::ExecutionFailure, _("Execution of '%{str}' returned %{exit_status}: %{output}") % { str: command_str, exit_status: exit_status, output: output.strip }
     
     Puppet::ExecutionFailure:
       Execution of '/usr/bin/yaourt --noconfirm --needed --noprogressbar -Sy package' returned 1: ==> ERROR: /tmp/rspecrun20180310-11742-1twohxi is not writable
     # ./lib/puppet/util/execution.rb:285:in `execute'
     # ./lib/puppet/provider/package/pacman.rb:270:in `install_from_repo'
     # ./lib/puppet/provider/package/pacman.rb:46:in `install'
     # ./spec/unit/provider/package/pacman_spec.rb:39:in `block (3 levels) in <top (required)>'

  2) Puppet::Type::Package::ProviderPacman when installing and install_options are given should call yaourt to install the right package quietly when yaourt is installed
     Failure/Error: raise Puppet::ExecutionFailure, _("Execution of '%{str}' returned %{exit_status}: %{output}") % { str: command_str, exit_status: exit_status, output: output.strip }
     
     Puppet::ExecutionFailure:
       Execution of '/usr/bin/yaourt --noconfirm --needed --noprogressbar -x --arg=value -Sy package' returned 1: ==> ERROR: /tmp/rspecrun20180310-11742-1twohxi is not writable
     # ./lib/puppet/util/execution.rb:285:in `execute'
     # ./lib/puppet/provider/package/pacman.rb:270:in `install_from_repo'
     # ./lib/puppet/provider/package/pacman.rb:46:in `install'
     # ./spec/unit/provider/package/pacman_spec.rb:81:in `block (4 levels) in <top (required)>'

  3) Puppet::Type::Package::ProviderPacman when uninstalling should call yaourt to remove the right package quietly
     Failure/Error: raise Puppet::ExecutionFailure, _("Execution of '%{str}' returned %{exit_status}: %{output}") % { str: command_str, exit_status: exit_status, output: output.strip }
     
     Puppet::ExecutionFailure:
       Execution of '/usr/bin/yaourt --noconfirm --noprogressbar -R package' returned 1: ==> ERROR: /tmp/rspecrun20180310-11742-1twohxi is not writable
     # ./lib/puppet/util/execution.rb:285:in `execute'
     # ./lib/puppet/provider/package/pacman.rb:213:in `uninstall'
     # ./spec/unit/provider/package/pacman_spec.rb:181:in `block (3 levels) in <top (required)>'

Finished in 16.91 seconds (files took 39.25 seconds to load)
42 examples, 3 failures

Failed examples:

rspec ./spec/unit/provider/package/pacman_spec.rb:35 # Puppet::Type::Package::ProviderPacman when installing should call yaourt to install the right package quietly when yaourt is installed
rspec ./spec/unit/provider/package/pacman_spec.rb:77 # Puppet::Type::Package::ProviderPacman when installing and install_options are given should call yaourt to install the right package quietly when yaourt is installed
rspec ./spec/unit/provider/package/pacman_spec.rb:177 # Puppet::Type::Package::ProviderPacman when uninstalling should call yaourt to remove the right package quietly

rake aborted!
Command failed with status (1): [rspec spec/unit/provider/package/pacman_sp...]
/vagrant/puppet-src/puppet/Rakefile:67:in `block in <top (required)>'
Tasks: TOP => spec
(See full trace by running task with --trace)

```

</details>

**Comment by melissa** [comment]
@puppetlabs/platform-os could y'all take a look at this PR?

**Comment by jhelwig** [comment]
As it is, the test failures would definitely need to be fixed first at a minimum. @puppetlabs/platform-os may have input as to how to get that sorted out. I don't know if they may also have more general comments on the PR.

**Comment by jtappa** [comment]
Could someone from @puppetlabs/platform-os take a look at this?

**Comment by joshcooper** [comment]
ping @mihaibuzgau

**Comment by GabrielNagy** [comment]
Honestly, I'd rather drop `yaourt` entirely and switch to `yay` or something that's still maintained/in active development. Yaourt is not even mentioned anymore on the [AUR helpers](https://wiki.archlinux.org/index.php/AUR_helpers) wiki page and many users have complained about security issues regarding it.

@wiccan2, are you up for that?

**Comment by GabrielNagy** [comment]
As outlined in the ticket, I'm closing this. Possible ways to proceed from here:
- entirely remote `yaourt` support
- change to a maintained AUR helper such as `yay`

**Pull request closed without merging**
