### PR TITLE
(PUP-5554) Improve parser performance on JRuby

### PR DESCRIPTION
**Pull request by thallgren**
This PR contains two commits. One that optimizes the lexer and one that optimizes the parser
factory. The measurements that I've done indicates that when this PR is applied, parsing will spend:

55% less CPU time with JRuby (tested using JRuby 9.0.4)
13% less CPU time with MRI (tested on 1.9.3, 2.1.1, and 2.2.1).

The parser is 11% faster with MRI than with JRuby.

### CODE REVIEW

**Comment by hlindberg** [comment]
Nicely done - I guess the breaking up into lambdas makes it possible for the JRuby implementation to optimize the logic. How did you measure the performance gain? Did you run the rake benchmarks - -there is one for language constructs IIRC. Worth checking so not optimizing for only one case (and possibly regressing elsewhere).

**Comment by thallgren** [comment]
Performance was measured using the files attached to [SERVER-993](https://tickets.puppetlabs.com/browse/SERVER-993). The site.pp contains 1000 nodes and each node includes about 50 of the most common forge modules. I measured the time by parsing the site 50 times in sequence (to give JIT some time to kick in) using the `doparse.rb`script attached in one of the comments.

I can try the rake tests as well but I don't think they will give us more accurate benchmarks.

**Comment by thallgren** [comment]
Some sample runs of benchmark:evaluations:

JRuby on master
```
$ bundle exec rake benchmark:evaluations
                 user     system      total        real
Run 1       20.130000   0.110000  20.240000 (  5.350424)
Run 2        4.810000   0.010000   4.820000 (  3.004732)
Run 3        3.730000   0.000000   3.730000 (  2.856813)
Run 4        3.460000   0.010000   3.470000 (  2.816691)
Run 5        2.980000   0.010000   2.990000 (  2.763458)
Run 6        3.320000   0.000000   3.320000 (  2.764022)
Run 7        3.900000   0.010000   3.910000 (  2.766820)
Run 8        3.780000   0.010000   3.790000 (  2.718905)
Run 9        3.310000   0.010000   3.320000 (  2.697132)
Run 10       3.210000   0.000000   3.210000 (  2.730446)
> total:    52.630000   0.170000  52.800000 ( 30.469443)
> avg:       5.263000   0.017000   5.280000 (  3.046944)
```
JRuby using the branch of this PR:
```
$ bundle exec rake benchmark:evaluations
                 user     system      total        real
Run 1       19.140000   0.090000  19.230000 (  4.335367)
Run 2        4.680000   0.010000   4.690000 (  2.061136)
Run 3        2.640000   0.010000   2.650000 (  1.901571)
Run 4        2.500000   0.000000   2.500000 (  1.855599)
Run 5        1.920000   0.000000   1.920000 (  1.829496)
Run 6        2.400000   0.000000   2.400000 (  1.819275)
Run 7        2.610000   0.010000   2.620000 (  1.782573)
Run 8        2.630000   0.000000   2.630000 (  1.828947)
Run 9        2.120000   0.010000   2.130000 (  1.736646)
Run 10       2.110000   0.000000   2.110000 (  1.724908)
> total:    42.750000   0.130000  42.880000 ( 20.875518)
> avg:       4.275000   0.013000   4.288000 (  2.087552)
```

MRI 1.9.3 on master
```
$ bundle exec rake benchmark:evaluations
                 user     system      total        real
Run 1        1.860000   0.000000   1.860000 (  1.860966)
Run 2        1.760000   0.000000   1.760000 (  1.768686)
Run 3        1.630000   0.000000   1.630000 (  1.625058)
Run 4        1.620000   0.000000   1.620000 (  1.627215)
Run 5        1.630000   0.000000   1.630000 (  1.628099)
Run 6        1.620000   0.000000   1.620000 (  1.627440)
Run 7        1.660000   0.000000   1.660000 (  1.663523)
Run 8        1.630000   0.000000   1.630000 (  1.629413)
Run 9        1.620000   0.000000   1.620000 (  1.626921)
Run 10       1.630000   0.000000   1.630000 (  1.636595)
> total:    16.660000   0.000000  16.660000 ( 16.693916)
> avg:       1.666000   0.000000   1.666000 (  1.669392)
```
MRI 1.9.3 using the branch of this PR:
```
$ bundle exec rake benchmark:evaluations
                 user     system      total        real
Run 1        1.710000   0.000000   1.710000 (  1.714156)
Run 2        1.660000   0.000000   1.660000 (  1.664765)
Run 3        1.490000   0.000000   1.490000 (  1.485823)
Run 4        1.460000   0.000000   1.460000 (  1.468151)
Run 5        1.470000   0.000000   1.470000 (  1.470141)
Run 6        1.470000   0.000000   1.470000 (  1.468857)
Run 7        1.470000   0.000000   1.470000 (  1.469285)
Run 8        1.470000   0.000000   1.470000 (  1.470895)
Run 9        1.470000   0.000000   1.470000 (  1.469168)
Run 10       1.470000   0.000000   1.470000 (  1.469197)
> total:    15.140000   0.000000  15.140000 ( 15.150439)
> avg:       1.514000   0.000000   1.514000 (  1.515044)
```

**Comment by thallgren** [comment]
The rake tests are very misleading since the JIT doesn't come into play very much. In fact, I just noticed that when running 100 iterations of the tests that I ran earlier, the JIT really kicks in after 150 seconds (or about 50 iterations, so unnoticed in prior reports). When it does, the parser performance is par with using the MRI.

**Comment by thallgren** [comment]
Superseded by #4476.

**Pull request closed without merging**
