### PR TITLE
(PUP-9198) Add RHEL8 support in the dnf provider

### PR DESCRIPTION
**Pull request by mwhahaha**
dnf should be the default for RHEL8

### CODE REVIEW

**Comment by EmilienM** [comment]
ping @hunner Hey Hunter :-) do you know anyone who can quickly help here? it's urgent on our side. Thanks a ton!

**Comment by melissa** [comment]
@EmilienM if it's urgent, you can always set the provider to dnf for those systems https://puppet.com/docs/puppet/6.0/types/package.html#package-attribute-provider

**Comment by EmilienM** [comment]
@melissa I know I could do that but I hope a single line patch, that simple, could land quickly but it doesn't seem to be the case.

**Comment by kris-bosland** [comment]
@EmilienM , we recently added a feature to blacklist defaults (notdefaultfor).  If RHEL is planning to be DNF going forward, please use this feature to exclude older RHEL versions so that this file will not need to change with each new release.  See the fedora entry for an example.  Thanks!

**Comment by mwhahaha** [comment]
Does it work in 5.x?  Our current target is not 6.x

**Comment by mwhahaha** [comment]
@kris-bosland Ok I can do both. Wasn't sure how backports are handled in puppet.

**Comment by kris-bosland** [comment]
Thanks @mwhahaha .  I am guessing that by 'both' you mean a PR for 5.5.x and a PR for 6.0.x.  If you do that, please merge your 5.5.x commit into 6.0.x as part of your 6.0.x PR.

**Comment by mwhahaha** [comment]
@kris-bosland ok so i've got this targeted to 5.5.x. What's the best way to handle the 6.0.x patch. You said merge this into 6.0.x, is there a specific way that is traditionally done for the puppet code base?

**Comment by melissa** [comment]
@mwhahaha thanks for retargeting this! Could you also add some tests for this addition?

**Comment by mwhahaha** [comment]
@melissa done

**Comment by mwhahaha** [comment]
I have opened https://github.com/puppetlabs/puppet/pull/7211 for the 6.0.x branch

**Pull request merged**
