### PR TITLE
(maint) Update internal test forge URI

### PR DESCRIPTION
**Pull request by caseywilliams**
Analogous to https://github.com/puppetlabs/puppet-agent/pull/1470

### CODE REVIEW

**Comment by melissa** [comment]
jenkins please test this on amazon7-64 with agent 5.5.x

**Comment by joshcooper** [comment]
@caseywilliams is this still needed?

**Comment by caseywilliams** [comment]
@joshcooper thanks for the ping! This isn't absolutely necessary anymore, since the redirect is working fine, but it couldn't hurt to merge, since this URL is the real one now.

**Comment by joshcooper** [comment]
jenkins please test this on amazon7-64a,windows2012r2-64a with agent 5.5.x

**Pull request merged**
