### PR TITLE
(PUP-3116) Optimize the read of the system mounts in selinux

### PR DESCRIPTION
**Pull request by trevor-vaughan**
Util::SELinux currently reads /proc/mounts for each file in the system.

This can cause a massive lag/burden on the system especially if the
system uses a great number of mount entries (such as OpenShift).

However, this is not a great patch since it creates a global variable
insted of using whatever global caching mechanism that Puppet may have
internally.

Submitting for review but hoping for improvement.

### CODE REVIEW

**Comment by joshcooper** [comment]
PR Triage Notes

* Waiting for @peiriannydd to update PR based on puppet-dev conversation.

**Comment by ScottGarman** [comment]
@peiriannydd ping?

**Comment by peiriannydd** [comment]
Sorry all, I'm going to have to take some additional time to concentrate on this and not make a mess of the internal memory. I suppose I was hoping that someone would magically throw a global queue in here that I could use :-D.

**Comment by joshcooper** [comment]
@peiriannydd thank you for your contribution! We're in agreement that we need a mechanism for providers to store state during the catalog application. A simple example might be for puppet to push an `provider_data` hash using puppet's context system:

```
provider_data = {}
Puppet.override(:provider_data => provider_data) do
  # apply the catalog
end
```

We do something similar for the HTTP connection pool. You could then access the cache in your provider:

```
data = Puppet.lookup(:provider_data)
data[:selinux] = read_mounts
```

But yes, namespacing is an issue. I can imagine cases where you want to store class-level provider data, but I can also see where selinux contexts might need to be accessed from multiple providers, not just the file provider.

There is also the issue the cache might contain more than just data, e.g. file descriptors, and we'd want to makes sure those things were closed after the catalog is applied. We can do that with HTTP connections, because it's internal data, but it's less clear about how that would work with arbitrary provider data. Likely, data would need implement a marker interface, e.g. `disposable`, and have puppet call that during cleanup.

I think more design work is required to the provider API to make this happen. It might be better to create a new ticket for that, and mark this ticket as blocked on that one. That way it's clearer that the crux of the issue is being able to share state across resources, as opposed to selinux itself.

**Comment by peiriannydd** [comment]
@joshcooper What you're saying about the provider data is really spot on I think.

How about automatically creating a namespace based on the provider namespace? In theory, it has to be globally unique anyway.

So,  Puppet::Type.type(:super_awesome).provide(:things) would create provider_data[:super_awesome__things] as a standard unique namespace.

Adding a bit of sugar with something like a 'provider_data' variable automatically pulling the contents of that namespace would save a great deal of confusion.

Perhaps, there would also be a space for explicitly global data (provider_data[:global]?) that also makes things well understood.

I think that using a marker interface is fine but it's definitely going to be missed and/or ignored but I don't think that should stop anything.

Perhaps very obvious objects (filehandles) could just be closed when the object is destroyed by running through the object. As horrible as it might be: thing.respond_to?(:close) && thing.close. (Yes, I realize the potential horrible implications of this).

**Comment by kylog** [comment]
@joshcooper @peiriannydd logistics: should we close this PR for now and open a PUP ticket for the general facility discussed above?

**Comment by peiriannydd** [comment]
Please don't. If you could link the tickets, I'll pick this up with a re-implementation once the facility is in place (or someone else can).

I just don't want this to get lost since it can produce adverse system effects quite badly.

**Comment by kylog** [comment]
Okey doke, we can leave this PR open.

Jira-wise I added https://tickets.puppetlabs.com/browse/PUP-4002 for the general facility, and made that a blocker for PUP-3116.

**Comment by hlindberg** [comment]
Here is one way of dealing with additional data and caches: http://puppet-on-the-edge.blogspot.se/2014/02/puppet-internals-adapter-pattern.html - using the adapter pattern makes sure different aspects does not clash and it makes the adapter contents have the same lifecycle as what it adapts. Adapters can be more specific in their purpose than acting as a general cache; this is beneficial since it can have a concrete API. Also the implementation does not rely on some common cache feature which needs to be well specified and maintained. Instead it is a private concern and much easier to deal with. This approach is used in data-in-modules where cached data is either associated with the environment or the compiler depending on how long the data should live.

**Comment by hkenney** [comment]
@trevor-vaughan Hey it's been a few months, are you still interested in working on this issue? Just checking in.

**Comment by trevor-vaughan** [comment]
I'm interested in working on it and, of course, interested in having it
worked (if someone else wants to do it +1).

Just been too busy to devote any time to it.

Thanks,

Trevor

On Mon, Jul 20, 2015 at 2:34 PM, Hailee Kenney <notifications@github.com>
wrote:

> @trevor-vaughan <https://github.com/trevor-vaughan> Hey it's been a few
> months, are you still interested in working on this issue? Just checking in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/puppetlabs/puppet/pull/3043#issuecomment-122980341>.
>



-- 
Trevor Vaughan
Vice President, Onyx Point, Inc
(410) 541-6699

-- This account not approved for unencrypted proprietary information --

**Comment by joshcooper** [comment]
Hey @trevor-vaughan, so this PR has been open for over a year, it's blocked on PUP-4002, which we just haven't had time to investigate. Can we close this PR and reopen when it's actionable?

**Comment by trevor-vaughan** [comment]
Sure, why not. I'm not a huge fan of closing things that aren't closed
because we'll all forget about it, but I certainly understand it.

On Tue, Sep 15, 2015 at 2:01 PM, Josh Cooper <notifications@github.com>
wrote:

> Hey @trevor-vaughan <https://github.com/trevor-vaughan>, so this PR has
> been open for over a year, it's blocked on PUP-4002, which we just haven't
> had time to investigate. Can we close this PR and reopen when it's
> actionable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/puppetlabs/puppet/pull/3043#issuecomment-140484013>.
>



-- 
Trevor Vaughan
Vice President, Onyx Point, Inc
(410) 541-6699

-- This account not approved for unencrypted proprietary information --

**Comment by joshcooper** [comment]
@trevor-vaughan sounds good, closing for now. If you're coming to puppetconf, it would be good to catch up about this, as I imagine many providers would like to be able to store state during a run, and do so in a way that doesn't require puppet hacks.

**Comment by GertjanBijl** [comment]
No movement on [PUP-4002](https://tickets.puppetlabs.com/browse/PUP-4002) in the last 8 years, and Puppet runs are still insanely slow on machines with loads of mounts. Any way to speed up the process somewhere?

**Pull request closed without merging**
