### PR TITLE
(maint) Remove expectation of failure in direct puppet cache test

### PR DESCRIPTION
**Pull request by whopper**
The first of these commits adds a new static catalog helper in lib/acceptance, abstracted away from the original direct puppet from cache test.

The second commit corrects an error with the `versioned-code` puppetserver.conf settings and removes the `expect_failure` from the test.

Tested in Centos and windows, both pass.

/cc @MikaelSmith @joshcooper

### CODE REVIEW

**Comment by MikaelSmith** [comment]
:+1:

**Comment by whopper** [comment]
ack, messed up a rebase. One sec

**Comment by MikaelSmith** [comment]
Yeah, where'd the augeas commit come from?

**Comment by whopper** [comment]
@MikaelSmith augeas thing was a PR merged yesterday, accidentally did an interactive rebase of the last 3 commits, somehow that ended up in here (even though that commit is already in master). Should be good now.

**Pull request merged**
