### PR TITLE
(PUP-10104) Puppet device ssl oids

### PR DESCRIPTION
**Pull request by JonasVerhofste**
Not sure if I'd need some other tests, will gladly add them if necessary.

### CODE REVIEW

**Comment by JonasVerhofste** [comment]
Let's give that second commit a more meaningful title too..

**Comment by joshcooper** [comment]
Thanks for your contribution @JonasVerhofste! Could you squash the commits?

**Comment by JonasVerhofste** [comment]
Oh, sure! Assumed you guys would want tests and actual code in different commits, but if you don't, no probs.

**Comment by JonasVerhofste** [comment]
@joshcooper There you go :)

**Comment by joshcooper** [comment]
Thanks for your contribution @JonasVerhofste, this will be released in the 6.11.0 release!

**Pull request merged**
