### PR TITLE
(lol) Add more clear alias for :latest pkg ensure

### PR DESCRIPTION
**Pull request by adrienthebo**
"When you can't move fast and break things" (http://lanyrd.com/2015/cfgmgmtcamp/sdhgcz/)

```puppet
package { 'puppet':
  ensure => yolo,
}
```

### CODE REVIEW

**Comment by daenney** [comment]
:+1:

**Comment by ferventcoder** [comment]
Ha!

**Comment by ScottGarman** [comment]
Ship it!

**Comment by kylog** [comment]
:100: 

This will dovetail nicely with the `ensure => chaos` PR I'll be pushing up soon, which selects a random package version.

**Comment by mckern** [comment]
If you write a unit test for this value and a better commit message, I will merge this. I'll do it. Don't think I won't.

**Comment by shrug** [comment]
vlcsnap-2011-02-20-02h12m23s2221

**Comment by heathseals** [comment]
:+1:

**Comment by kylog** [comment]
Can this be restructured to be a breaking change? Perhaps we retire `latest`? Naturally, for consistency reasons, we should introduce this breaking change in a Z release.

**Comment by ferventcoder** [comment]
@kylog :trollface:

**Comment by AndrewWest** [comment]
Ironic

**Comment by daenney** [comment]
Some times, a couple of years from now, someone will run into this code in the Puppet code base and look back on this and go "those fuckers".

**Comment by ferventcoder** [comment]
I love that this was triaged.

**Comment by ferventcoder** [comment]
And more importantly, left open...

**Comment by petems** [comment]
The green button calls to me, so tempting...

**Comment by daenney** [comment]
It needs at least a spec before we go green button.

**Comment by ffrank** [comment]
Folks. People. 

Can we please agree that what happens in Belgium stays in Belgium? (That goes double for @adrienthebo, geddit?)

**Comment by petems** [comment]
Well, if anyone wants a spec, this seems to work ;)

```ruby
describe Puppet::Type.type(:package), "when validating attribute values" do
  before do
    @provider = stub 'provider', :class => Puppet::Type.type(:package).defaultprovider, :clear => nil
    Puppet::Type.type(:package).defaultprovider.stubs(:new).returns(@provider)
    @provider.expects(:satisfies?).with([:versionable]).returns true
  end

  it "should support :yolo as a value to :latest" do
    Puppet::Type.type(:package).new(:name => "yay", :ensure => :yolo)
  end
end
```

**Comment by petems** [comment]
Actually, I'm not sure that works, but vaguely close :+1:

**Comment by adrienthebo** [comment]
I love you guys. Again, great talk @MosesMendoza it was really inspiring. ;)

**Comment by MosesMendoza** [comment]
:)

**Comment by daenney** [comment]
:sob:

**Pull request closed without merging**
