### PR TITLE
(PUP-9265) Revert PUP-6542, implement it in a different way, and fix AIX group provider

### PR DESCRIPTION
**Pull request by ekinanp**

### CODE REVIEW

**Comment by ekinanp** [comment]
jenkins please test this on windows10ent-64a,windows10ent-32a,windows2008r2-64a,windows2012r2-64a,windows2012r2_ja-64a%7Blocale=ja%7D,windows2016-64a,aix71-POWERfa,osx1012-64a

**Comment by ekinanp** [comment]
jenkins please test this on windows10ent-64a,windows10ent-32a,windows2008r2-64a,windows2012r2-64a,windows2012r2_ja-64a%7Blocale=ja%7D,windows2016-64a,aix71-POWERfa,osx1012-64a

**Comment by ekinanp** [comment]
I don't have any acceptance tests for reporting the right change notification since I think that's something which can be verified from manual inspection instead of requiring some complex and fragile regex matching logic. Looking at the PR testing output, we have the following for each of the tested platforms:

WINDOWS:
```
  * Verify that Puppet enforces minimum user membership when auth_membership == false
    
    p13qvtljw4kkahw.delivery.puppetlabs.net (p13qvtljw4kkahw.delivery.puppetlabs.net) 01:42:34$ cygpath -m $(mktemp -t apply_manifest.pp.XXXXXX)
      C:/cygwin64/tmp/apply_manifest.pp.F4CzU3
    
    p13qvtljw4kkahw.delivery.puppetlabs.net (p13qvtljw4kkahw.delivery.puppetlabs.net) executed in 0.31 seconds
    localhost $ scp /tmp/beaker20181027-348-1vgyk83 p13qvtljw4kkahw.delivery.puppetlabs.net:C:/cygwin64/tmp/apply_manifest.pp.F4CzU3 {:ignore => }
    
    p13qvtljw4kkahw.delivery.puppetlabs.net (p13qvtljw4kkahw.delivery.puppetlabs.net) 01:42:35$ cmd.exe /c puppet apply --verbose C:/cygwin64/tmp/apply_manifest.pp.F4CzU3
      Notice: Compiled catalog for p13qvtljw4kkahw.delivery.puppetlabs.net in environment production in 0.02 seconds
      Info: Applying configuration version '1540604557'
      Notice: /Stage[main]/Main/Group[pl787716]/members: members changed P13QVTLJW4KKAHW\pl164231,P13QVTLJW4KKAHW\pl64140 to P13QVTLJW4KKAHW\pl164231,P13QVTLJW4KKAHW\pl64140,P13QVTLJW4KKAHW\pl507478,P13QVTLJW4KKAHW\pl652124
      Notice: Applied catalog in 1.09 seconds

....

  * Verify that Puppet enforces inclusive user membership when auth_membership == true
    
    p13qvtljw4kkahw.delivery.puppetlabs.net (p13qvtljw4kkahw.delivery.puppetlabs.net) 01:43:01$ cygpath -m $(mktemp -t apply_manifest.pp.XXXXXX)
      C:/cygwin64/tmp/apply_manifest.pp.VIHO1N
    
    p13qvtljw4kkahw.delivery.puppetlabs.net (p13qvtljw4kkahw.delivery.puppetlabs.net) executed in 0.31 seconds
    localhost $ scp /tmp/beaker20181027-348-1vxzm6 p13qvtljw4kkahw.delivery.puppetlabs.net:C:/cygwin64/tmp/apply_manifest.pp.VIHO1N {:ignore => }
    
    p13qvtljw4kkahw.delivery.puppetlabs.net (p13qvtljw4kkahw.delivery.puppetlabs.net) 01:43:02$ cmd.exe /c puppet apply --verbose C:/cygwin64/tmp/apply_manifest.pp.VIHO1N
      Notice: Compiled catalog for p13qvtljw4kkahw.delivery.puppetlabs.net in environment production in 0.02 seconds
      Info: Applying configuration version '1540604583'
      Notice: /Stage[main]/Main/Group[pl787716]/members: members changed P13QVTLJW4KKAHW\pl164231,P13QVTLJW4KKAHW\pl64140,P13QVTLJW4KKAHW\pl652124,P13QVTLJW4KKAHW\pl507478,P13QVTLJW4KKAHW\pl199482 to P13QVTLJW4KKAHW\pl164231
      Notice: Applied catalog in 1.98 seconds
```

AIX:
```
  * Verify that Puppet enforces minimum user membership when auth_membership == false
    
    aix71-7.delivery.puppetlabs.net (aix71-7.delivery.puppetlabs.net) 01:57:28$ rndnum=${RANDOM} && touch /tmp/apply_manifest.pp.${rndnum} && echo /tmp/apply_manifest.pp.${rndnum}
      /tmp/apply_manifest.pp.5149
    
    aix71-7.delivery.puppetlabs.net (aix71-7.delivery.puppetlabs.net) executed in 0.11 seconds
    localhost $ scp /tmp/beaker20181027-343-w3i46p aix71-7.delivery.puppetlabs.net:/tmp/apply_manifest.pp.5149 {:ignore => }
    
    aix71-7.delivery.puppetlabs.net (aix71-7.delivery.puppetlabs.net) 01:57:29$ puppet apply --verbose /tmp/apply_manifest.pp.5149
      Notice: Compiled catalog for aix71-7.delivery.puppetlabs.net in environment production in 0.03 seconds
      Info: Applying configuration version '1540605453'
      Notice: /Stage[main]/Main/Group[pl695552]/members: members changed 'pl563608,pl893494' to ['pl472509', 'pl563608', 'pl701760', 'pl893494']
      Notice: Applied catalog in 0.29 seconds

....

  * Verify that Puppet enforces inclusive user membership when auth_membership == true
    
    aix71-7.delivery.puppetlabs.net (aix71-7.delivery.puppetlabs.net) 01:57:49$ rndnum=${RANDOM} && touch /tmp/apply_manifest.pp.${rndnum} && echo /tmp/apply_manifest.pp.${rndnum}
      /tmp/apply_manifest.pp.1881
    
    aix71-7.delivery.puppetlabs.net (aix71-7.delivery.puppetlabs.net) executed in 0.11 seconds
    localhost $ scp /tmp/beaker20181027-343-16n6o1u aix71-7.delivery.puppetlabs.net:/tmp/apply_manifest.pp.1881 {:ignore => }
    
    aix71-7.delivery.puppetlabs.net (aix71-7.delivery.puppetlabs.net) 01:57:50$ puppet apply --verbose /tmp/apply_manifest.pp.1881
      Notice: Compiled catalog for aix71-7.delivery.puppetlabs.net in environment production in 0.03 seconds
      Info: Applying configuration version '1540605474'
      Notice: /Stage[main]/Main/Group[pl695552]/members: members changed 'pl734736,pl278701,pl472509,pl701760,pl563608,pl893494' to ['pl563608']
      Notice: Applied catalog in 0.27 seconds
```

OSX:
```
  * Verify that Puppet enforces minimum user membership when auth_membership == false
    
    ez087yj4k803kzv.delivery.puppetlabs.net (ez087yj4k803kzv.delivery.puppetlabs.net) 01:50:21$ mktemp -t apply_manifest.pp.XXXXXX
      /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/apply_manifest.pp.XXXXXX.06LwKUu4
    
    ez087yj4k803kzv.delivery.puppetlabs.net (ez087yj4k803kzv.delivery.puppetlabs.net) executed in 0.01 seconds
    localhost $ scp /tmp/beaker20181027-350-9cd7pa ez087yj4k803kzv.delivery.puppetlabs.net:/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/apply_manifest.pp.XXXXXX.06LwKUu4 {:ignore => }
    
    ez087yj4k803kzv.delivery.puppetlabs.net (ez087yj4k803kzv.delivery.puppetlabs.net) 01:50:21$ puppet apply --verbose /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/apply_manifest.pp.XXXXXX.06LwKUu4
      Notice: Compiled catalog for ez087yj4k803kzv.delivery.puppetlabs.net in environment production in 0.04 seconds
      Info: Applying configuration version '1540605024'
      Notice: /Stage[main]/Main/Group[pl988166]/members: members changed 'pl702611,pl127808' to ['pl127808', 'pl477529', 'pl538076', 'pl702611']
      Notice: Applied catalog in 0.28 seconds

...

  * Verify that Puppet enforces inclusive user membership when auth_membership == true
    
    ez087yj4k803kzv.delivery.puppetlabs.net (ez087yj4k803kzv.delivery.puppetlabs.net) 01:50:31$ mktemp -t apply_manifest.pp.XXXXXX
      /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/apply_manifest.pp.XXXXXX.7rjUbjT4
    
    ez087yj4k803kzv.delivery.puppetlabs.net (ez087yj4k803kzv.delivery.puppetlabs.net) executed in 0.01 seconds
    localhost $ scp /tmp/beaker20181027-350-5az326 ez087yj4k803kzv.delivery.puppetlabs.net:/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/apply_manifest.pp.XXXXXX.7rjUbjT4 {:ignore => }
    
    ez087yj4k803kzv.delivery.puppetlabs.net (ez087yj4k803kzv.delivery.puppetlabs.net) 01:50:31$ puppet apply --verbose /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/apply_manifest.pp.XXXXXX.7rjUbjT4
      Notice: Compiled catalog for ez087yj4k803kzv.delivery.puppetlabs.net in environment production in 0.04 seconds
      Info: Applying configuration version '1540605035'
      Notice: /Stage[main]/Main/Group[pl988166]/members: members changed 'pl702611,pl127808,pl538076,pl477529' to ['pl702611']
      Notice: Applied catalog in 0.33 seconds
```

which is correct. The test that enforces `auth_membership == false` [adds two new members to the group](https://github.com/ekinanp/puppet/blob/PUP-9265/acceptance/tests/resource/group/should_manage_members.rb#L134), while the test enforcing `auth_membership == true` sets the group to [have only one member](https://github.com/ekinanp/puppet/blob/PUP-9265/acceptance/tests/resource/group/should_manage_members.rb#L181).

**Comment by ScottGarman** [comment]
:+1:

**Comment by joshcooper** [comment]
@ekinanp for next time, can you revert specific commits instead of creating an "uber" revert commit like: https://github.com/puppetlabs/puppet/pull/7204/commits/ba6d0698c37a5711206bdb6d076da74b2b1bd71b. Related, you can give `git revert` a commit range and it will correctly unwind the commits.

**Comment by ekinanp** [comment]
@joshcooper Sure, to clarify, that would mean that in the context of this PR, it would be better to revert each of the individual PUP-6542 commits right?

**Pull request merged**
