### PR TITLE
(DOCUMENT-318) Add note about unless taking arrays

### PR DESCRIPTION
**Pull request by petems**

### CODE REVIEW

**Comment by kylog** [comment]
@peterhuene @melissa: I just noticed this PR. It hasn't been covered in PR triage because it has the 'PL' label, but @petems isn't on a team that merges to puppet despite working at PL :)

Should we drop the PL label from this (and #3800) and/or treat these as part of PR triage?

**Comment by melissa** [comment]
@kylog oops, that was my mistake. Thanks for catching it! I say we do what you suggest.

**Comment by peterhuene** [comment]
@petems Would you mind terribly amending the commit message to be prefixed with `(docs)` for this one?  Sorry this fell off our radar.  I'd like to get this merged in.

**Comment by petems** [comment]
@peterhuene Done! :+1:

**Comment by joshcooper** [comment]
for future reference, just made sense it was "all" commands need to return non-zero exit codes:

```
0 ~/work/puppet (stable)  $ be puppet apply -e 'exec { "echo oh no": path => $path, unless => ["/usr/bin/false","/usr/bin/true"] }'
Notice: Compiled catalog for arcturus.corp.puppetlabs.net in environment production in 0.43 seconds
Notice: Applied catalog in 0.04 seconds
```

vs

```
0 ~/work/puppet (stable)  $ be puppet apply -e 'exec { "echo oh no": path => $path, unless => ["/usr/bin/false","/usr/bin/false"] }'
Notice: Compiled catalog for arcturus.corp.puppetlabs.net in environment production in 0.43 seconds
Notice: /Stage[main]/Main/Exec[echo oh no]/returns: executed successfully
Notice: Applied catalog in 0.05 seconds 
```

**Pull request merged**
