### PR TITLE
Merge stable to master

### PR DESCRIPTION
**Pull request by hlindberg**

### CODE REVIEW

**Comment by hlindberg** [comment]
The failure is due to the POT updating command as it commits with a non compliant message.

**Comment by joshcooper** [comment]
This PR is also failing on ruby 1.9.3 due to net/ssh, thoughts @Iristyle?

```
Gem::InstallError: net-ssh requires Ruby version >= 2.0.
An error occurred while installing net-ssh (4.1.0), and Bundler cannot continue.
Make sure that `gem install net-ssh -v '4.1.0'` succeeds before bundling.
The command "eval bundle install --without development extra " failed 3 times.
```

**Comment by joshcooper** [comment]
POT file issue should be fixed in https://github.com/puppetlabs/ci-job-configs/pull/2742, but won't solve files that have already been updated in puppet#stable.

**Comment by joshcooper** [comment]
Looks like @thallgren merged stable->master in 9ce6842, closing this.

**Pull request closed without merging**
