### PR TITLE
Cache environment config same way as environment

### PR DESCRIPTION
**Pull request by keymone**
right now environment config is never cached. this means calls to things like `Puppet.future_parser?` are always reloading environment configuration which slows down everything.

lets cache environment config same way as environment is cached.

i got ~30-40% speedup on large catalog, reduced number of stat calls from 375k to 137k.

### CODE REVIEW

**Comment by branan** [comment]
Hi @keymone,

This looks fine to me at first glance. The tests do need to be updated before we can merge. I also want to talk to someone from the compiler team who can verify my understanding of environment expiration is correct before I push the button

**Comment by branan** [comment]
Your commit message also does not follow our requirements. Please read [contributing.md](https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md). Specifically, it needs the ticket number at the start and a more detailed body explaining the change.

**Comment by hlindberg** [comment]
if the config is not dynamically loaded (i.e. cached) and timeout is set to a very long time then you have to take down the server to make it react to a change.
This may be a moot point since the environment is still cached.

**Comment by hlindberg** [comment]
Environment config is also used by the client/agent, it may have different expectations (that I am not aware of).

**Comment by branan** [comment]
That was my understanding. I don't know if there's a real use case for having the config be replaceable if the rest of the environment is on a long timeout. My gut says "no", though.

**Comment by branan** [comment]
@keymone Hi, we haven't heard back from you. Do you think you'll be able to take the time to fix up the tests and commit message? We'll leave this open a little while longer but will probably close it in a couple weeks if we haven't heard from you.

**Comment by joshcooper** [comment]
This seems still applicable, but needs to be fixed up (single spec failures) and targeted to a later branch.

**Comment by MosesMendoza** [comment]
While this PR seems like a valuable addition, I'm afraid the team doesn't have the capacity to review/incorporate it and add the required tests for validation. I'm going to close for now, but we can reopen if/when we can pick it up again.

**Pull request closed without merging**
