### PR TITLE
(PUP-9133) Make agent side loader load all modules by using wildcard

### PR DESCRIPTION
**Pull request by hlindberg**
This introduces the abolity to give a whilecard as "module name" for
a module loader. This will have the same effect as setting `nil`
(which indicates that it is a kind of global loader), but in contrast
it will accept any namespace and attempt to load from it where a `nil`
module name means *only* accepting unqualified name (top/global
namespace).

### CODE REVIEW

**Comment by hlindberg** [comment]
Ping @tvpartytonight - thanks for the initial sleuthing on this and coming up with (#7075). After fiddling with a different solution I came up with supporting a
NAMESPACE_WILDCARD which essentially works the same as if it was set to `nil`, but not skipping the search for namespaced items. This way loading is more performant since there is no need to search the system loader for namespaced names.

**Comment by tvpartytonight** [comment]
I generally think that this approach will prove more useful over time than what is proposed in #7075 but I think we are crunched for time for the 6.0 release and should merge #7075 and then replace that functionality with this in a y release.

**Comment by tvpartytonight** [comment]
jenkins please test this

**Comment by tvpartytonight** [comment]
Preferring this over #7075.

**Pull request merged**
