### PR TITLE
DO NOT MERGE (PUP-4342) add acceptance to call all parser functions

### PR DESCRIPTION
**Pull request by er0ck**
This change adds a test for all parser functions.
This test calls all the parser functions that ship with puppet. It
ensures sane output in most cases. The remainder of the coverage for
functions lies in the spec tests.

### CODE REVIEW

**Comment by joshcooper** [comment]
@er0ck is this still needed given https://github.com/puppetlabs/puppet/pull/3917 was merged to master? Or is this a backport?

**Comment by er0ck** [comment]
it's a backport.  some folks (including @hlindberg, IIRC) thought it might be important to get into 3.x.
i guess we all forgot about the second PR on the ticket... :-\

**Comment by joshcooper** [comment]
@er0ck @hlindberg do you want to add a ticket to your sprint so this work gets backported?

**Comment by er0ck** [comment]
what work needs to be done to merge?  as far as i can tell it's ready to go.

**Comment by joshcooper** [comment]
@er0ck just that someone needs to own reviewing and merging it, and updating it if there are any 3.x differences that shake out in CI. Also, since this PR is from May, were any other changes made to puppet#master since that time, and this PR for 3.x should be updated accordingly? I'd prefer someone from the language team do this, since you guys did the original work.

**Comment by hlindberg** [comment]
+1 on merging - @er0ck will there be merge problems (merging 3.x -> stable -> master) because of this?

**Comment by er0ck** [comment]
i'll add a ticket to the sprint starting today, in the doing column so i can investigate any merge issues prior to forcing someone to review.  thanks josh

**Comment by er0ck** [comment]
yeah, this will cause issues when merging up to stable/master. we should divide the test in two parts, 3.x only and 4.x only.  4.x only test-file won't live in 3.x branch.  this PR will be for merging to 3.x.  i'll create a separate PR for removing the 3.x portion from stable.  later merges from 3.x to stable will re-enable testing of the 3.x functions in 4+ branches.

**Pull request closed without merging**
