### PR TITLE
(docs): fixed small errors

### PR DESCRIPTION
**Pull request by 0xflotus**
* enabled syntax highlighting in catalogs.md for better readability
* fixed typo errors in http.md

### CODE REVIEW

**Comment by melissa** [comment]
Hi @0xflotus! Thank you for this contribution as well!

Travis is failing here because of the commit message prefixes missing. Just like with your other PR, could you amend your commits to start with `(docs)`?

You also have a third commit here that we'll want to get ride of. [This merge commit](https://github.com/puppetlabs/puppet/pull/8122/commits/381fae45c8c1fec7b42bd6e3b1b25898b97a69ad) needs to be removed.

Again, I'm happy to walk you through any of these git updates if you like! We can do that either here in the comments, or you can reach out to me in the puppet community slack!

**Comment by 0xflotus** [comment]
> Hi @0xflotus! Thank you for this contribution as well!
> 
> Travis is failing here because of the commit message prefixes missing. Just like with your other PR, could you amend your commits to start with `(docs)`?
> 
> You also have a third commit here that we'll want to get ride of. [This merge commit](https://github.com/puppetlabs/puppet/pull/8122/commits/381fae45c8c1fec7b42bd6e3b1b25898b97a69ad) needs to be removed.
> 
> Again, I'm happy to walk you through any of these git updates if you like! We can do that either here in the comments, or you can reach out to me in the puppet community slack!

Amending multiple commits is a bit tricky I think, so I would be happy if you can help me :)

**Comment by melissa** [comment]
Hey @0xflotus! Sorry for the delay

First, I assume you're working with git on the command line, so that's how I'm going to walk you through this.

Once you navigate to the repo and are on your working branch `patch-2`, let's take a look at your commits and the changes in them:
```
git log -p -n 3
```
You'll see three commits here, the first is the merge commit, which contains zero changes. The next two are your commits for changes in `http.md` and `catalogs.md`. We want to keep the last two, amend their message, and remove the merge commit.

I have this fancy alias which maps `git lg` to `git log --graph --pretty=oneline --abbrev-commit --decorate --pretty=format:'%C(yellow)%h%C(reset) %C(green)%G?%C(reset) %C(blue)%an%C(reset) %C(cyan)%cr%C(reset) %s %C(auto)%d%C(reset)' --graph --date-order` You don't need that, but it does give me a lot of insight into what's happening in git.

When I run `git lg`, it gives me
```
*   381fae45c8 E 0xflotus 7 days ago Merge pull request #2 from 0xflotus/patch-4  (HEAD -> patch-2, com/patch-2)
|\
| * e81c63fb69 E 0xflotus 7 days ago Update http.md  (com/patch-4)
* | d0c802a165 E 0xflotus 7 days ago Update catalogs.md
|/
*   adcdbfb259 E Gabriel Nagy 8 days ago Merge pull request #8118 from joshcooper/merge_55x_master  (com/master)
```
That tells me you created the commit to update `catalogs.md` on the branch `patch-2`. Then, you created a new branch, `patch-4`, and added the change to `http.md`. Then you merged `patch-4` into the `patch-2` branch (I think).

Anyway, to fix this, I would reset to the catalogs.md change (`git reset --hard d0c802a165`), and then cherry-pick the commit for http.md (`git cherry-pick e81c63fb69`).

Once we do that, then `git lg` gives us a much cleaner graph
```
* 35383cd9d8 N 0xflotus 41 seconds ago Update http.md  (HEAD -> patch-2)
* d0c802a165 E 0xflotus 7 days ago Update catalogs.md
*   adcdbfb259 E Gabriel Nagy 8 days ago Merge pull request #8118 from joshcooper/merge_55x_master  (com/master)
```

Once the branch is clean, we need to update the commit messages to include the `(docs)` prefixes. 

Run `git rebase -i HEAD~2` (which says I want to update the commits between HEAD (the most recent commit) and 2 after HEAD). This will open a text editor with contents like
```
  1 pick d0c802a165 Update catalogs.md
  2 pick 35383cd9d8 Update http.md
  3
  4 # Rebase adcdbfb259..35383cd9d8 onto adcdbfb259 (2 commands)
```
Change the `pick` on lines 1 and 2 to `edit`, then save and close the file. You're now in a state where you can edit the older commit. `git commit --amend` will open your text editor with the commit info and you can change what it says. Once you're happy with the changes to the commit message, save and close the file, and run `git rebase --continue` and change the second commit again with `git commit --amend`. When you're done with that, run `git rebase --continue` one more time, and you're done! You can verify you've finished the rebase successfully with `git status` and `git lg` will show the updated messages
```
* e62ed6c278 N 0xflotus 87 seconds ago (docs) Update http.md  (HEAD -> patch-2)
* 73e38576d9 N 0xflotus 2 minutes ago (docs) Update catalogs.md
*   adcdbfb259 E Gabriel Nagy 8 days ago Merge pull request #8118 from joshcooper/merge_55x_master  (com/master)
```

Now you have these changes, you'll have to force push to your github branch. You've rewritten history, and git wants to make sure you know you've rewritten history. Be very very careful whenever you force push.

Make sure you're going to be pushing to the correct repo
```
➜  puppet git:(patch-2) git remote -v
com	git@github.com:0xflotus/puppet.git (fetch)
com	git@github.com:0xflotus/puppet.git (push)
```

In this case, you'd want to run `git push com HEAD -f`. Here, `HEAD` refers to our current working branch, `patch-2`. You'll want to change `com` to whatever your remote is named. It might be `origin`, it might be something else.

This turned into more of an essay than I was expecting. I hope it was helpful. Again, feel free to reach out if you'd like any more guidance. Either here or on slack.

**Comment by 0xflotus** [comment]
Thank you for your very good instructions, but I think something went wrong 🙈
What to do now or is it cleaner to start a new PR? 😓

**Pull request closed without merging**
