### PR TITLE
[DNM] (SERVER-2618) Spike making settings thread safe

### PR DESCRIPTION
**Pull request by justinstoller**

### CODE REVIEW

**Comment by justinstoller** [comment]
This and #7746 are two approaches to solve some thread safety problems. I just wanted to put my local state up to facilitate conversations with my team regarding them. I don't have any intention for either to be merged in their current for.

**Comment by Magisus** [comment]
So given the timeline we have, I'm inclined to go with this version over https://github.com/puppetlabs/puppet/pull/7746, at least for the time being. It ensures that any other work that's going on right now will be thread-safe, even if developers aren't aware of the new patterns they should be following.

The other thing really feels like something that should be broken up and done thoughtfully case-by-case, maybe in the fully better way Justin mentioned, of using local parameters, rather than the other kind of bandaid using the context.

But this will get us where we need to go to start getting validation on the single JRuby architecture.

**Comment by Magisus** [comment]
@pcarlisle thoughts on this vs https://github.com/puppetlabs/puppet/pull/7746?

**Comment by er0ck** [comment]
@pcarlisle can we get a review on these two so we can ship some threadsafe bits?

**Pull request closed without merging**
