### PR TITLE
(PUP-4210) Add rename to augeas

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by branan** [comment]
Hi, this looks pretty sane. Could you please add a test for the rename command? The provider spec has examples already for a basic check of the other commands we support.

**Comment by branan** [comment]
@raphink ping? Will you be able to update this with tests?

**Comment by melissa** [comment]
@raphink have you had a chance to update this with tests?

**Comment by raphink** [comment]
Sorry, not yet. Thanks for pinging.

**Comment by peterhuene** [comment]
Hi @raphink, thanks again for the contribution.  I'm just checking in to see if you've had any chance to update with tests.

**Comment by raphink** [comment]
Sorry not yet. I'll look into it when I get back from vacation next week.

**Comment by raphink** [comment]
Added a unit test for the rename command.

**Comment by raphink** [comment]
Rebased on master.

**Comment by peterhuene** [comment]
@raphink Thanks for the test and rebase.  This looks good to me.  I need to look into getting these specs run in our CI as I don't think we have augeas installed for it to test.

**Comment by peterhuene** [comment]
Although it looks like the new test isn't confined to when augeas is installed, so I'm :+1:

**Comment by raphink** [comment]
Great.

**Comment by peterhuene** [comment]
@raphink Thanks again for the contribution!  Your PR has been merged to master and will show up in the next release of Puppet.

**Comment by raphink** [comment]
Great, thanks

**Pull request merged**
