### PR TITLE
(PUP-7926) Fix capitalization of a regex (A-Z not A-z)

### PR DESCRIPTION
**Pull request by incase**
Otherwise this is over-matching (matches anything between ASCII A and ASCII z, which is much more than just characters).

### CODE REVIEW

**Comment by incase** [comment]
Note: Send a matching pull request to upstream for pathspec: https://github.com/highb/pathspec-ruby/pull/16

**Comment by hlindberg** [comment]
@incase Thanks for your contribution!

It would help a lot if you could do the following: 
* File a ticket for the PUP project that describes the problem (that helps us write a release note among other things)
* Make the first line of the commit message reference the PUP ticket, for example (PUP-1234)

Example commit message `(PUP-1234) Fix problem of matching too much in pathspec with A-z regexp`

This is needed as we match up all commits with tickets at release time.

**Comment by incase** [comment]
Ticket filed, commit message updated.

**Comment by hlindberg** [comment]
@incase thanks for logging a ticket - you still have the commit itself to deal with (that is why the travis tests shows a failure). The commit message should have the same form as the title of this PR - i.e. `(PUP-7926) Fix....`

**Comment by Iristyle** [comment]
I'm not even sure where `match_path` is used (it doesn't appear to be called in the Puppet code anywhere) - but perhaps 3rd parties are consuming it in tests?

Anyhow, the fix looks good to me, as long as we don't want to delete the code altogether.

**Comment by hlindberg** [comment]
@Iristyle  in that case we need a major version bump (don't think this was marked as private). Merging this, it is at least better than before this fix.

**Comment by hlindberg** [comment]
@incase Can you fix the message of the commit so that it conforms to the policy? That is the only thing that stops this from being merged.

**Comment by incase** [comment]
Now, if I knew how to add either add a commit to this and remove the old one, or how to edit the commit message on the existing change, I would be happy to do it. But I purely used the web interface to create this and don't know anything useful about the commandline client and don't have a local client. So it seems the most viable path for me would be to create a new pull request with a fixed commit?

**Comment by incase** [comment]
After all I tried, I only ended up polluting this pull request with stuff that doesn't belong here.
I'll withdraw this one and create a new one.

**Pull request closed without merging**
