### PR TITLE
(PUP-7786) Allow Puppet acceptance tests to pass in the presence of translations

### PR DESCRIPTION
**Pull request by Magisus**
We currently have one test cell, `windows2012r2_ja-64`, whose locale is set to Japanese. Japanese translations will soon be landing in Puppet, which means error and info strings will no longer be output in English when running on a Japanese machine. Many of our acceptance tests match against English output, so these will begin failing. This PR deletes certain tests marked for deletion during a recent QA audit, and adds limited confines to the other problematic tests, which avoid English matching assertions, while allowing the rest of the test to run. These confines rely on a `{locale=ja}` option being passed to beaker-hostgenerator when running tests in a Japanese locale.

Ultimately, many of these tests will be porting to RSpec, where we do not use translations. I hope that the beaker-hostgenerator option will eventually be replaced by a beaker method to detect locale, or some other less hacky solution. In the meantime, these fixes allow the tests to pass while giving as much validation as possible.

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
👍

**Comment by er0ck** [comment]
How can we be sure the tests being deleted will all be ported to spec, where appropriate?

**Comment by Magisus** [comment]
Do we want to port them? I thought we had said if the test was marked "delete" we were simply going to delete it, since according to the audit specification, "level" is a required field, but delete is optional (i.e. even if you intend to delete the test, you still have to mark a level)? If that's incorrect, we should not delete any tests at this time, and instead just confine them like the others, I suppose. We should check in with what @johnduarte intended when he marked them.

**Comment by er0ck** [comment]
@Magisus yeah, we hadn't originally specified a delete option.  so i just want to be sure that's what john intended.  alternatively some tickets to say we're going to port these very soon.  or just more `unless locale` conditionals.  i appreciate this is more work and not optimal.

**Comment by justinstoller** [comment]
I believe @Magisus correctly interpreted the meaning of the delete tag.

**Comment by er0ck** [comment]
outvoted and outnumbered, he succumbs to the button push...

this sounds and looks good to me!

**Pull request merged**
