### PR TITLE
(PUP-8531) Remove unused app_management config setting

### PR DESCRIPTION
**Pull request by jhelwig**
The config setting has been deprecated for a while, and has not done anything during that time.

### CODE REVIEW

**Comment by jhelwig** [comment]
Jenkins please test this

**Comment by joshcooper** [comment]
ping @adreyer

**Comment by jhelwig** [comment]
Ping might be a little early. There's still some references in the acceptance tests I wanted to look at, which is why the "Do Not Merge" tag is on here.

**Comment by nicklewis** [comment]
@joshcooper I'm not 100% clear about the plans for the app management functionality, but it hasn't been deprecated, so it seems like we shouldn't remove it.

**Comment by joshcooper** [comment]
@nicklewis ah k, I was confused because the `app_management` defaulted to false (but was ignored). What you said makes sense. Removing the language features is a different matter.

**Pull request merged**
