### PR TITLE
(PUP-6141) Move from forgeapi.puppetlabs.com to forgeapi.puppet.com

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by branan** [comment]
Hi, thanks for the contribution!

I actually have no idea why we haven't done this yet, so I'm going to reach out to our release engineering and QA teams for their feedback on what our internal plans are for this, and why we're holding off.

@shrug @johnduarte do you have any context around this part of the branding update?

**Comment by roidelapluie** [comment]
Oh: I forgot: forgeapi.puppet.com works:

```
puppet module install --module_repository=https://forgeapi.puppet.com puppetlabs-apache
Notice: Preparing to install into /home/roidelapluie/.puppetlabs/etc/code/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
opening connection to forgeapi.puppet.com:443...
opening connection to forgeapi.puppet.com:443...
opening connection to forgeapi.puppet.com:443...
opening connection to forgeapi.puppet.com:443...
opening connection to forgeapi.puppet.com:443...
opening connection to forgeapi.puppet.com:443...
opening connection to forgeapi.puppet.com:443...
opening connection to forgeapi.puppet.com:443...
opening connection to forgeapi.puppet.com:443...
opening connection to forgeapi.puppet.com:443...
Notice: Installing -- do not interrupt ...
/home/roidelapluie/.puppetlabs/etc/code/modules
└─┬ puppetlabs-apache (v1.10.0)
  ├── puppetlabs-concat (v1.2.4)
  └── puppetlabs-stdlib (v4.9.0)
```

**Comment by roidelapluie** [comment]
Thanks. Amended commit & PR to match the ticket

**Comment by joshcooper** [comment]
We don't issues internally, because we use beaker's [`stub_forge_on`](https://github.com/puppetlabs/beaker/blob/54dd81922e075769d48d4b5f01b7432ef4a4ed1c/lib/beaker/dsl/helpers/puppet_helpers.rb#L574-L582) helper to add an /etc/hosts entry to point forgeapi.puppetlabs.com to an internal IP address whose name is specified in our [acceptance Rakefile](https://github.com/puppetlabs/puppet/blob/a4ccfdaaf45edf9130ee58cbe63555e3aabbd37f/acceptance/Rakefile#L39)

**Comment by branan** [comment]
BKR-847 is in a PR as https://github.com/puppetlabs/beaker/pull/1148. Once that's in we can get this merged

**Comment by johnduarte** [comment]
Beaker 2.48.1 contains the updates to test against
* forge.puppet.com
* forgeapi.puppet.com
* forge.puppetlabs.com
* forgeapi.puppetlabs.com

This PR is no longer blocked. I believe we can pull this in after the release of puppet 4.6.0.

**Pull request merged**
