### PR TITLE
(maint) bump LTS version to 4.7.2

### PR DESCRIPTION
**Pull request by MosesMendoza**
This commit updates the version in anticipation of an upcoming 4.7.2 release.

Signed-off-by: Moses Mendoza <moses@puppet.com>

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
👍

**Comment by Magisus** [comment]
According to https://confluence.puppetlabs.com/display/PROD/puppet-agent+Versions+and+Dependencies the version is supposed to be 4.7.1... is that incorrect?

**Comment by McdonaldSeanp** [comment]
True, the version has already been updated.

**Comment by MosesMendoza** [comment]
Great catch. I knew we didn't ship 4.8.2, but hadn't realized 4.7.1 was in the same boat. Thanks

**Pull request closed without merging**
