### PR TITLE
(PUP-8495) Systemd support, Ubuntu 17.04 and 17.10

### PR DESCRIPTION
**Pull request by kbarmen**
And prepare Puppet for Ubuntu 18.04 and 18.10.

### CODE REVIEW

**Comment by melissa** [comment]
Thank you for the contribution @kbarmen !

It looks like you have references to 18.04 and 18.10 in your commit message. Could you update that to reflect that you're adding 17.04 and 17.10 instead?

**Comment by kbarmen** [comment]
I do indeed consider the patch very trivial, so no need for CLA.

It is perhaps time to switch to systemd as default for Ubuntu (and Debian), and let upstart only be triggered for older releases. That's a whole other patch though, I'm not fluent in ruby :)

I will try to change my commit message, my git foo is so so.

**Comment by kbarmen** [comment]
Looks like I killed Travis CI :)

**Comment by melissa** [comment]
Strange, it looks like travis maybe timed out on those jobs. I've restarted them.

I also agree this is a trivial patch, so no need to sign the CLA.

And thank you for updating your commit message! I need to poke around a little more to make sure there's nothing else we need to add before merging this, but it looks good!

**Comment by melissa** [comment]
Actually, I just noticed this is targeting the master branch. Can you retarget it to the 4.10.x branch? That way we can get this change in 4.10.x if we ever do another release for that series, plus all future releases in 5.x

**Comment by kbarmen** [comment]
Oboy, this is a git workshop for me :)
To avoid merge conflicts, I'll make a new pull request for 4.10.x

**Comment by melissa** [comment]
Git is a process. You can use `git cherry-pick 9a82ae7e1e40eec2df3e27ff26cb4802bde5dee7` to bring just this commit to the branch you want rather than re-writing everything

**Comment by melissa** [comment]
I'm closing this PR in favor of https://github.com/puppetlabs/puppet/pull/6706

**Pull request closed without merging**
