### PR TITLE
(PUP-9303) Reapply earlier revert for heredoc locator problems and drop text in margin error

### PR DESCRIPTION
**Pull request by hlindberg**
This was fixed earlier but reverted because the fix was not bug-compatible wrt handling of heredoc with text in margin.
The specification says that white space up to margin should be removed for lines that extend into the margin but the implementation does nothing for such lines.

This PR adds back the reverted fixes for the original locator problems where seemingly random positions in the text affects the outcome - with mysterious syntax errors as the result.
(See commit messages).

### CODE REVIEW

**Comment by hlindberg** [comment]
Ping @Magisus / @justinstoller - can we get this merged now?  Implementation is now compatible with the specification.

**Comment by Magisus** [comment]
jenkins please test this

**Comment by Magisus** [comment]
So this is targeted at 5.5.x, I'll need to check on the status of that release before merging this. If you'd like to get it into the 6.0.x release, it might be worth retargeting and then cherry-picking back later.

**Comment by hlindberg** [comment]
Merging, as it is approved and servertest ran green.

**Pull request merged**
