### PR TITLE
(PUP-4659) Update environment tests

### PR DESCRIPTION
**Pull request by joshcooper**
Previously, the tests failed when the master had the agent role. This
wasn't noticed originally due to PUP-4111. We also stopped testing the
agent role on the master in the lead up to Puppet 4, so once PUP-4111
was fixed, we didn't see the problem in platform CI. But puppetserver CI
does test that combination and was failing.

These commits update some of the environment related tests to
match the current and expected behavior.

### CODE REVIEW

**Comment by joshcooper** [comment]
Here's the output when all of the `environment` tests are run against redhat-7-x86_64 with the master host having the agent role.

```
$ git rev-parse HEAD
5673069b02f43ad3bad867520742518acc8c29ef
$ git diff
diff --git a/acceptance/config/nodes/redhat-7-x86_64.yaml b/acceptance/config/nodes/redhat-7-x86_64.yaml
index 9593c6e..a438f00 100644
--- a/acceptance/config/nodes/redhat-7-x86_64.yaml
+++ b/acceptance/config/nodes/redhat-7-x86_64.yaml
@@ -3,6 +3,7 @@ HOSTS:
   master:
     roles:
     - master
+    - agent
     platform: el-7-x86_64
     hypervisor: vcloud
     template: redhat-7-x86_64
$ be rake ci:test:aio SHA=e72e0af75d1e8e1f27ad5faaaa9cbc1d73898c0f CONFIG=config/nodes/redhat-7-x86_64.yaml TESTS=tests/environment
...
              - Test Case Summary for suite 'tests' -
       Total Suite Time: 1327.74 seconds
      Average Test Time: 69.88 seconds
              Attempted: 19
                 Passed: 19
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 19
```

**Comment by joshcooper** [comment]
@er0ck for your review

**Comment by er0ck** [comment]
oops.  totally forgot to tackle this myself, last week.  checking against ubuntu14

**Comment by MikaelSmith** [comment]
:+1:

**Pull request merged**
