### PR TITLE
PUP-5289 adding interface mode auto, encapsulation negotiate to puppet device

### PR DESCRIPTION
**Pull request by jorhett**
This patch adds full support for interface mode auth, and encapsulation negotiate to the cisco device. It also adds new tests for mode and encapsulation to the interface resource which didn't exist before.

### CODE REVIEW

**Comment by jorhett** [comment]
Fixed encap negotiate detection.

**Comment by whopper** [comment]
/cc @ScottGarman @nanliu any thoughts on this?

Also, @jorhett, would you mind amending your commit message to put the PUP-5289 in parens? That'll make our Travis commit check pass.

**Comment by ScottGarman** [comment]
I was under the impression that we were about to deprecate and remove the cisco provider from Puppet Core, in favor of using modules instead. @kylog can you chime in here?

**Comment by kylog** [comment]
We *want* to split non-core functionality out into modules: https://tickets.puppetlabs.com/browse/PUP-4380. The specific ticket for the cisco provider is: https://tickets.puppetlabs.com/browse/PUP-4682.

None of that effort is scheduled however, much to my sadness. 

Meanwhile, I don't see why we wouldn't continue to advance the state of such providers in core. If we do that, then, when we do get around to extracting them from core, they will have all the latest goodness.

(And btw, these comments are independent of this PR per se - just providing context for Scott's question.)

**Comment by joshcooper** [comment]
Hey @jorhett, it was good catching up at PuppetConf. It looks like this PR has valid test failures. Can you take a look?

@ScottGarman did you have any concerns about the changes (ignoring the "when are we moving this to a module" question)?

**Comment by ScottGarman** [comment]
I have no objections to the changes. Are the failing tests something that need to be fixed?

**Comment by joshcooper** [comment]
@ScottGarman thanks for reviewing

@jorhett so looks like a few tests need updating, and we'll get this merged, thanks!

**Comment by joshcooper** [comment]
ping @jorhett

**Comment by HAIL9000** [comment]
Hey @jorhett, thanks so much for the contribution. Just wanted to check in because it's been a little while, are you still interested in fixing this up so we can get it merged? If you have a second please let us know either way so we know how to move forward.

Thanks!

**Comment by jorhett** [comment]
yes, sorry. been caught up in stuff. Wednesday night at the latest.

**Comment by jorhett** [comment]
I'm sorry, I tried to work on this tonight. I found the relevant code but I'm exhausted after a late night of on-call response and I'm simply too tired to continue. More tomorrow.

**Comment by jorhett** [comment]
Okay, a revised and improved commit has been added which supports both dynamic auto (prefer access) and dynamic preferred (prefer trunk) auto-negotiation modes. It also allows a distinct setting of the trunk native vlan, while being backwards compatible with the numerous online references.

**Comment by jorhett** [comment]
Confirmed: your suggestion won't work. First I tried removing the begin/end and commenting out the @channel.close

```
$ puppet device --verbose
Info: starting applying configuration to switch01.example.com at ssh://switch01.example.com/
Info: Retrieving pluginfacts
Info: Retrieving plugin
Error: Could not retrieve local facts: closed stream
Error: Failed to apply catalog: Could not retrieve local facts: closed stream
```

Then I tried commenting out @channel = nil as well.

```
$ puppet device --verbose
Info: starting applying configuration to switch01.example.com at ssh://switch01.example.com/
Info: Retrieving pluginfacts
Info: Retrieving plugin
Error: Could not retrieve local facts: closed stream
Error: Failed to apply catalog: Could not retrieve local facts: closed stream
```

The issue at hand is the rude termination of SSH using RST. If this occurs, the SSH object itself will toss an IOError for any request made of it, including close.

This is where the maintainer is using the same approach himself: https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/buffered_io.rb with comments about same at https://www.omniref.com/github/net-ssh/net-ssh/2.1.1/symbols/Net::SSH::BufferedIo#line=152

Likewise, your own ticket for Beaker includes significant discussion of the dynamics here: https://tickets.puppetlabs.com/si/jira.issueviews:issue-html/BKR-70/BKR-70.html

**Comment by HAIL9000** [comment]
@jorhett Thanks for the updates! Could you rebase this again? It looks like you grabbed an extra commit by mistake.

@ScottGarman Could you take another look at this now that it's been udpated?

**Comment by jorhett** [comment]
Sorry, I clicked the link to merge the latest in. I'll rebase it back out again.

**Comment by jorhett** [comment]
Okay, I think I cleaned the tree up correctly now.

**Comment by ScottGarman** [comment]
:+1:

**Pull request merged**
