### PR TITLE
Clear envs for rich data toggle

### PR DESCRIPTION
**Pull request by Magisus**

### CODE REVIEW

**Comment by Magisus** [comment]
This is hacky but is the only thing I've so far gotten to have the desired behavior of only clearing environments when you actually change the value of `rich_data` programmatically (in my case, I had a function that set it).

**Comment by Magisus** [comment]
Working on this we learned that
```
irb(main):001:0> require 'puppet'
=> true
irb(main):002:0> Puppet[:rich_data]
=> true
irb(main):003:0> Puppet[:rich_data] = false
This is an rich_data value: false
This is the current rich_data value: true
=> false
irb(main):004:0> Puppet[:rich_data]
=> false
```

But also
```
irb(main):001:0> require 'puppet'
=> true
irb(main):002:0> Puppet[:rich_data] = false
This is an rich_data value: false
This is the current rich_data value: false
=> false
```

Which is to say, if you have never accessed the value of a setting before, the "value" passed into the hook is also the value of the setting itself to outside code. But if you _have_ accessed that setting before, the value of the setting is old value, and the one passed into the hook is the new value.

**Comment by joshcooper** [comment]
@Magisus is this ok to close?

**Comment by Magisus** [comment]
Yep, we went with the other PR instead.

**Pull request closed without merging**
