### PR TITLE
(PUP-4545): Too many restarts on interface changes

### PR DESCRIPTION
**Pull request by danzilio**
This commit removes `ext/puppet-nm-dispatcher` and cleans up the RPM
spec accordingly.

### CODE REVIEW

**Comment by kylog** [comment]
@shermdog IIRC you were taking a look at this issue?

**Comment by stahnma** [comment]
:+1:

**Comment by shermdog** [comment]
Pinging @kylog for some internal discussion around this.

**Comment by kylog** [comment]
@underscorgan why did you close this? Mostly just curious what y'all may have discovered and I didn't see comments here or in the jira ticket. Thanks!

**Comment by underscorgan** [comment]
@kylog looks like this was targeted against 3.8.x, so when I deleted the branch it closed the PR? This should probably just get retargeted towards 3.x

**Comment by kylog** [comment]
Ohhhhh right.

For back story, @danzilio, we realized just this morning that we created some confusion by having both a `3.x` branch and a `3.8.x` branch (the latter was intended just for the short-term security release of 3.8.6, the former is where we actually have long-term CI and usually release from). 

`3.8.x` is gone now, so please retarget this to `3.x` when you get a chance. Thanks!!

**Comment by danzilio** [comment]
Will do!!

**Comment by danzilio** [comment]
Rebased in #4780

**Pull request closed without merging**
