### PR TITLE
(maint) Bump ruby version to 2.1.8

### PR DESCRIPTION
**Pull request by kylog**

### CODE REVIEW

**Comment by stahnma** [comment]
:+1:

**Comment by MikaelSmith** [comment]
In 3.x as well? I guess it works, so why not...

**Comment by kylog** [comment]
Yeah I figure latest 2.1.z for each branch that support 2.1.z (which is all of 3.x/stable/master right now). So I'm thinking once we merge this, we merge up and all branches get this.

**Comment by ferventcoder** [comment]
whoa. I was under the impression that 3.x was 1.9.3/2.0.0 for Windows.

**Comment by ferventcoder** [comment]
Guess it doesn't really matter given it's just testing. :)

**Comment by kylog** [comment]
@ferventcoder this is a travis-only change, no windows impact.

**Pull request merged**
