### PR TITLE
(PUP-4242) change deprecation for namespace mismatch to an error.

### PR DESCRIPTION
**Pull request by kris-bosland**

### CODE REVIEW

**Comment by justinstoller** [comment]
@Magisus we need to do [SERVER-2218](https://tickets.puppetlabs.com/browse/SERVER-2218) before we take this change into our dev environment.

**Comment by hlindberg** [comment]
This PR does not do what the title says "change to an error" since it uses the `strict` setting making it possible for users to turn it off, get a warning or error.
If the intention is to actually make it an error, then there is no need to configure it at all since the default for a reported issue is to error. If there is a desire to be explicit, rather than removing the entire line where it used to set `:deprecation`, it can be set to `:error` to always error.

The tests do test that it is controlled by `strict` flag - so... is it just the title of the PR that is wrong and we want Puppet 6 to have this configurable?

**Comment by kris-bosland** [comment]
@hlindberg, @joshcooper what is the appropriate level of error for this issue?  My changes are based on other issues found in lib/puppet/pops/validation/validator_factory_4_0.rb, which were the same as an earlier PR which was reviewed and merged, so I did not ask for further feedback.

**Comment by hlindberg** [comment]
Since the issue is set to `:deprecated` in 5.y I assumed it would be a hard error in 6.0.0 and not under user's control. In fact, making it be under the control of the strict flag makes it more relaxed than 5.y since there it is a hard deprecation. I made a comment on the ticket as well - a decision is needed (on the ticket).

**Comment by joshcooper** [comment]
👍 Could you squash the two commits, since the second commit is needed to make the first commit pass?

**Comment by kris-bosland** [comment]
@joshcooper squashed.

**Comment by hlindberg** [comment]
AppVeyor timed out - restarted

**Pull request merged**
