### PR TITLE
Fixes #9220: Accept environment names consisting only of integers. 

### LINKED ISSUE #9220: Environment names can't contain only integer
## Describe the Bug
Using an environment name composed only of numeric characters makes the catalog compilation fail.
The [puppet documentation](https://www.puppet.com/docs/puppet/8/lang_reserved.html#lang_acceptable_char-environment-names) explains that environment names can contain lowercase letters, numbers and underscores. It does not prohibit the use of numeric characters only.

When using an environment like `42`, we get ruby stacktrace like this one:

```syslog
2024-01-23T11:02:48.938+01:00 ERROR [qtp472974372-11877] [puppetserver] Puppet Server Error: undefined method `match' for 42:Integer
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/node/environment.rb:127:in `valid_name?'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:90:in `uri2indirection'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:35:in `call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/server/v3.rb:17:in `block in wrap'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:82:in `block in process'
org/jruby/RubyArray.java:1865:in `each'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:81:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:88:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:88:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:86:in `block in process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:69:in `block in with_request_profiling'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:65:in `with_request_profiling'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:85:in `block in process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:92:in `respond_to_errors'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:84:in `process'
uri:classloader:/puppetserver-lib/puppet/server/master.rb:69:in `block in handleRequest'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:62:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:289:in `override'
uri:classloader:/puppetserver-lib/puppet/server/master.rb:68:in `handleRequest'
```
 
 
## Expected Behavior
An environment name composed only of numeric characters should be valid.

## Steps to Reproduce
1. Create a puppet environment with only numeric characters (eg.: 42)
2. run `puppet agent -t --environment 42`
3. get the error described above on the puppetserver.

## Environment
 - puppetserver Version 7.14.0-1buster
 - Platform Debian buster

## Additional Context
We are deploying environments from a Gitlab repository with r10k.
[GitLab uses the default pattern `%{id}-%{title}` when creating a branch from an issue](https://docs.gitlab.com/ee/user/project/repository/branches/#configure-default-pattern-for-branch-names-from-issues).
If we want keep branch names equals to environment names (i.e. without hyphens), the easy solution is to replace the pattern with `%{id}` only. Otherwise the spaces and special characters in `%{title}` xould be converted to hyphens.

Using this workflows, we end up with some numeric only branches/puppet environments. 

According to puppet documentation, this shouldn't have been a problem.

A pull-request to fix this in on the way.

### PR DESCRIPTION
**Pull request by saimonn**
See #9220 for motivations behind this pull-request

### CODE REVIEW

**Review by joshcooper — CHANGES_REQUESTED** [review]
Hi thanks for your PR, but unfortunately we've had issues in the past with confusion between symbols and strings in environment names. We don't want to reintroduce string-based names. See a6e0a6bed3dd9ccef5d72d4d2c39a873c1cb454a and ceb7c011a29edede9ef5532b379c716acf0aa997

I think you'll want to add some debugging to https://github.com/puppetlabs/puppet/blob/3192f4aab419b221402f738ed1be90de0d969be5/lib/puppet/network/http/api/indirected_routes.rb#L36 to see if puppetserver is passing the environment request parameter as an integer when calling into puppet? Or if something in the indirected routes is coercing the string to an integer. It should be a string by the time we reach https://github.com/puppetlabs/puppet/blob/3192f4aab419b221402f738ed1be90de0d969be5/lib/puppet/network/http/api/indirected_routes.rb#L62

It's probably this https://github.com/puppetlabs/puppet/blob/52903c21b05d98b9611903e4b9f0252cf081d1ca/lib/puppet/network/http/handler.rb#L197 Probably want to special case `environment` since we know that shouldn't be coerced to integer and we don't want to break compatibility.

**Comment by joshcooper** [comment]
Hi @saimonn have you had a chance to review my comments? We'd welcome a pull request if you can incorporate those changes, thanks!

**Comment by saimonn** [comment]
Hi @joshcooper, thanks for the reminder!

I don't have enough time nor ruby knowledge to dig further on this PR. 

We ended by [prefixing our branches/environment names with letters](https://github.com/puppetlabs/puppet/issues/9220#issuecomment-2049096964) as a workaround.

You can close this PR unless you find someone else with resources to address it.

**Comment by joshcooper** [comment]
Ok, thanks for letting us know. I'm going to close this for now.

**Pull request closed without merging**
