### PR TITLE
(maint) mergeup 5.3.x -> master

### PR DESCRIPTION
**Pull request by johnduarte**

### CODE REVIEW

**Comment by johnduarte** [comment]
Merging this PR is blocked on a green CI run of puppet-agent 5.3.x including puppet at https://github.com/puppetlabs/puppet/commit/d23ff65ebe872aa8df6de547dff3d6896d12feca

**Comment by johnduarte** [comment]
We have a green run on puppet-agent 5.3.x including puppet at https://github.com/puppetlabs/puppet/commit/d23ff65ebe872aa8df6de547dff3d6896d12feca

This PR should be ready to merge now.

cc: @geoffnichols , @branan , @McdonaldSeanp

**Comment by Magisus** [comment]
Not seeing this, I opened https://github.com/puppetlabs/puppet/pull/6269, which has up to the latest passing 5.3.x SHA.

**Comment by johnduarte** [comment]
👍 @Magisus I am closing this PR.

**Pull request closed without merging**
