### PR TITLE
(PUP-7042) Mark strings in reference

### PR DESCRIPTION
**Pull request by Magisus**
This commit marks user-facing error and info strings in
`lib/puppet/reference/*` for translation.

### CODE REVIEW

**Comment by Magisus** [comment]
Closing and reopening to fix Travis.

**Comment by Magisus** [comment]
One more time, now with base switch.

**Comment by Magisus** [comment]
Closing and reopening to fix CI.

**Comment by McdonaldSeanp** [comment]
👍

**Pull request merged**
