### PR TITLE
WIP (PUP-4050): configure AIO module dirs for Git acceptance

### PR DESCRIPTION
**Pull request by Iristyle**

### CODE REVIEW

**Comment by Iristyle** [comment]
Current failures have decreased, so this might be an OK approach to just making this work for now, until the tech debt can be paid off:

```
      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 4726.15 seconds
      Average Test Time: 17.00 seconds
              Attempted: 278
                 Passed: 225
                 Failed: 5
                Errored: 1
                Skipped: 46
                Pending: 1
                  Total: 278

      - Specific Test Case Status -

Failed Tests Cases:
  Test Case tests/ensure_puppet-agent_paths.rb reported: #<Beaker::DSL::Outcomes::FailTest:
Failed to find expected binary '/usr/bin/mco.bat' on agent 'y42cxxovxvhvaqo.delivery.puppetlabs.net'
>
  Test Case tests/modules/list/with_installed_modules.rb reported: #<Minitest::Assertion: --- expected
+++ actual
@@ -1,4 +1,5 @@
 "/etc/puppetlabs/code/modules
+├── jenny (\e[0;36m???\e[0m)
 ├── jimmy-appleseed (\e[0;36mv1.1.0\e[0m)
 ├── jimmy-crakorn (\e[0;36mv0.4.0\e[0m)
 └── jimmy-thelock (\e[0;36mv1.0.0\e[0m)
>
  Test Case tests/modules/list/with_repeated_dependencies.rb reported: #<Minitest::Assertion: --- expected
+++ actual
@@ -1,6 +1,7 @@
 "/etc/puppetlabs/code/modules
-└─┬ jimmy-thelock (\e[0;36mv1.0.0\e[0m)
-  ├─┬ jimmy-crakorn (\e[0;36mv0.4.0\e[0m)
-  │ └── jimmy-steward (\e[0;36mv0.9.0\e[0m)
-  └── jimmy-appleseed (\e[0;36mv1.1.0\e[0m)
+├─┬ jimmy-thelock (\e[0;36mv1.0.0\e[0m)
+│ ├─┬ jimmy-crakorn (\e[0;36mv0.4.0\e[0m)
+│ │ └── jimmy-steward (\e[0;36mv0.9.0\e[0m)
+│ └── jimmy-appleseed (\e[0;36mv1.1.0\e[0m)
+└── jenny (\e[0;36m???\e[0m)
 "
>
  Test Case tests/modules/uninstall/with_multiple_modules_installed.rb reported: #<Beaker::DSL::Outcomes::FailTest:
Expected /\/etc\/puppetlabs\/code\/modules
\u251C\u2500\u2500 pmtacceptance-java \(.*v1.6.0.*\)
\u2514\u2500\u2500 pmtacceptance-stdlub \(.*v1.0.0.*\)/ to match "/etc/puppetlabs/code/modules\n├── jenny (\e[0;36m???\e[0m)\n├── pmtacceptance-java (\e[0;36mv1.6.0\e[0m)\n└── pmtacceptance-stdlub (\e[0;36mv1.0.0\e[0m)\n".
>
  Test Case tests/modules/upgrade/in_a_secondary_directory.rb reported: #<Minitest::Assertion: --- expected
+++ actual
@@ -1,4 +1,5 @@
 "/etc/puppetlabs/code/modules
+├── jenny (\e[0;36m???\e[0m)
 ├── pmtacceptance-java (\e[0;36mv1.6.0\e[0m)
 └── pmtacceptance-stdlub (\e[0;36mv1.0.0\e[0m)
 "
>
Errored Tests Cases:
  Test Case tests/config/puppet_manages_own_configuration_in_robust_manner.rb reported: #<Beaker::Host::CommandFailure: Host 'm3n6542xqyksko3.delivery.puppetlabs.net' exited with 1 running:
 puppet master
Last 10 lines of output were:
>
```

**Comment by joshcooper** [comment]
btw, you can add `[skip ci]` in the body of the commit message, and it'll skip travis & appveyor

**Comment by Iristyle** [comment]
Closing in favor of https://github.com/puppetlabs/puppet_for_the_win/pull/114 + docs + email blast, etc.

**Comment by kylog** [comment]
@Iristyle is this the one you meant to close? Your comment makes me think it was #4011.

**Comment by joshcooper** [comment]
@Iristyle you're still working on this PR, right? I'll apply the Windows label

**Comment by Iristyle** [comment]
Yes, intend to resume working on this and take to completion this sprint.

-e

**Comment by Iristyle** [comment]
Closed in favor of #4088 which has been retargeted at master branch.

**Pull request closed without merging**
