### PR TITLE
(PUP-6964) Make modules see all other modules with dependencies first

### PR DESCRIPTION
**Pull request by hlindberg**
This makes everything available in an environment loadable by a module.
Earlier a module could only see into modules it depended on.

The search now starts by searching modules listed as dependencies.

### CODE REVIEW

**Comment by hlindberg** [comment]
Rebased and conflicting test resolved. @joshcooper can this be unblocked now? Performance degradation observed with earlier PR should no longer be an issue.
There is now also a performance test in puppet that tests loading which was used to assert this.

**Comment by joshcooper** [comment]
Isn't this ` O(n^2)` as in every module could end up searching every other module. Worst case the module that everything depends on is last in the search path. That seems bad.

Rather than relaxing the visibility constraint always, what about only relaxing the constraint when environment timeout is unlimited, and modifying the code to determine module dependencies once at the beginning when the environment is created?

**Comment by hlindberg** [comment]
@joshcooper Users are surprised and annoyed that visibility is only into modules that are listed as dependencies. The old behavior searched everything when there were no dependencies listed (so no change for those modules). For all others, the change in this PR will have the same (roughly within margin of error of measuring) performance as before as it will find things in the usually much shorter list of modules listed as dependencies.

The implementation does build an index but it does it incrementally. A search means a hash lookup once per searched module (roughly), and after the first resolution of a function in one module the next time it is needed in the same module, it is found with one hash lookup. At any time it does one glob per module and caches that. It only reads a file if it knows it is there and the one that it wants to load.

Still - worst case, if you have stdlib last and a module path with many modules and you do not have any dependencies - yeah it will search the entire path for each function (in stdlib) - but that is no worse than what is before this PR.

We may gain performance by having a single combined resolution index (instead of one per module) - which is now possible since everything is viewable by everyone else. 
That means that there is only one exhaustive search per function. Fixing that is beyond the scope of this ticket though as that requires a more extensive change of the 4x loaders caching mechanism.

I don't think having the behavior depend on env timeout is desirable as your code would then just not work in some configurations.

Can we remove the block and get this merged now?

**Comment by joshcooper** [comment]
The caching logic seems really complicated and expensive (O^2). For example, our internal deployment uses many modules without dependencies, and they didn't notice a perf regression when the prior PR landed, because they were already in a perf degraded state! I would much rather see us register functions once, e.g. `create_function`, when the environment is created, and do simple lookups as functions are called. What is preventing us from doing that (in the longer term)?

This PR does make the failure case worse, right? Previously, if modules declared dependencies, but the loader couldn't find the called function, then the compile would fail more quickly than it would with this PR. Is there a scenario where we would ignore the failure to load a function and fall back to another mechanism, e.g. we look for a 4.x function, then fall back to 3.x?

**Comment by hlindberg** [comment]
@joshcooper you are right that a search will look for a 4.x function first before going to 3.x - and this fix would therefore slow down all calls to 3.x functions.
While this could be a good incentive to make people move off 3.x functions :-) I think that is reason to not merge this and instead do the more elaborate change to caching/indexing.

**Comment by hlindberg** [comment]
After discussion with @thallgren - it may not be that bad for 3.x since a "not found" in 4.x. is cached and quickly resolved the next time. We think this is not really noticeable in practice (a single 3.x call from a particular 3.x function from each module would be the worst case, for all subsequent calls it would be the same as before).

**Comment by joshcooper** [comment]
> "not found" in 4.x. is cached and quickly resolved the next time.

It's cached for the environment lifetime? PE only enables unlimited environment timeout when code manager is enabled, which is most, but not all installations. So this would be a perf reduction for those that don't?

**Comment by ryanycoleman** [comment]
Has this been run by a large Puppetfile? I'm thinking ~1000 modules with a 70% Forge/Git emphasis. Our TAM team might have a few ready-to-go examples shared by customers for testing.

**Comment by kris-bosland** [comment]
Hi @hlindberg, with the 5.5.x branch being cut, please retarget that branch.  Thanks!

**Comment by hlindberg** [comment]
Will retarget (@kris-bosland )

@joshcooper The 4.x loaders cache for the system part (things in the puppet runtime) has the lifecycle of the Ruby runtime, the remaining has the same lifecycle as the environment they operate in.  A first time call from a module to a 3.x function will first see if there is a 4.x version and since it is not loaded it will search - the search builds and caches an index of all files that are loadable (once per module per env life), and then consults this index if there is a match of function-name to file-to-load. Worst case if what is being looked for is a 3.x function then the first time that function is called there will be roughly one hash lookup per module on the module path (i.e. no file system search as that is only once per module and triggered on the very first time there is a search for any function in that module). The next call to the same function will get a cache hit telling the search that there is no such 4.x function (== same as before the change). Thus, it is only for the first time a 3.x function is called that the search is number-of-modules-not-on-modules-dependency-list number of hash lookups slower. By far, the number of function calls are to 4.x functions in puppet. The worst case would be if a module calls a very large number of different 3.x functions once - but that is unlikely in practice since there simply are not that many different functions to call.

When using env timeout 0 the most expensive part is the once per module scan for candidates-to-load files which takes place irrespective of this change. There is the risk that if a configuration was perfect (all modules have dependencies in their metadata) there would then be one module scan per module that would otherwise not have been scanned (because they would never have been visited). That only occurs once per environment life though. 

Our benchmark (in puppet source) uses 100 modules and a mix of modules with and without declared dependencies and with calls to both top scoped functions (requiring a search) and namespaces function (not requiring a search of all modules). We do not have any 3.x function calls in the mix - hence the speculation of what the change means for those. For the 4.x calls we see that the change is close to the margin of error in running the benchmark. The benchmark runs with env timeout 0.

If we merge this and see during performance testing that it is indeed bad in practice, the change back is simple.

**Comment by joshcooper** [comment]
> it is only for the first time a 3.x function is called that the search is number-of-modules-not-on-modules-dependency-list number of hash lookups slower.

Since a significant number of customers do not use unlimited environment timeout, my question from before still stands. This would be a perf reduction?

> By far, the number of function calls are to 4.x functions in puppet. 

I'm not sure I follow. There are large numbers of 3.x functions in modules, e.g. https://github.com/puppetlabs/puppetlabs-puppetdb/tree/master/lib/puppet/parser/functions, https://github.com/puppetlabs/puppetlabs-apache/tree/master/lib/puppet/parser/functions, https://github.com/puppetlabs/puppetlabs-mysql/tree/master/lib/puppet/parser/functions, https://github.com/puppetlabs/puppetlabs-sqlserver/tree/master/lib/puppet/parser/functions, ...

> We do not have any 3.x function calls in the mix - hence the speculation of what the change means for those.

Please add some. We should be able to quantify what the perf impact will be before merging this.

**Comment by pcarlisle** [comment]
+1 to adding in 3x functions for perf testing, it shouldn't be that hard and then we can know for sure how things are affected. I think the majority of functions in production puppet are probably still 3x.

**Comment by joshcooper** [comment]
Using @pcarlisle's full_catalog benchmark (#6676), which pulls in a number of modules that use 3.x functions, the `large` catalog takes about 45% longer to compile. Each run of the benchmark creates a new environment.

[before using 5.5.x](https://gist.github.com/joshcooper/1e792ef3d1b687e2566127b8ba094d0b)
```
$ bx rake  benchmark:full_catalog:run ITERATIONS=50 SIZE=large
...
                 user     system      total        real
Run 1      /var/folders/8m/d6146zxd6bv_3h8y4ykvvxh40000gn/T/full_catalog20180313-70154-k61o7j/environments/perf_control/modules/postgresql/lib/puppet/parser/functions/postgresql_acls_to_resources_hash.rb:33: warning: constant ::Fixnum is deprecated
/var/folders/8m/d6146zxd6bv_3h8y4ykvvxh40000gn/T/full_catalog20180313-70154-k61o7j/environments/perf_control/modules/influxdb/templates/influxdb.conf.erb:223: warning: constant ::Fixnum is deprecated
  1.710000   0.040000   1.750000 (  1.753078)
...
> total:    89.960000   1.990000  91.950000 ( 92.502201)
> avg:       1.799200   0.039800   1.839000 (  1.850044)
```

[after with this PR merged](https://gist.github.com/joshcooper/a6826fad6d8f81aae3d6afe812bf165f):

```
$ bx rake  benchmark:full_catalog:run ITERATIONS=50 SIZE=large
...
                 user     system      total        real
Run 1      /var/folders/8m/d6146zxd6bv_3h8y4ykvvxh40000gn/T/full_catalog20180313-87646-167agg7/environments/perf_control/modules/postgresql/lib/puppet/parser/functions/postgresql_acls_to_resources_hash.rb:33: warning: constant ::Fixnum is deprecated
/var/folders/8m/d6146zxd6bv_3h8y4ykvvxh40000gn/T/full_catalog20180313-87646-167agg7/environments/perf_control/modules/influxdb/templates/influxdb.conf.erb:223: warning: constant ::Fixnum is deprecated
  2.540000   0.040000   2.580000 (  2.581631)
...
> total:   130.510000   2.110000 132.620000 (133.108072)
> avg:       2.610200   0.042200   2.652400 (  2.662161)
```

**Comment by hlindberg** [comment]
Super thanks @joshcooper for running that - clearly that degradation is not an acceptable price to pay for the feature "making all modules visible" and that makes me not want to merge this for 5.5.0.  Thomas and I have spent time today coming up with alternative implementations (we still want the feature "making all visible", but it needs to be done a different way. We concluded that the problem is IO bound. We have one idea that can be explored, but it needs a simple benchmark that measures the worst case and we need to optimize for that as we believe that will also address the 45% time diff shown in the full scale benchmark. 

With that I am closing this PR. Depending on how the continued work goes we may want to come back with this feature in 5.5.1 if it is considered backwards compatible.
The idea in short is to make 4.x loaders also work on 3.x function paths so that priority is 4.x before 3.x per module rather than per all modules on the modules path. We would still load 3.x exactly the same way (they become methods on Scope  etc. which in itself is a bad thing for JRuby/JVM optimization - but addressing requires a breaking change - for puppet 6 perhaps).

**Pull request closed without merging**
