### PR TITLE
(PUP-5135)(PUP-5137)(PUP-5139) Add AIX node configs

### PR DESCRIPTION
**Pull request by whopper**

### CODE REVIEW

**Comment by johnduarte** [comment]
:+1:  lgtm

**Comment by MikaelSmith** [comment]
Need .yaml extension.

**Comment by MikaelSmith** [comment]
Not sure about the Ruby failure on Windows, that's worrisome.

**Comment by whopper** [comment]
@MikaelSmith @johnduarte whoops, updated with yaml extension (in each of these three PRs)

**Comment by MikaelSmith** [comment]
AppVeyor failure is unrelated.

**Pull request merged**
