### PR TITLE
(PUP-5037) Fixed `service puppetmaster status` incorrectly returning "puppet dead but subsys locked" on RHEL and derivatives

### PR DESCRIPTION
**Pull request by hamidnazari**
Details here: https://tickets.puppetlabs.com/browse/PUP-5037

### CODE REVIEW

**Comment by kylog** [comment]
@haus this looks reasonable to me, but I don't have a ton of context here. Thoughts?

**Comment by haus** [comment]
This looks reasonable to me, but the commit message is a little thin. @hamidnazari could you add a little bit from the bug to the commit message so that it is clear why this change is needed and what the issue is?

**Comment by hamidnazari** [comment]
Back to you @haus.

**Comment by haus** [comment]
@kylog this looks like a sane change to me.

**Pull request merged**
