### PR TITLE
(PUP-7695) Update `parallel:spec` rake task to pass extra args to RSpec

### PR DESCRIPTION
**Pull request by Magisus**
This commit updates the existing `parallel:spec` rake task to accept
arguments to be passed on to RSpec. These will primarily be used in CI
to correctly generate test result log files.

### CODE REVIEW

**Comment by MosesMendoza** [comment]
Instead of creating a new rake tasks, can we just update the original task to do the new things by default, or just update the CI job to specify the appropriate args? It would be ideal to just have one rake task to run the parallel specs

**Comment by Magisus** [comment]
Yes, we can. I didn't at first, to help local testing, but there is no reason we can't just do the argument passing in Jenkins instead of in a wrapper task. I'll update.

**Comment by Magisus** [comment]
@jcoconnor I've updated my puppet PR to remove the `ci:parallel_spec` wrapper task, instead JJB should now invoke `parallel:spec` directly something like this:
```
LOG_SPEC_ORDER=true bundle exec rake "parallel:spec[4,1000,'-rrspec/legacy_formatters','-ryarjuf','-fJUnit','-oresult.xml','-fp']"
```

**Comment by Magisus** [comment]
This has been tested in CI using an invocation like above. Jenkins correctly consumes the XML output. For developer use, the experience of using the `parallel:spec` rake task is unchanged (though RSpec options may be specified now).

**Comment by jcoconnor** [comment]
@Magisus have been able to get Green runs on Linux and Windows builds with this.
So 👍

**Comment by jcoconnor** [comment]
For reference, the following ci-jobs builds appear to have been changed, so this change will need to be pushed to the equivalent puppet branches:
```
experimental_puppet_unit-ruby-win_4.10.x
experimental_puppet_unit-ruby-win_5.0.x
experimental_puppet_unit-ruby-win_master
experimental_puppet_unit-ruby_4.10.x
experimental_puppet_unit-ruby_5.0.x
experimental_puppet_unit-ruby_master
platform_puppet-cve_unit-ruby-win_CVE-2017-2295-4.10.x
platform_puppet-cve_unit-ruby_CVE-2017-2295-4.10.x
```

**Pull request merged**
