### PR TITLE
(PUP-11934) Use String#each_codepoint instead of deprecated String#codepoints

### PR DESCRIPTION
**Pull request by justinstoller**

### CODE REVIEW

**Comment by joshcooper** [comment]
Does `codepoints` produce the wrong results in newer JRuby?

**Comment by justinstoller** [comment]
No, but it prints a deprecation message to the log when it's called.

In MRI that usage was marked as deprecated in a previous version of Ruby and the documentation for it has been removed: https://ruby-doc.org/3.2.2/String.html#method-i-codepoints

**Comment by joshcooper** [comment]
@justinstoller will this need to target 7.x too? We think we're testing against 9.3 there, but we weren't sure if it issues the same deprecation warning?

**Comment by justinstoller** [comment]
It _can_ target 7.x, but it's only problematic in 8.x. (at least so far) JRuby started warning in 9.4.3 not 9.3.x. I don't know if they plan to backport that warning. Lemme know if you'd like it cherrypicked.

**Comment by justinstoller** [comment]
Rebased onto 7.x

**Comment by joshcooper** [comment]
Closing and reopening to rekick checks

**Review by joshcooper — APPROVED** [review]

**Pull request merged**
