### PR TITLE
WIP adding support for running spec tests against jruby in travis

### PR DESCRIPTION
**Pull request by ericldelaney**

### CODE REVIEW

**Comment by ericldelaney** [comment]
Finished in 20 minutes 16 seconds
22466 examples, 406 failures, 42 pending

**Comment by ericldelaney** [comment]
Finished in 19 minutes 14 seconds
22351 examples, 293 failures, 42 pending

**Comment by ericldelaney** [comment]
Previous commit took care of all the obvious fork cases.

Finished in 31.22 seconds (files took 8.76 seconds to load)
Finished in 18 minutes 47 seconds
22269 examples, 221 failures, 57 pending

**Comment by ericldelaney** [comment]
previous commit took care of tests that require SSL things

Finished in 21.68 seconds (files took 6.1 seconds to load)
Finished in 18 minutes 54 seconds
22113 examples, 73 failures, 58 pending

**Comment by ericldelaney** [comment]
Now at

Finished in 34.79 seconds (files took 8.08 seconds to load)
Finished in 20 minutes 1 second
22101 examples, 66 failures, 58 pending

**Comment by ericldelaney** [comment]
Finished in 23.42 seconds (files took 6.74 seconds to load)
Finished in 15 minutes 48 seconds
22101 examples, 64 failures, 58 pending

**Comment by ericldelaney** [comment]
Finished in 30.42 seconds (files took 6.69 seconds to load)
Finished in 17 minutes 14 seconds
22096 examples, 51 failures, 58 pending

**Comment by ericldelaney** [comment]
Finished in 2 minutes 17.1 seconds (files took 8.44 seconds to load)
Finished in 18 minutes 29 seconds
22096 examples, 33 failures, 74 pending

**Comment by ericldelaney** [comment]
@melissa @jhelwig  someone will have to take over this PR, this is the latest of what I have done.

**Comment by jhelwig** [comment]
New WIP PR: https://github.com/puppetlabs/puppet/pull/6790

**Pull request closed without merging**
