### PR TITLE
(PUP-4237) Add puppet-agent gem provider

### PR DESCRIPTION
**Pull request by branan**
This is a rebase of #3728 against the stable branch so it can be included in Puppet 4.0

It includes cherry-picks of PUP-4191 and PUP-4203 (from #3708), since this code was originally written assuming they would be merged into 4.0 but they ended up in 4.1

### CODE REVIEW

**Comment by branan** [comment]
To be more specific, I cherry-picked the fixed up versions of the #3708 commits that @melissa merged into master.

**Comment by branan** [comment]
@joshcooper on the original PR you had asked about windows support. What is needed to make that happen?

**Comment by branan** [comment]
Trivially it's "add another provider", but that really stinks. (having `puppet_gem_win` in addition to this one). I'm not aware of a way to declare a command is used/needed based on a fact. We could flag both the windows and linux commands as optional and implement the failure logic ourselves if neither is found, but that also feels kinda hacky to me :/

Is there an existing way of handling this sort of situation?

**Comment by branan** [comment]
I still need to verify proper functioning on windows, just pushed up the code to my working branch

**Comment by MikaelSmith** [comment]
:+1: This looks like it should work.

**Comment by MikaelSmith** [comment]
@branan Let me know when you've verified on Windows?

**Comment by branan** [comment]
@MikaelSmith looks like it works.

Windows firewall blocked Gem from the network, but that's a different problem that I'll talk to either RE or the windows team about.

**Comment by jhoblitt** [comment]
Is there any chance of also getting this functionality in a 3.x release?

**Comment by kylog** [comment]
@jhoblitt puppet 3.x doesn't have the same packages that bundle ruby, so the straight gem provider should work.

**Comment by ferventcoder** [comment]
@kylog I wonder if @jhoblitt is specifically interested in the uninstall_options that was introduced to the gem provider at https://github.com/branan/puppet/commit/70a7e2870fa684a9642c6f110d407d20c47f1224

**Pull request merged**
