### PR TITLE
(PUP-9268) Revert earlier merge to 5.5.x

### PR DESCRIPTION
**Pull request by hlindberg**
This reverts merge commit e0b7dcc5e0706534448faf0c06dc0edb42ef9b1e where PUP-6964 was merged to 5.5.x.
We are reverting this due to backwards incompatibility loading 3x functions with illegal constructs (methods inside and outside of the function body).

When merging this to master the revert should again be reverted. (PUP-9137) Revert test for 4x load after 3.x load due to revert of 6964

This reverts a test that asserts that a 4.x load following a 3.x load of a 3.x function does not again load the 3.x function. This test needs to be reverted since PUP-6964 is reverted and it is not possible to load 3.x. functions with the 4.x loaders after that revert.

### This change should not be merged to master (i.e. 6.0.z and onward) since the behavior of PUP-6964 and PUP-9137 should be intact there.

### CODE REVIEW

**Comment by hlindberg** [comment]
Trying to prepare the reverted-revert when merging this into 6.0.x ran into conflicts. Someone please make a clean merge first before continuing with merging this PR.
There was a conflict in `lib/puppet/provider/package/dnf.rb` in the merge I attempted.

**Comment by hlindberg** [comment]
Travis complains about a warning - it is actually a fixed warning that is reverted - it will be ok again when this revert is reverted for 6.0.z

**Comment by branan** [comment]
@hlindberg I think we still need that warning to be fixed in 5.5.x, otherwise travis will fail every time we open a PR against 5.5.x in the future.

That should probably just be another commit, so it won't be brought along when we revert the main change of this PR.

**Comment by joshcooper** [comment]
nit, can you change the ticket reference to https://tickets.puppetlabs.com/browse/PUP-9268, since that's what we're "fixing" in 5.5.x while PUP-6964 has already been released?

**Comment by hlindberg** [comment]
When reverting this for 6.0.x, do not revert the maint commit.

**Pull request merged**
