### PR TITLE
Update documentation for Puppet::Util::Execution::execute

### PR DESCRIPTION
**Pull request by dalen**

### CODE REVIEW

**Comment by peterhuene** [comment]
@dalen Thanks for the contribution!  Think we could squash this into a single commit about "fixing documentation for Puppet::Util::Execution?"

**Comment by dalen** [comment]
@peterhuene done

**Comment by peterhuene** [comment]
@dalen Sorry, one last update to the commit: could you prefix with `(docs)` instead of maint?  Will merge after that.

**Comment by dalen** [comment]
done

**Comment by peterhuene** [comment]
@dalen Thanks again for the contribution!

**Pull request merged**
