### PR TITLE
(PUP-10408) Remove deprecated '-noidme' flag from pkgdmg package provider

### PR DESCRIPTION
**Pull request by cmiconi**
The pkgdmg package provider uses the '-noidme' flag with hdiutil, which was deprecated in macOS 10.15. See man hdiutil for more information. In macOS 10.15 the '-noidme' flag causes hdiutil to output a deprecation warning, which then causes pkgdmg to fail to parse the plist xml that hdiutil generates, which then causes the package installation to fail in puppet.

This change removes the '-noidme' flag from pkgdmg in order to prevent the deprecation warning from hdiutil, and restore functionality to pkgdmg in macOS 10.15 and above. Additonally, after reviewing the man page for hdiutil in macOS 10.14, it seems the '-noidme' flag is unnecessary for older versions of macOS as hdiutil appears to not perform idme actions by default. This change also removes the '-noidme' flag from the pkgdmg test in order to bring it up-to-date with the change in pkgdmg.

### CODE REVIEW

**Comment by joshcooper** [comment]
Seems good to me, though to get into a 5.5.x release, could you retarget the base branch to 5.5.x?

**Comment by cmiconi** [comment]
Base branch has been set to 5.5.x. FYI this also affects the 6.x.x branch as well.

**Comment by GabrielNagy** [comment]
@cmiconi you also need to rebase your commit on top of the 5.5.x branch, in addition to changing the base branch on GitHub. Otherwise you'd pull all master commits on top of 5.5.x. Let me know if you need any help with that.

**Comment by lucaskanashiro** [comment]
My contribution was trivial and I can't access the provided url: http://docs.puppet.com/community/trivial_patch_exemption.html

**Comment by mwaggett** [comment]
hey @lucaskanashiro, here's the updated url to our trivial patch exemption policy: https://puppet.com/community/trivial-patch-exemption-policy/
Sorry about that!

**Comment by cmiconi** [comment]
Closing this pull request as it is now superseded by #8081.

**Pull request closed without merging**
