### PR TITLE
(PUP-5553) Add systemd as a default service provider for Ubuntu 15.10

### PR DESCRIPTION
**Pull request by joshcooper**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
You didn't follow through with doing `>=`?

**Comment by joshcooper** [comment]
Yeah, I looked for other examples of doing that and couldn't find any. But maybe I missed it?

**Comment by MikaelSmith** [comment]
None I'm aware of either. :+1:

**Comment by joshcooper** [comment]
I'm running this through acceptance to make sure it resolves the two acceptance failures.

**Comment by kylog** [comment]
Yeah looking at how defaultfor is handled in provider.rb, there isn't support for such a `>=` construct yet. The defaultfor params are fed into a dochook as well, so not sure how exactly that would work. 

And this is pretty easy to do every six months :)

:+1:

**Comment by joshcooper** [comment]
Verified we can manage ufw service on wily with this change:

```
root@yunvikxws2bbrl3:~# /opt/puppetlabs/bin/puppet resource service ufw
service { 'ufw':
  ensure => 'stopped',
  enable => 'true',
}
root@yunvikxws2bbrl3:~# /opt/puppetlabs/bin/puppet resource service ufw ensure=running
Notice: /Service[ufw]/ensure: ensure changed 'stopped' to 'running'
service { 'ufw':
  ensure => 'running',
}
root@yunvikxws2bbrl3:~# systemctl status ufw -o short
● ufw.service - Uncomplicated firewall
   Loaded: loaded (/lib/systemd/system/ufw.service; enabled; vendor preset: enabled)
   Active: active (exited) since Tue 2015-12-15 15:15:21 PST; 3s ago
  Process: 32745 ExecStart=/lib/ufw/ufw-init start quiet (code=exited, status=0/SUCCESS)
 Main PID: 32745 (code=exited, status=0/SUCCESS)

Dec 15 15:15:21 yunvikxws2bbrl3 systemd[1]: Starting Uncomplicated firewall...
Dec 15 15:15:21 yunvikxws2bbrl3 systemd[1]: Started Uncomplicated firewall.
root@yunvikxws2bbrl3:~# /opt/puppetlabs/bin/puppet resource service ufw ensure=stopped
Notice: /Service[ufw]/ensure: ensure changed 'running' to 'stopped'
service { 'ufw':
  ensure => 'stopped',
}
root@yunvikxws2bbrl3:~# systemctl status ufw -o short
● ufw.service - Uncomplicated firewall
   Loaded: loaded (/lib/systemd/system/ufw.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Tue 2015-12-15 15:15:31 PST; 2s ago
  Process: 32761 ExecStop=/lib/ufw/ufw-init stop (code=exited, status=0/SUCCESS)
  Process: 32745 ExecStart=/lib/ufw/ufw-init start quiet (code=exited, status=0/SUCCESS)
 Main PID: 32745 (code=exited, status=0/SUCCESS)

Dec 15 15:15:21 yunvikxws2bbrl3 systemd[1]: Starting Uncomplicated firewall...
Dec 15 15:15:21 yunvikxws2bbrl3 systemd[1]: Started Uncomplicated firewall.
Dec 15 15:15:31 yunvikxws2bbrl3 systemd[1]: Stopping Uncomplicated firewall...
Dec 15 15:15:31 yunvikxws2bbrl3 ufw-init[32761]: Skip stopping firewall: ufw (not enabled)
Dec 15 15:15:31 yunvikxws2bbrl3 systemd[1]: Stopped Uncomplicated firewall.
```

There's a secondary issue about puppet not being able to manage its own service, filed as PUP-5613.

**Pull request merged**
