### PR TITLE
(PUP-8766) device $LOAD_PATH and environment handling

### PR DESCRIPTION
**Pull request by DavidS**

### CODE REVIEW

**Comment by DavidS** [comment]
This is only a first draft of the changes that seem to be necessary to get this fixed. I've done only cursory manual testing, and will do a full manual test, and update the unit tests before submitting this for a merge.

@joshcooper I'd appreciate feedback on this approach, if this matches what you expected from the conversation in the ticket, and if you see anything that needs improvement

**Comment by DavidS** [comment]
The log below shows manual testing how the current `puppet device` is loading the spinner device from the agent's load path, and then the patched version is correctly trying pluginsync and then loads from the device's cache: 

```
david@davids:~/git/puppetlabs-test_device$ cat /home/david/.puppetlabs/opt/puppet/cache/lib/puppet/util/network_device/spinner/device.rb
raise 'agent'

david@davids:~/git/puppetlabs-test_device$ cat /home/david/.puppetlabs/opt/puppet/cache/devices/spinner/lib/puppet/util/network_device/spinner/device.rb
raise 'device'

david@davids:~/git/puppetlabs-test_device$ bundle exec puppet device --target spinner --deviceconfig ./device.conf --verbose --resource spinner 500 
Error: Can't load spinner for spinner: agent
david@davids:~/git/puppetlabs-test_device$ export PUPPET_GEM_VERSION='file:///home/david/git/puppet'
david@davids:~/git/puppetlabs-test_device$ bundle exec puppet device --target spinner --deviceconfig ./device.conf --verbose --resource spinner 500 
Info: Retrieving pluginfacts
Error: /File[/home/david/.puppetlabs/opt/puppet/cache/devices/spinner/facts.d]: Failed to generate additional resources using 'eval_generate': Failed to open TCP connection to puppet:8140 (Connection refused - connect(2) for "puppet" port 8140)
Error: /File[/home/david/.puppetlabs/opt/puppet/cache/devices/spinner/facts.d]: Could not evaluate: Could not retrieve file metadata for puppet:///pluginfacts: Failed to open TCP connection to puppet:8140 (Connection refused - connect(2) for "puppet" port 8140)
Info: Retrieving plugin
Error: /File[/home/david/.puppetlabs/opt/puppet/cache/devices/spinner/lib]: Failed to generate additional resources using 'eval_generate': Failed to open TCP connection to puppet:8140 (Connection refused - connect(2) for "puppet" port 8140)
Error: /File[/home/david/.puppetlabs/opt/puppet/cache/devices/spinner/lib]: Could not evaluate: Could not retrieve file metadata for puppet:///plugins: Failed to open TCP connection to puppet:8140 (Connection refused - connect(2) for "puppet" port 8140)
Error: Can't load spinner for spinner: device
david@davids:~/git/puppetlabs-test_device$ 
```

**Comment by DavidS** [comment]
The downside here is that puppet device is now ignoring `--libdir` on the CLI totally, and that even for "local" usecases pluginsync is executed.

**Comment by tphoney** [comment]
its really hard to comment on this, the approach looks sane. Not being able to use the --libdir feels like a blocker

**Comment by DavidS** [comment]
@tphoney about to wrap-up a second iteration of this, fixing the libdir issue

**Comment by DavidS** [comment]
There we go.

PS: the "force-pushed" link also includes the changes on the 5.5.x branch since I rebased the entire thing.

**Comment by DavidS** [comment]
This is now ready for final reviews.

**Pull request merged**
