### PR TITLE
(maint) Extract selinux from puppet

### PR DESCRIPTION
**Pull request by melissa**
This code is being migrated into a separate module. See PUP-8577 for
more details.

### CODE REVIEW

**Comment by melissa** [comment]
This cannot be merged until we have promoted the module into puppet-agent

**Comment by vinzent** [comment]
@melissa 

* https://github.com/puppetlabs/puppetlabs-selinux_core only contains the types but no providers
* the PR delets the unit tests but not the actual providers

were the lib/puppet/provider/selmodule/...  just missed to be moved?

I wanted to create a PR to forward port https://github.com/puppetlabs/puppet/pull/6883 to puppetlabs-selinux_core

**Comment by melissa** [comment]
🤦‍♂️  yup, I somehow managed to miss the providers. I'll get those in asap

**Comment by melissa** [comment]
@vinzent the providers are now in the selinux_core module! Thanks for calling that out!

**Comment by melissa** [comment]
Oh, also, this is blocked on https://github.com/puppetlabs/puppet-agent/pull/1456

**Comment by melissa** [comment]
Above PR has been merged in, so this is technically unblocked, but we should wait until puppet-agent#master passes CI

**Comment by joshcooper** [comment]
@melissa the last passing puppet-agent#eab3f2047ebdfd2908ef3231ff440616046b65a4 contains there selinux module component json file, but the .rb file is missing and the puppet-agent projects needs to include the component. Do you want to fix that? I can also if you're in the middle of something.

**Comment by melissa** [comment]
I fixed the above comment with https://github.com/puppetlabs/puppet-agent/pull/1465, which is a part of the latest passing sha of puppet-agent#master (puppet-agent 5.5.3.333.g3896152)

**Pull request merged**
