### PR TITLE
(PUP-7102) Log a warning when environment path has permission problems

### PR DESCRIPTION
**Pull request by thallgren**
Prior to this PR, a permission problem in one of the directories in
an `environmentpath` would go unnoticed. The directory would simply be
deemed invalid and excluded from the path. This would later lead to
an `EnvironmentNotFound` exception being raised with no clue as to why
the path wasn't included.

This PR ensures that the directory with permission problems is logged
as a warning (once). The warning can be silenced using a `disable_warnings`
setting that includes 'permission_denied'.

### CODE REVIEW

**Comment by hlindberg** [comment]
Didn't we say on the ticket that this should be an error? I wonder if there is a legit usecase where some users should skip over unreachable environments only to find one later in the envpath that they can access. Sounds like a sure way to screw things up. Most likely users don't have such a setup, so it always ends with "not found". Then, when on an agent doing 'puppet agent -t', you don't get to see the warning, so user still has no clue to the "not found" without going digging in the logs.

**Comment by hlindberg** [comment]
appveyor also has a problem with this PR it seems.

**Comment by thallgren** [comment]
The ticket description and acceptance criteria only mentions that messages indicating that parts of the environmentpath is inaccessible should make it into the log. Looking deeper I discovered your comment about always make this an error. If that's concluded, then it would be great if the acceptance criteria was also updated.

Interesting to see that a file name containing asterisks gives an EINVAL error on Windows. I'll add a check for that.

**Comment by thallgren** [comment]
Succeeded by [PR-5650[(/puppetlabs/puppet/pull/5650).

**Pull request closed without merging**
