### PR TITLE
Revert "Merge pull request #8291 from joshcooper/status_extra_headers_10617"

### PR DESCRIPTION
**Pull request by joshcooper**
This reverts commit 93fce9135e750c86bc57d64eed3bdc13f583a996, reversing
changes made to dd152daef0d550b26453c31a22a05f248d3c96ec.

### CODE REVIEW

**Comment by joshcooper** [comment]
Before reverting:

```
$  rm -rf /tmp/regression && bx puppet ssl bootstrap --ssldir /tmp/regression --server_list gold-quality.delivery.puppetlabs.net
Error: Failed to initialize SSL: The CA certificates are missing from '/tmp/regression/certs/ca.pem'
Error: Run `puppet agent -t`
Error: Could not select a functional puppet master from server_list: 'gold-quality.delivery.puppetlabs.net'
Info: Will try again in 120 seconds.
```

After reverting:

```
$ rm -rf /tmp/regression && bx puppet ssl bootstrap --ssldir /tmp/regression --server_list gold-quality.delivery.puppetlabs.net
Info: csr_attributes file loading from /Users/josh/.puppetlabs/etc/puppet/csr_attributes.yaml
Info: Creating a new SSL certificate request for localhost
Info: Certificate Request fingerprint (SHA256): B3:93:5F:7C:ED:BB:C2:33:CC:F8:71:4D:1B:C7:5D:65:88:53:C4:B0:91:A4:CB:FB:F8:58:3B:DF:1A:B7:F3:1F
Info: Certificate for localhost has not been signed yet
Couldn't fetch certificate from CA server; you might still need to sign this agent's certificate (localhost).
Info: Will try again in 120 seconds.
```

**Comment by joshcooper** [comment]
Hold off on merging, I think there's an easy fix for this.

**Comment by justinstoller** [comment]
So.. the service construct requires that SSL be fully set up and so can't be used in its current form for calls that might happen during bootstrapping our SSL infrastructure?

Is there a toggle we can pass to the service when constructed to allow it to make unsecured calls?

**Comment by joshcooper** [comment]
Yep exactly, I accidentally dropped the SSLContext when switching over. It should be fixed in https://github.com/puppetlabs/puppet/pull/8302. Closing this.

**Pull request closed without merging**
