### PR TITLE
(PUP-6430) Add Fedora 24 support for DNF

### PR DESCRIPTION
**Pull request by petems**
* Also add spec for default provider-ness

Closes #5052 and re-targets against stable

### CODE REVIEW

**Comment by geoffnichols** [comment]
👍

**Comment by shermdog** [comment]
I'd like to propose we change the provider to default to DNF for >= 22. If and when there is a new package management tool we can limit the scope then :)

**Comment by petems** [comment]
@shermdog Agreed for Fedora 25, but that'll take time and review before someone extends the `defaultfor` method to accept operators, but I'll open a ticket for that for the future 👍

**Comment by petems** [comment]
Just opened https://tickets.puppetlabs.com/browse/PUP-6452 for that 👍

**Pull request merged**
