### PR TITLE
(PUP-7966) Enable Coverity scanning triggered by Travis

### PR DESCRIPTION
**Pull request by BillWeiss**
Don't merge this yet, please. I'm working on getting Coverity scanning working and this PR is the easy way to test it.

Eventually, the plan is for Coverity to scan every time there's a change to the coverity_scan branch. This isn't great, but it's how they want us to configure it, and it's what we get for free.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
This may need to be kept as a separate branch, that's what I've done in other repos.

Coverity requires some config that might be incompatible with how we normally run CI.

**Comment by BillWeiss** [comment]
My thought is to merge this into master, then cut a branch called coverity_scan? Or I could just go straight to that branch and... something. I dunno.

**Comment by MikaelSmith** [comment]
I keep the coverity-specific config on a separate branch, and merge to it from master periodically.

**Comment by BillWeiss** [comment]
Nevermind. I'm going to make a coverity_scan branch directly instead of PRing it.

**Pull request closed without merging**
