### PR TITLE
(PUP-8815) Remove mount type and provider

### PR DESCRIPTION
**Pull request by joshcooper**

### CODE REVIEW

**Comment by joshcooper** [comment]
Blocked on https://github.com/puppetlabs/puppet-agent/pull/1487

**Comment by joshcooper** [comment]
jenkins please test this on debian9-64a,fedora27-64a,sles12-64a

**Comment by joshcooper** [comment]
jenkins please test this on debian9-64a,fedora27-64a,sles12-64a

**Comment by melissa** [comment]
Checked puppet-agent 5.99.1.90.g51dad18-1
```
[root@jnnhct4u4gw0lv6 ~]# tree /opt/puppetlabs/puppet/vendor_modules/mount_core/
/opt/puppetlabs/puppet/vendor_modules/mount_core/
├── CHANGELOG.md
├── Gemfile
├── lib
│   └── puppet
│       ├── provider
│       │   ├── mount
│       │   │   └── parsed.rb
│       │   └── mount.rb
│       └── type
│           └── mount.rb
├── metadata.json
├── Rakefile
├── README.md
├── REFERENCE.md
└── spec
    ├── acceptance
    │   ├── lib
    │   │   └── mount_utils.rb
    │   ├── nodesets
    │   │   └── default.yml
    │   └── tests
    │       ├── defined_spec.rb
    │       ├── destroy_spec.rb
    │       ├── modify_spec.rb
    │       ├── mounted_spec.rb
    │       └── query_spec.rb
    ├── default_facts.yml
    ├── fixtures
    │   └── unit
    │       └── provider
    │           └── mount
    │               ├── mount-output.aix.txt
    │               └── parsed
    │                   ├── aix.filesystems
    │                   ├── aix.mount
    │                   ├── darwin.mount
    │                   ├── freebsd.fstab
    │                   ├── freebsd.mount
    │                   ├── hpux.mount
    │                   ├── linux.fstab
    │                   ├── linux.mount
    │                   ├── netbsd.fstab
    │                   ├── netbsd.mount
    │                   ├── openbsd.fstab
    │                   ├── openbsd.mount
    │                   ├── solaris.fstab
    │                   └── solaris.mount
    ├── integration
    │   └── provider
    │       └── mount_spec.rb
    ├── lib
    │   └── puppet_spec
    │       └── files.rb
    ├── shared_behaviours
    │   └── all_parsedfile_providers.rb
    ├── spec_helper_acceptance.rb
    ├── spec_helper_local.rb
    ├── spec_helper.rb
    └── unit
        ├── provider
        │   ├── mount
        │   │   └── parsed_spec.rb
        │   └── mount_spec.rb
        └── type
            └── mount_spec.rb

24 directories, 41 files
```

**Pull request merged**
