### PR TITLE
PUP-8949 use install_options with 'latest' methods

### PR DESCRIPTION
**Pull request by tkishel**
Prior to this commit ...

The 'latest_with_new_pip' and 'latest_with_old_pip methods' (called by the
'latest' method) failed to execute `pip install` with the resource's
`install_options` attribute, potentially resulting in a lack of idempotency.

With this commit ...

Any 'install_options' are applied whenever 'install' is executed.

### CODE REVIEW

**Comment by mihaibuzgau** [comment]
jenkins please test this on debian8-64a,debian8-32a,debian9-64a,debian9-32a,fedora28-64a,fedora29-64a,osx1012-64a,osx1013-64a,osx1014-64a,redhat5-64a,centos6-64a,centos6-32a,redhat7-64a,redhat8-64a,redhatfips7-64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,sles15-64a,solaris10-64a,solaris114-64a,ubuntu1404-64a,ubuntu1404-32a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1804-64a,windows2016-64a,windows2019-64a

**Comment by ciprianbadescu** [comment]
looks good, please add rspec/acceptance tests

**Comment by tkishel** [comment]
I've added unit tests, but would need help with acceptance tests as none exist now.

**Comment by ciprianbadescu** [comment]
We are generally missing acceptance tests for package managers ...
I had similar issue for yum/rpm and I created some basic tests: https://github.com/puppetlabs/puppet/blob/90fa5152fa5c92e7d499fe0d38c10636c7d7e737/acceptance/tests/provider/package/rpm_ensure_install_multiversion_package.rb
Pls check and let me know if more help is needed.

**Comment by tkishel** [comment]
I added a commit with potential acceptance tests. 
I did not run them yet, I need to learn/setup them locally.

**Comment by tkishel** [comment]
I’ve added multiple acceptance tests. If the others need to be broken out
into another PR, or they need to be refactored, please let me know.
-- 
Tom Kishel

Senior Support Engineer
tom.kishel@puppet.com
Puppet. The shortest path to better software.

**Comment by tkishel** [comment]
There is a potential issue or two with PATH in our acceptance test environment ... documented in comments in `acceptance/tests/provider/package/gem.rb`

**Comment by tkishel** [comment]
I think this is done. I’ll submit a separate PR for gem acceptance tests, and post my findings regarding path issues in beaker.

**Comment by ciprianbadescu** [comment]
jenkins please test this on debian8-64a,debian8-32a,debian9-64a,debian9-32a,fedora28-64a,fedora29-64a,osx1012-64a,osx1013-64a,osx1014-64a,redhat5-64a,centos6-64a,centos6-32a,redhat7-64a,redhat8-64a,redhatfips7-64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,sles15-64a,solaris10-64a,solaris114-64a,ubuntu1404-64a,ubuntu1404-32a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1804-64a,windows2016-64a,windows2019-64a

**Pull request merged**
