### PR TITLE
(PUP-8733) Store full file path in LOADED_FEATURES in autoloader

### PR DESCRIPTION
**Pull request by pcarlisle**
The implementations of `require` in JRuby and MRI don't check the same
paths in `$LOADED_FEATURES`. Both check a version of the relative path, but
MRI checks with the file extension and JRuby checks without. Both check the
absolute path, so if we save that instead we should get consistent behavior
across platforms.

### CODE REVIEW

**Comment by pcarlisle** [comment]
I forked this from master this week, the branch is still only 4 commits behind.

**Comment by joshcooper** [comment]
The yum failure is bizarre... The test is should not be using `agent`, which was added in a5d1913bf6250dc8649d1198603412eb7c8a00e8. I think beaker has some logic to select the first host with the agent role, but idk... maybe the test ran with an older version of beaker... We should update the test to use the plural `agents` instead.

**Comment by pcarlisle** [comment]
jenkins please test this

**Comment by joshcooper** [comment]
Using the custom function in the description of https://tickets.puppetlabs.com/browse/PUP-8733, and I pointed the puppet submodule in puppetserver to your PR, but I'm still seeing the file type being redefined. It looks like the `file parameter passed to `mark_loaded` is sometimes a relative path, and that ends up getting cached the first time. Note I applied the following diff to print when we updated the `LOADED_FEATURES` hash:

```diff
diff --git a/lib/puppet/util/autoload.rb b/lib/puppet/util/autoload.rb
index fb8fdee43c..26f67ca250 100644
--- a/lib/puppet/util/autoload.rb
+++ b/lib/puppet/util/autoload.rb
@@ -37,7 +37,10 @@ class Puppet::Util::Autoload
     # into memory.
     def mark_loaded(name, file)
       name = cleanpath(name).chomp('.rb')
-      $LOADED_FEATURES << file unless $LOADED_FEATURES.include?(file)
+      unless $LOADED_FEATURES.include?(file)
+        Puppet.notice("LOADED FEATURE #{file}")
+        $LOADED_FEATURES << file
+      end
       loaded[name] = [file, File.mtime(file)]
     end
```

```
2018-05-23 15:39:52,340 INFO  [clojure-agent-send-pool-0] [puppetserver] Puppet LOADED FEATURE ./ruby/puppet/lib/puppet/type/file.rb
...
2018-05-23 15:40:21,540 INFO  [qtp977866504-36] [puppetserver] Puppet LOADED FEATURE /Users/josh/.puppetlabs/etc/code/environments/production/modules/foo/lib/puppet/parser/functions/owner_defed_after_require.rb
LOADING puppet/type/file.rb
2018-05-23 15:40:21,554 INFO  [qtp977866504-36] [puppetserver] Puppet Redefining file in Puppet::Type
/Users/josh/work/puppet-server/ruby/puppet/lib/puppet/type/file.rb:363: warning: already initialized constant CREATORS
/Users/josh/work/puppet-server/ruby/puppet/lib/puppet/type/file.rb:364: warning: already initialized constant SOURCE_ONLY_CHECKSUMS
2018-05-23 15:40:21,709 INFO  [qtp977866504-36] [puppetserver] Puppet owner_defed_after_require: enter
2018-05-23 15:40:21,709 INFO  [qtp977866504-36] [puppetserver] Puppet owner_defed_after_require: exit (false)
2018-05-23 15:40:21,900 INFO  [qtp977866504-36] [puppetserver] Puppet LOADED FEATURE ./ruby/puppet/lib/puppet/type/notify.rb
2018-05-23 15:40:22,013 INFO  [qtp977866504-36] [puppetserver] Puppet Compiled catalog for localhost in environment production in 0.78 seconds
2018-05-23 15:40:22,017 DEBUG [qtp977866504-36] [puppetserver] Puppet Puppet::Network::Format[msgpack]: feature msgpack is missing
2018-05-23 15:40:22,019 DEBUG [qtp977866504-36] [puppetserver] Puppet catalog supports formats: json pson yaml dot
2018-05-23 15:40:22,111 DEBUG [qtp977866504-35] [p.r.core] Processing :put /puppet/v3/report/localhost
2018-05-23 15:40:22,115 DEBUG [qtp977866504-35] [puppetserver] Puppet Evaluating match for Route /^\/puppet\//
2018-05-23 15:40:22,116 DEBUG [qtp977866504-35] [puppetserver] Puppet Evaluating match for Route /v3/
2018-05-23 15:40:22,117 DEBUG [qtp977866504-35] [puppetserver] Puppet Evaluating match for Route /^\/environments$/
2018-05-23 15:40:22,117 DEBUG [qtp977866504-35] [puppetserver] Puppet Did not match path ("/report/localhost")
2018-05-23 15:40:22,118 DEBUG [qtp977866504-35] [puppetserver] Puppet Evaluating match for Route /^\/environment\/[^\/]+$/
2018-05-23 15:40:22,119 DEBUG [qtp977866504-35] [puppetserver] Puppet Did not match path ("/report/localhost")
2018-05-23 15:40:22,120 DEBUG [qtp977866504-35] [puppetserver] Puppet Evaluating match for Route /.*/
2018-05-23 15:40:22,121 DEBUG [qtp977866504-35] [puppetserver] Puppet Evicting cache entry for environment 'production'
2018-05-23 15:40:22,121 DEBUG [qtp977866504-35] [p.s.j.puppet-environments] Removing environment 'production' from registry
2018-05-23 15:40:22,126 DEBUG [qtp977866504-35] [p.s.j.puppet-environments] Registering environment 'production'
2018-05-23 15:40:22,126 DEBUG [qtp977866504-35] [puppetserver] Puppet Caching environment 'production' (ttl = 0 sec)
2018-05-23 15:40:22,127 DEBUG [qtp977866504-35] [puppetserver] Puppet Applying settings catalog for sections reporting
2018-05-23 15:40:22,152 ERROR [qtp977866504-35] [puppetserver] Puppet Could not create resources for managing Puppet's files and directories in sections [:reporting]: no parameter named 'ensure'
/Users/josh/work/puppet-server/ruby/puppet/lib/puppet/util/errors.rb:157:in `fail'
/Users/josh/work/puppet-server/ruby/puppet/lib/puppet/type.rb:662:in `[]='
/Users/josh/work/puppet-server/ruby/puppet/lib/puppet/type.rb:2495:in `block in set_parameters'
org/jruby/RubyArray.java:1735:in `each'
/Users/josh/work/puppet-server/ruby/puppet/lib/puppet/type.rb:2489:in `set_parameters'
/Users/josh/work/puppet-server/ruby/puppet/lib/puppet/type.rb:2396:in `initialize'
/Users/josh/work/puppet-server/ruby/puppet/lib/puppet/type/file.rb:493:in `initialize'
/Users/josh/work/puppet-server/ruby/puppet/lib/puppet/resource.rb:461:in `to_ral'
```

**Comment by joshcooper** [comment]
I assume this is because my dev/puppetserver.conf contains relative paths:

```
    ruby-load-path: [./ruby/puppet/lib, ./ruby/facter/lib, ./ruby/hiera/lib]
```

whereas an install from a package contains:

```
    ruby-load-path: [
        "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby",
        "/opt/puppetlabs/puppet/cache/lib"
    ]
```

Can we expand the `ruby-load-path` settings when puppetserver starts so that we don't have to "expand" the path in the autoloader unnecessarily?

If I change `ruby-load-path` to use absolute paths, then it works ok:

```
2018-05-23 15:54:26,887 INFO  [qtp1008064330-35] [puppetserver] Puppet owner_defed_after_require: exit (true)
```

**Comment by pcarlisle** [comment]
Ok trying with expanded in autoloader

**Comment by pcarlisle** [comment]
jenkins please test this on redhat7-64,windows2012r2-64

**Comment by joshcooper** [comment]
The yum failure is due to a bad test introduced in a5d1913bf6250dc8649d1198603412eb7c8a00e8. It's calling `agent` outside of an `hosts/agents` loop. I think it fails on windows, because the test confines itself to a subset of linux and beaker creates methods based on roles. Presumably it doesn't meta-program an `agent` method if none are suitable.

**Comment by joshcooper** [comment]
jenkins please test this on redhat7-64a,windows2012r2-64a

**Comment by joshcooper** [comment]
The issue is that you have to append `a` for hosts to have the `agent` role. If no hosts have the role, then beaker never defines the method on the `TestCase`.

@McdonaldSeanp @branan could we update the PR testing logic to always include the `agent` role?

**Pull request merged**
