### PR TITLE
(PUP-6774) Fix incorrect call to `is_json_type` in Puppet::Resource

### PR DESCRIPTION
**Pull request by whopper**
The actual method name is `is_json_type?`

### CODE REVIEW

**Comment by whopper** [comment]
Verified {{environment/variables_refreshed_each_compilation.rb}} now passes:

```
      Test Suite: tests @ 2016-10-04 13:30:43 -0700

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 79.89 seconds
      Average Test Time: 79.89 seconds
              Attempted: 1
                 Passed: 1
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 1

      - Specific Test Case Status -

Beaker completed successfully, thanks.
```

**Comment by MosesMendoza** [comment]
👍

**Comment by branan** [comment]
Since this didn't get caught by unit tests, it seems like we might have a test coverage gap - is that something that should be fixed either in this or in another PR soon-ish?

**Comment by whopper** [comment]
@branan makes sense - I'd vote for a followup PR as this is just intended as an immediate fix to get CI passing again

**Comment by branan** [comment]
@whopper I'm cool with that

**Pull request merged**
