### PR TITLE
(docs) fix typo in indirector docs (van->and)

### PR DESCRIPTION
**Pull request by johnmccabe**
originally raised as puppetlabs/puppet-docs#702

### CODE REVIEW

**Comment by johnmccabe** [comment]
The appveyor failure appears to be unrelated?

**Comment by nfagerlund** [comment]
The appveyor failure is 100% unrelated. 

@johnmccabe, could I get you to change the `(maint)` to `(docs)` in the commit message? Thank you (and sorry for the extra fuss)!

**Comment by johnmccabe** [comment]
@nfagerlund done

**Comment by nfagerlund** [comment]
Rockin'. Note to observers: I'm going to bypass the CI checks since this is a one-word docs-only change, and it previously passed Travis.

**Comment by nfagerlund** [comment]
@johnmccabe Thx for following this all the way through the weird docs generation process! A magical journey.

**Comment by johnmccabe** [comment]
autogen all the way down :)

**Pull request merged**
