### PR TITLE
(docs)(PUP-5206) Note local filebucket default.

### PR DESCRIPTION
**Pull request by gguillotte**
PUP-5206 changes `puppet filebucket --local` to use $clientbucketdir by default instead of `$bucketdir`. Note this in the command's man page.

### CODE REVIEW

**Comment by joshcooper** [comment]
@kris-bosland can you review and merge?

**Comment by gguillotte** [comment]
@kris-bosland via chat:

> Hey Garrett, I think the sense on -local and -remote is incorrect in this doc update.  The clientbucketdir can be overridden with the bucket option, but the remote bucket cannot (or it's somewhere else).

For one, `--bucket` isn't even documented in this man page. So we should fix that, but probably not in this PR.

Also, if that's true, then the PUP-5206 acceptance criteria are wrong:

> The `--local` flag to the filebucket command should always use the `$clientbucketdir` setting for its operations

Looking at the commit and your comment, the acceptance criteria should instead be:

> The `--local` flag to the filebucket command uses the `$clientbucketdir` setting for its operations, unless overridden by the `--bucket` flag.

@jtappa @Magisus Can you confirm what I'm supposed to document here? This didn't seem complicated enough in the ticket to require pre-docs, but it sounds like there's either more going on or some information missing.

**Comment by Magisus** [comment]
Sorry, I haven't been involved with the filebucket stuff, @joshcooper or @jtappa would know more, since they worked on the actual ticket.

**Comment by kris-bosland** [comment]
@gguillotte, for --local, --bucket can override the '$clientbucketdir' setting for the location of the bucket.

**Comment by kris-bosland** [comment]
My last comment was a little out of date, I didn't see the later comments.  Line 34 of the file does list the bucket option.

**Comment by gguillotte** [comment]
@kris-bosland It's in the list of options, yes, but we never describe what `--bucket` does — like overriding other options' defaults — in the man page.

**Comment by gguillotte** [comment]
cool, I can check this off my bucket list

**Pull request merged**
