### PR TITLE
(PUP-5448) Add cumulus install support

### PR DESCRIPTION
**Pull request by johnduarte**
This commit adds conditional logic to find cumulus repo file
in order to install on cumulus.

[skip ci]

### CODE REVIEW

**Comment by LuvCurves** [comment]
This will require what will be Beaker version 2.28.0

**Comment by LuvCurves** [comment]
Beaker version 2.28.0 is available

**Comment by johnduarte** [comment]
Added commit to update Gemfile to Beaker 2.28

**Comment by joshcooper** [comment]
If this is for PUP 4.3.0, please retarget for stable

**Comment by johnduarte** [comment]
Closing PR to retarget for stable

**Pull request closed without merging**
