### PR TITLE
(PUP-5022) update generator skeleton to new README template

### PR DESCRIPTION
**Pull request by DavidS**
Cherry picked #4373 on top of stable.

### CODE REVIEW

**Comment by joshcooper** [comment]
@jbondpdx could you review and merge? Also please update the jira fixVersion to PUP 4.3.0 and resolve the ticket. /cc @barlowst @nfagerlund @gguillotte @jtappa

**Comment by jtappa** [comment]
@joshcooper Jean is out until Thursday, if you need it merged before then, let me know and I can take a look and merge later this afternoon.

**Comment by joshcooper** [comment]
@jtappa please do merge today to get into puppet 4.3.0/puppet-agent 1.3.0.

**Comment by jtappa** [comment]
@DavidS will you please rebase, then ping me so I can merge? It's now out of date with stable. Thanks!

**Comment by DavidS** [comment]
@jtappa @jbondpdx @joshcooper Updated.

**Comment by jtappa** [comment]
:+1:

**Pull request merged**
