### PR TITLE
(PUP-4530) FreeBSD specific service provider fix

### PR DESCRIPTION
**Pull request by infracaninophile**
Ticket ref: PUP-4530

### CODE REVIEW

**Comment by peterhuene** [comment]
Hi @infracaninophile.  Thanks for the contribution!  Before we can consider merging this, could you amend your commit message to be the expected format of "(PUP-4530 per our [contributing guidelines](https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md#making-changes)?

Also, it appears that the AppVeyor failure is a transient issue that may be fixed by rebasing; speaking of, it's generally a good idea to do work in a branch other than master to make rebasing easier.

**Comment by infracaninophile** [comment]
Commit message amended as requested.  Sorry about not working in a branch.

**Comment by peterhuene** [comment]
Hi @infracaninophile.  Thanks for pushing up the changes!  It looks like the original commit wasn't amended properly, though, as there are now two commits for the same thing in the PR.  Additionally, there shouldn't be any merge commits in the history.

I would do a `git pull --rebase upstream master` to rebase.  This should likely get rid of that merge commit.  From there, a `git rebase -i` can be used to discard one of the two identical commits.

There's one last thing I should have mentioned earlier: could you reword the commit title (either with `git rebase -i` or `git commit --amend`) like `(PUP-4530) Fix FreeBSD service provider to parse service names correctly` or something along those lines?  It may seem a bit pedantic, but we prefer seeing commit messages in a sort of "imperative" form.

With the above fixed up, we'll get this merged in.  Cheers!

**Comment by infracaninophile** [comment]
Did that do what you wanted?  This is getting beyond what git-usage I understand.

**Comment by peterhuene** [comment]
@infracaninophile Unfortunately the rebase wasn't performed correctly as now there's a ton of commits in your branch that the PR is attempting to merge (there should be only 1).  There shouldn't be any merge commits from your master branch in your commit log (commit 3b9b43b should be deleted). `git pull --rebase upstream master` should have pulled puppetlabs' master into yours and then replayed any commits that are local to your branch (preferably only commit d390578).

If you like, I can put your commit up in a different PR (your commit goes in as-is), but unfortunately GitHub doesn't allow me to fix this PR in that way.  Thanks!

**Comment by infracaninophile** [comment]
> If you like, I can put your commit up in a different PR (your commit goes in as-is), but unfortunately 
> GitHub doesn't allow me to fix this PR in that way. Thanks!

That would probably be the best.

**Comment by peterhuene** [comment]
@infracaninophile Thanks again for the contribution!  I've opened PR #3928 with just your commit.  I'm going to close this PR in favor of that one.

**Pull request closed without merging**
