### PR TITLE
(PUP-9092) Improve process handling on Windows

### PR DESCRIPTION
**Pull request by onyxmaster**
A simple improvement to improve process handling rate on Windows.
With exec/onlyif/unless-heavy catalogs, this change easily makes catalog application 10 times faster.

### CODE REVIEW

**Comment by onyxmaster** [comment]
Your email sending procedure appears to be broken, I never got the email, no matter how much I clicked “resend”, or change my email address. Yes, I checked my spam folder, no, I do not have any filters.

**Comment by joshcooper** [comment]
Hi @onyxmaster, thank you for your contribution! The change makes sense. I think the only downside is the ruby thread can't be interrupted for up to 15 seconds once it calls into the native method (assuming the child process is long lived). But maybe newer ruby versions handle that correctly now?

About which version to target, the 4.10.x is in security mode only and 5.3.x is in deep maintenance mode. Please target the 5.5.x base branch.

**Comment by onyxmaster** [comment]
IIRC, the 2nd argument to WaitForSingleObject is milliseconds, also my manual testing of Ctrl-C-ing puppet while it executes a specially built binary that loops for 30 seconds worked instantly every time (although I did only three tests).

**Comment by joshcooper** [comment]
> 2nd argument to WaitForSingleObject is specified in milliseconds

Ah right, that makes sense 👍

**Comment by hlindberg** [comment]
Yep, second arg to [WaitForSingleObject](https://docs.microsoft.com/en-us/windows/desktop/api/synchapi/nf-synchapi-waitforsingleobject) is in ms.

**Comment by joshcooper** [comment]
@onyxmaster could you rebase your PR on 5.5.x?

**Comment by onyxmaster** [comment]
Well, seems that Github believes that force pushing wasn't a good idea, there are now no new commits between my master and origin 5.5.x, so I cant change the PR base, and it closed the PR automatically, see the new PR. Sorry for any inconvenience, I'm "not really good" with git.

**Pull request closed without merging**
