### PR TITLE
(PUP-3827) Return errors matching schema from indirected routes

### PR DESCRIPTION
**Pull request by justinstoller**
But with feeling this time....    ...so many feelings....

Originally the merged PR for PUP-3827 (#4875) had its acceptance tests ran locally with `SHA=$(git rev-parse HEAD) TEST_TARGET=ubuntu1404-64a bundle exec rake ci:test:git`

That line is crucially missing a `PUPPET_FORK=justinstoller` and instead of running code from the local git checkout will instead look for the current SHA in puppetlabs/puppet and when it doesn't find it, it happily runs code from the current HEAD of master. 

Some selected commit messages from the past month that this ticket has been in progress:
```
Prior to this the indirected routes would intercept any issues that
arose in processing the request and format them into a plain text
response with the proper error code.

All other routes pass issues up to the generic route handler which will
format them according to a documented schema.

This moves the indirected routes handler from never raising to always
raising on error, similar to other route handlers. This allows the
indirected routes to share the error handling code with other routes
and provides consistently formatted errors throughout the rest api.
```
```
In 363d36e we brought the IndirectedRoutes into consistency with
other API handlers. However, we regressed in no longer catching
Puppet::Network::AuthorizationErrors (which is handled by additional
middleware for other route handlers).

IndirectedRoutes cannot use the same middleware as other handlers
without a larger refactor because the URI supplied to the middleware
must first be coerced and validated (logic which currently lives within
IndirectedRoutes) before it can be authorized.

Therefore, this patch leaves the authorization check within
IndirectedRoutes, but ensure that it catches any
Puppet::Network::AuthorizationError and raises
Puppet::Network::HTTP::Error::HTTPNotAuthorizedError in its place.
```
```
Previously, we threw ArgumentErrors when we received a malformed request
for the IndirectedRoutes class. This conflated an error in calling a
Ruby method and an error by the consumer calling an API endpoint, and
consequently always returned 400 statuses for internal errors.

As part of PUP-3827, higher level middleware now handles the response
formatting for errors. The higher level middleware, however, makes the
distinction between ArgumentErrors to Ruby functions and BadRequests to
the API endpoint (and expects throwers to as well).

Since IndirectedRoutes did not make this distinction all invalid
environment requests were then being treated as ServerErrors, and
returning 500 statuses.

This patch updates IndirectedRoutes to throw proper HTTPErrors instead
of ArgumentErrors when a client has submitted a BadRequest, used a
MethodNotAllowed, or the environment is NotFound.
```

Plus attendant test updates.

### CODE REVIEW

**Comment by justinstoller** [comment]
Running locally I get this set of failures:
```
21:37:36 hobo:acceptance justin (PUP-3827-this-time-with-feeling) ‖ bundle exec rake ci:test:git SHA=`git rev-parse HEAD` TEST_TARGET=ubuntu1404-64a PUPPET_FORK=justinstoller


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 3061.94 seconds
      Average Test Time: 10.17 seconds
              Attempted: 301
                 Passed: 242
                 Failed: 0
                Errored: 4
                Skipped: 54
                Pending: 1
                  Total: 301

      - Specific Test Case Status -
        
Failed Tests Cases:
Errored Tests Cases:
                Test Case tests/direct_puppet/static_catalog_env_control.rb reported: #<Beaker::Host::CommandFailure: Host 'nbr7kz9zy4sf5wi.delivery.puppetlabs.net' exited with 1 running:
               mv /etc/puppetserver/conf.d/puppetserver.conf.bak /etc/puppetserver/conf.d/puppetserver.conf
              Last 10 lines of output were:
                mv: cannot stat ‘/etc/puppetserver/conf.d/puppetserver.conf.bak’: No such file or directory>
                Test Case tests/direct_puppet/supports_utf8.rb reported: #<Beaker::Host::CommandFailure: Host 'nbr7kz9zy4sf5wi.delivery.puppetlabs.net' exited with 1 running:
               ln -sf /tmp/supports_utf8_i6rumvd1 /etc/puppetlabs/code/environments/supports_utf8_i6rumvd1
              Last 10 lines of output were:
                ln: failed to create symbolic link ‘/etc/puppetlabs/code/environments/supports_utf8_i6rumvd1’: No such file or directory>
                Test Case tests/language/exported_resources.rb reported: #<Beaker::Host::CommandFailure: Host 'nbr7kz9zy4sf5wi.delivery.puppetlabs.net' exited with 1 running:
               ln -sf /tmp/exported_resources_9235h4rk /etc/puppetlabs/code/environments/exported_resources_9235h4rk
              Last 10 lines of output were:
                ln: failed to create symbolic link ‘/etc/puppetlabs/code/environments/exported_resources_9235h4rk’: No such file or directory>
                Test Case tests/parser_functions/no_exception_in_reduce_with_bignum.rb reported: #<RuntimeError: PuppetAcceptance::DSL::Helpers.with_puppet_running_on failed (check backtrace for location) because: Host 'nszn6bb4f3f3xfw.delivery.puppetlabs.net' exited with 1 running:
               puppet agent -t --environment no_exception_in_reduce_with_bignum_ugtok9ny --server nbr7kz9zy4sf5wi.delivery.puppetlabs.net
              Last 10 lines of output were:
                Info: Retrieving pluginfacts
                Error: /File[/opt/puppetlabs/puppet/cache/facts.d]: Failed to generate additional resources using 'eval_generate': Error 500 on SERVER: {"message":"Server Error: Permission denied - /etc/puppetlabs/code/environments/no_exception_in_reduce_with_bignum_ugtok9ny/environment.conf","issue_kind":"RUNTIME_ERROR"
```

I believe those are issues from the fact that it is a git checkout, but I would love someone from the Client team to confirm that.
```
cat log/latest/hosts_preserved.yml
---
HOSTS:
  nbr7kz9zy4sf5wi.delivery.puppetlabs.net: !ruby/hash:Beaker::Options::OptionsHash
    :pe_dir: 
    :pe_ver: 
    :pe_upgrade_dir: 
    :pe_upgrade_ver: 
    :hypervisor: vmpooler
    :platform: !ruby/string:Beaker::Platform
      str: el-7-x86_64
      variant: !ruby/string:Beaker::Platform el
      arch: !ruby/string:Beaker::Platform x86_64
      version: !ruby/string:Beaker::Platform '7'
      codename: 
    :template: redhat-7-x86_64
    :roles:
    - master
    - default
    :user: root
    :group: puppet
    :pathseparator: ":"
    :host_tags: !ruby/hash:Beaker::Options::OptionsHash {}
    :vmhostname: nbr7kz9zy4sf5wi.delivery.puppetlabs.net
    :puppetserver-confdir: "/etc/puppetserver/conf.d"
    :puppetservice: puppetmaster
    :puppetpath: "/etc/puppet"
    :puppetconfdir: "/etc/puppet"
    :puppetvardir: "/var/lib/puppet"
    :puppetbin: "/usr/bin/puppet"
    :puppetbindir: "/usr/bin"
    :privatebindir: "/usr/bin"
hieralibdir: "/opt/puppet-git-repos/hiera/lib"
    :hierapuppetlibdir: "/opt/puppet-git-repos/hiera-puppet/lib"
    :hierabindir: "/opt/puppet-git-repos/hiera/bin"
    :hieradatadir: "/etc/puppet/hieradata"
    :hieraconf: "/etc/puppet/hiera.yaml"
    :distmoduledir: "/etc/puppetlabs/code/modules"
    :sitemoduledir: "/opt/puppetlabs/puppet/modules"
    :type: foss
  nszn6bb4f3f3xfw.delivery.puppetlabs.net: !ruby/hash:Beaker::Options::OptionsHash
    :pe_dir: 
    :pe_ver: 
    :pe_upgrade_dir: 
    :pe_upgrade_ver: 
    :hypervisor: vmpooler
    :platform: !ruby/string:Beaker::Platform
      str: ubuntu-14.04-amd64
      variant: !ruby/string:Beaker::Platform ubuntu
      arch: !ruby/string:Beaker::Platform amd64
      version: !ruby/string:Beaker::Platform '14.04'
      codename: trusty
    :template: ubuntu-1404-x86_64
    :roles:
    - agent
    :user: root
    :group: puppet
    :pathseparator: ":"
    :host_tags: !ruby/hash:Beaker::Options::OptionsHash {}
    :vmhostname: nszn6bb4f3f3xfw.delivery.puppetlabs.net
    :puppetserver-confdir: "/etc/puppetserver/conf.d"
    :puppetservice: puppetmaster
    :puppetpath: "/etc/puppet"
    :puppetconfdir: "/etc/puppet"
    :puppetvardir: "/var/lib/puppet"
    :puppetbin: "/usr/bin/puppet"
    :puppetbindir: "/usr/bin"
    :privatebindir: "/usr/bin"
    :hieralibdir: "/opt/puppet-git-repos/hiera/lib"
    :hierapuppetlibdir: "/opt/puppet-git-repos/hiera-puppet/lib"
    :hierabindir: "/opt/puppet-git-repos/hiera/bin"
    :hieradatadir: "/etc/puppet/hieradata"
    :hieraconf: "/etc/puppet/hiera.yaml"
    :distmoduledir: "/etc/puppetlabs/code/modules"
    :sitemoduledir: "/opt/puppetlabs/puppet/modules"
    :type: foss
CONFIG: !ruby/hash:Beaker::Options::OptionsHash
  :nfs_server: none
  :consoleport: 443
  :pooling_api: http://vmpooler.delivery.puppetlabs.net/
  :project: Beaker
  :department: unknown
  :created_by: justin
  :host_tags: !ruby/hash:Beaker::Options::OptionsHash {}
  :openstack_api_key: 
  :openstack_username: 
  :openstack_auth_url: "/tokens"
  :openstack_tenant: 
  :openstack_keyname: 
  :openstack_network: 
  :openstack_region: 
  :jenkins_build_url: 
  :validate: true
  :configure: true
  :log_level: debug
  :trace_limit: 10
  :master-start-curl-retries: 30
  :masterless: false
  :options_file: merged_options.rb
  :type: git
  :provision: false
  :preserve_hosts: onfail
  :root_keys: true
  :quiet: false
  :project_root: "/Users/justin/Backup/code/work/puppet/acceptance/.bundle/gems/gems/beaker-2.41.0/lib/beaker"
  :xml_dir: junit
  :xml_file: beaker_junit.xml
  :xml_time: beaker_times.xml
  :xml_time_enabled: false
  :xml_stylesheet: junit.xsl
  :log_dir: log
  :log_sut_event: sut.log
  :color: false
  :dry_run: false
  :tag_includes: []
  :tag_excludes: []
  :timeout: 900
  :fail_mode: slow
  :accept_all_exit_codes: false
  :timesync: false
  :disable_iptables: false                                                                                                                                                                          [9/9333]
  :set_env: true
  :disable_updates: true
  :repo_proxy: true
  :package_proxy: false
  :add_el_extras: false
  :epel_url: http://mirrors.kernel.org/fedora-epel
  :epel_arch: i386
  :epel_7_pkg: epel-release-7-6.noarch.rpm
  :epel_6_pkg: epel-release-6-8.noarch.rpm
  :epel_5_pkg: epel-release-5-4.noarch.rpm
  :pe_dir: "/opt/enterprise/dists"
  :pe_version_file: LATEST
  :pe_version_file_win: LATEST-win
  :host_env: !ruby/hash:Beaker::Options::OptionsHash {}
  :host_name_prefix: 
  :ssh_env_file: "~/.ssh/environment"
  :profile_d_env_file: "/etc/profile.d/beaker_env.sh"
  :dot_fog: "/Users/justin/.fog"
  :ec2_yaml: config/image_templates/ec2.yaml
  :help: false
  :collect_perf_data: none
  :puppetdb_port_ssl: 8081
  :puppetdb_port_nonssl: 8080
  :puppetserver_port: 8140
  :nodeclassifier_port: 4433
  :cache_files_locally: true
  :aws_keyname_modifier: '7954764593'
  :ssh: !ruby/hash:Beaker::Options::OptionsHash
    :config: false
    :paranoid: false
    :auth_methods:
    - publickey
    :port: 22
    :forward_agent: true
    :keys:
    - id_rsa_acceptance
    - "/Users/justin/.ssh/id_rsa-acceptance"
    :user_known_hosts_file: "/Users/justin/.ssh/known_hosts"
    :keepalive: true
  :helper:
  - lib/helper.rb
  :tests: []
  :xml: true
  :forge_host: forge-aio01-petest.puppetlabs.com
  :install:
  - https://github.com/puppetlabs/facter.git#2.x
  - https://github.com/puppetlabs/hiera.git#1.3.4
  - https://github.com/justinstoller/puppet.git#3bb5db6363df7d1bfb1e0a9784afb489101f0340
  :pre_suite: []
  :hosts_file: "/Users/justin/Backup/code/work/puppet/acceptance/tmp/redhat7-64m-ubuntu1404-64a-7da37d39-31e6-43b0-9fa8-37be7c30d78d.yaml"
  :command_line: "/Users/justin/Backup/code/work/puppet/acceptance/.bundle/gems/bin/beaker
    --options-file merged_options.rb --hosts=tmp/redhat7-64m-ubuntu1404-64a-7da37d39-31e6-43b0-9fa8-37be7c30d78d.yaml"
  :home: "/Users/justin"
  :load_path: []
  :post_suite: []
  :pre_cleanup: []
  :modules: []
  :beaker_version: 2.41.0
```

**Comment by justinstoller** [comment]
@branan @whopper Puppet Agent release has gone out, right? Is the master branch open to merges?

**Comment by KevinCorcoran** [comment]
@justinstoller Should #4947 be closed?

**Comment by justinstoller** [comment]
Yeah, thanks. Closed.

**Comment by justinstoller** [comment]
Updated the indirector rest terminus to properly format messages for error responses in `[PJ]SON`. Also rebased onto master.

**Comment by kylog** [comment]
LGTM. Sorry we missed your ping on the PR two weeks ago - yes, master is open for business again. Woot!

**Pull request merged**
