### PR TITLE
(PUP-7815) Add Task class, have Modules find their Tasks

### PR DESCRIPTION
**Pull request by aperiodic**
Add a new class to represent tasks contained in modules. There's not
much functionality in it yet: it can find valid task files in a module's
tasks directory and construct tasks composed of them, where the tasks
can't do anything but tell you their name, their paylod files, their
metadata file (if they have one), and the module they belong to, all via
attribute reader instance methods. There are no other instance methods,
but there are a few public class methods for validating task names and
file names.

When modules are created, they check to see if their tasks directory
exists. If so, they use the Puppet::Module::Task class to create a Task
object for every task that exists in their task directory.

### CODE REVIEW

**Comment by aperiodic** [comment]
Hmm, I don't understand why the AppVeyor build failed -- there were some warnings, but the specs all passed, and I can't find the exception it claims occurred. Previous AppVeyor builds for this PR passed, and the only changes have been a small amount of new behavior around names that should be the same on all platforms. Is there a way to kick the AppVeyor build? Or can you see the exception?

**Comment by hlindberg** [comment]
I think tasks should be represented in modules as Data types. Then there is no need to write any code at all to load them, reflect them, serialize them, a name can directly refer to a task, etc. etc. I think invention of yet more special kinds of things with new ways of loading them is going in the wrong direction.

The description of how the logic in this PR seems to say that eager loading of tasks will take place - that does not sound good at all if that is always the case at runtime. Is that for reflection? That should be solved a different way.

-1 to the design.

**Comment by aperiodic** [comment]
Originally when we looked at the module code we thought we could add tasks as just another file type for modules, but since the filetype methods operate directly on files present on disk while there is some logic necessary to map between available tasks and files on disk, since there is not a 1:1 correspondence like with a manifest. In the near future we'll have more, say for loading the task metadata and gathering the pieces of file metadata we want to serve through the API. A separate class that contains only this logic and whose state acts as a caching mechanism seemed like a sensible way to implement this.

If what you're objecting to is the separate class, then I suppose we could move this logic into the the module class. If you have something different in mind (which I suspect from your usage of capital-D 'Data'), could you elaborate on that?

As for the eager loading of tasks: I think this is desirable, and was motivated by performance considerations. This lets us cache the list of available tasks by using the environment cache in Puppet Server, since the environment will load its modules will load their tasks, after which listing them involves no IO, and the list should be correct for as long as the environment is in the cache.

Although, as I say this, I realize that assumes code manager controls environments; are there no guarantees at all about the consistency of environment contents without that? Should the implementation always read the currently available tasks from disk whenever modules are asked for their tasks, and the caching implemented some other way? Or is it acceptable for the loading occur the first time that a module is asked for its tasks? (The reason I felt is was alright to eagerly load is that tasks already eagerly load their metadata from disk when they're initialized, so I thought that a directory check for each module would not significantly increase the load time.)

**Comment by aperiodic** [comment]
Based on your discussion with Michael, it seems like you're concerned with how Tasks will be represented in Puppet code. The changes in this PR are intended only to provide data about standalone task files in modules that we'll serve through the API; it shouldn't define anything about the language side of Tasks or how users will define or load them. If you think it does, please explain how and provide a sketch of an alternative implementation that allows us to serve these standalone tasks without requiring them to be defined in Puppet code.

As the language changes to allow defining and using tasks in Puppet code are made, I think we should be able to integrate those tasks into the module's notion of what tasks are available for serving through the API. Do you disagree?

**Comment by MosesMendoza** [comment]
> I think tasks should be represented in modules as Data types. 

In the future I'd like to move task file serving out of puppet ruby and just serve these files via puppet server. I understand there's some knowledge about module path we'd need to create but thats ok. So I'm hesitant to tie task implementation into puppet very closely.

**Comment by aperiodic** [comment]
I've updated this to avoid loading any tasks before the `tasks` method of a Module instance is called.

**Comment by holguinj** [comment]
Closing in favor of #6120

**Pull request closed without merging**
