### PR TITLE
(PUP-4436) Create required ancestor directories

### PR DESCRIPTION
**Pull request by joshcooper**

### CODE REVIEW

**Comment by kylog** [comment]
Not sure what happened on appveyor???

**Comment by joshcooper** [comment]
@MikaelSmith filed the rdoc issue is https://tickets.puppetlabs.com/browse/PUP-4537, not sure why it's happening

**Comment by kylog** [comment]
Ah, right. I thought it looked familiar ... thanks!

**Comment by kylog** [comment]
Nit: can you tweak the summary line in the commit to fix the typo in the word 'ancestor'.

**Comment by joshcooper** [comment]
@kylog updated commit. Looks like appveyor passed this time, but waiting on travis...

**Comment by kylog** [comment]
Travis is delayed, but this has passed previously.

**Pull request merged**
