### PR TITLE
(PUP-11783) Delete vendored pson

### PR DESCRIPTION
**Pull request by joshcooper**
Deletes vendored pson code. It is possible to install the gem to re-enable pson but it's not enabled by default.

- [x] Blocked on https://github.com/puppetlabs/puppet/pull/9034
- [x] ~Need to add `puppet-pson` to features group~
- [x] Run beaker tests

### CODE REVIEW

**Comment by joshcooper** [comment]
jenkins please test this with servertests

**Comment by joshcooper** [comment]
jenkins please test this with servertests

**Comment by joshcooper** [comment]
jenkins please test this with servertests

**Comment by joshcooper** [comment]
jenkins please test this with servertests

**Review by mhashizume — APPROVED** [review]

**Pull request merged**
