### PR TITLE
(PUP-6620) Move pre-suite setup of CA certs on Windows

### PR DESCRIPTION
**Pull request by MosesMendoza**
(PA-461) Prior to this commit, the Puppet presuite would install the certs
needed to connect to forge over PMT for all test modes. This was needed as the
Windows MSI did not include certs. That changed for :aio in RE-6111, in which
the cert bundle was included in the MSI, but this pre-suite item remained. This
commit moves it to the :git mode presuite only, because it is no longer needed
for :aio, and in PA-461 was found to be masking a misconfiguration in the MSI
  which resulted in a regression in functionality.

### CODE REVIEW

**Comment by Iristyle** [comment]
I *think* this should work.. but we should probably run the various `ci:test:XXX` tasks locally to make certain.

**Comment by MosesMendoza** [comment]
I ran `ci:test:git` and the associated module tests passed. While the run had no failures, there were some errors though, output here: https://gist.github.com/MosesMendoza/d0a95bf513ecaa60fcd33d7204069076. They appear to be unrelated to this change, but may signal that we need to audit that our tests are still compatible with running from git? My invocation was: `be rake ci:test:git PUPPET_FORK='MosesMendoza' TEST_TARGET='windows2012r2-64a' SHA='00bc15b91dd935372d7e821afcfe63f407d75efa'`

I'll run with `ci:test:gem` and post output of that as well.

**Comment by joshcooper** [comment]
I think the errors are because `ci:test:git` uses a webrick master, but the tests are assuming puppetserver. The tests may have been recently added?

**Comment by Iristyle** [comment]
@MosesMendoza I believe those are known failures when running `ci:test:git` for the reason @joshcooper has mentioned, so that's good news.

My last `ci:test:git` run for a different issue had these failures (see https://gist.githubusercontent.com/Iristyle/7aadb5760c6113a1d6b7ecf6d1af3532/raw/5508563c5e297ab508881024a68cda732cce8faf/tests-run.log for full run): 

* tests/direct_puppet/static_catalog_env_control.rb - you have this one
* tests/direct_puppet/supports_utf8.rb - you have this one
* tests/environment/custom_type_provider_from_same_environment.rb - you have this one
* tests/face/parser_validate.rb - you **don't have** this one
* tests/language/exported_resources.rb - you have this one
* tests/parser_functions/no_exception_in_reduce_with_bignum.rb - you have this one

```
 Test Case tests/direct_puppet/static_catalog_env_control.rb reported: #<Beaker::Host::CommandFailure: Host 'vc0s0t3vuo12ux8.delivery.puppetlabs.net' exited with 1 running:
                     mv /etc/puppetserver/conf.d/puppetserver.conf.bak /etc/puppetserver/conf.d/puppetserver.conf
                    Last 10 lines of output were:
                    	mv: cannot stat ‘/etc/puppetserver/conf.d/puppetserver.conf.bak’: No such file or directory>
                      Test Case tests/direct_puppet/supports_utf8.rb reported: #<Beaker::Host::CommandFailure: Host 'vc0s0t3vuo12ux8.delivery.puppetlabs.net' exited with 1 running:
                     ln -sf /tmp/supports_utf8_m5acn9ke /etc/puppetlabs/code/environments/supports_utf8_m5acn9ke
                    Last 10 lines of output were:
                    	ln: failed to create symbolic link ‘/etc/puppetlabs/code/environments/supports_utf8_m5acn9ke’: No such file or directory>
                      Test Case tests/environment/custom_type_provider_from_same_environment.rb reported: #<Beaker::Host::CommandFailure: Host 'vc0s0t3vuo12ux8.delivery.puppetlabs.net' exited with 1 running:
                     ln -sf /tmp/custom_type_provider_from_same_environment_1gjo4rbw /etc/puppetlabs/code/environments/custom_type_provider_from_same_environment_1gjo4rbw
                    Last 10 lines of output were:
                    	ln: failed to create symbolic link ‘/etc/puppetlabs/code/environments/custom_type_provider_from_same_environment_1gjo4rbw’: No such file or directory>
                      Test Case tests/face/parser_validate.rb reported: #<Beaker::Host::CommandFailure: Host 'jauagz90qn520sb.delivery.puppetlabs.net' exited with 1 running:
                     ln -sf /tmp/parser_validate_pa0c4d8t /etc/puppetlabs/code/environments/parser_validate_pa0c4d8t
                    Last 10 lines of output were:
                    	ln: failed to create symbolic link '/etc/puppetlabs/code/environments/parser_validate_pa0c4d8t': No such file or directory>
                      Test Case tests/language/exported_resources.rb reported: #<Beaker::Host::CommandFailure: Host 'vc0s0t3vuo12ux8.delivery.puppetlabs.net' exited with 1 running:
                     ln -sf /tmp/exported_resources_9adiz862 /etc/puppetlabs/code/environments/exported_resources_9adiz862
                    Last 10 lines of output were:
                    	ln: failed to create symbolic link ‘/etc/puppetlabs/code/environments/exported_resources_9adiz862’: No such file or directory>
                      Test Case tests/parser_functions/no_exception_in_reduce_with_bignum.rb reported: #<RuntimeError: PuppetAcceptance::DSL::Helpers.with_puppet_running_on failed (check backtrace for location) because: Host 'jauagz90qn520sb.delivery.puppetlabs.net' exited with 1 running:
                     puppet agent -t --environment no_exception_in_reduce_with_bignum_mqrbx78l --server vc0s0t3vuo12ux8.delivery.puppetlabs.net
                    Last 10 lines of output were:
                    	[1;33mWarning: Error 500 on SERVER: Server Error: Permission denied - /etc/puppetlabs/code/environments/no_exception_in_reduce_with_bignum_mqrbx78l/environment.conf[0m
                    	[1;31mError: /File[/opt/puppetlabs/puppet/cache/facts.d]: Failed to generate additional resources using 'eval_generate': Error 500 on SERVER: Server Error: Permission denied - /etc/puppetlabs/code/environments/no_exception_in_reduce_with_bignum_mqrbx78l/environment.conf[0m
                    	[1;31mError: /File[/opt/puppetlabs/puppet/cache/facts.d]: Could not evaluate: Could not retrieve file metadata for puppet:///pluginfacts: Error 500 on SERVER: Server Error: Permission denied - /etc/puppetlabs/code/environments/no_exception_in_reduce_with_bignum_mqrbx78l/environment.conf[0m
                    	[0;32mInfo: Retrieving plugin[0m
                    	[1;31mError: /File[/opt/puppetlabs/puppet/cache/lib]: Failed to generate additional resources using 'eval_generate': Error 500 on SERVER: Server Error: Permission denied - /etc/puppetlabs/code/environments/no_exception_in_reduce_with_bignum_mqrbx78l/environment.conf[0m
                    	[1;31mError: /File[/opt/puppetlabs/puppet/cache/lib]: Could not evaluate: Could not retrieve file metadata for puppet:///plugins: Error 500 on SERVER: Server Error: Permission denied - /etc/puppetlabs/code/environments/no_exception_in_reduce_with_bignum_mqrbx78l/environment.conf[0m
                    	[1;31mError: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Permission denied - /etc/puppetlabs/code/environments/no_exception_in_reduce_with_bignum_mqrbx78l/environment.conf[0m
                    	[1;33mWarning: Not using cache on failed catalog[0m
                    	[1;31mError: Could not retrieve catalog; skipping run[0m
                    	[1;31mError: Could not send report: Error 500 on SERVER: Server Error: Permission denied - /etc/puppetlabs/code/environments/no_exception_in_reduce_with_bignum_mqrbx78l/environment.conf[0m
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/gems/beaker-2.44.0/lib/beaker/host.rb:331:in `exec'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/gems/beaker-2.44.0/lib/beaker/dsl/helpers/host_helpers.rb:83:in `block in on'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/gems/beaker-2.44.0/lib/beaker/shared/host_manager.rb:115:in `run_block_on'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/gems/beaker-2.44.0/lib/beaker/dsl/patterns.rb:35:in `block_on'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/gems/beaker-2.44.0/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
                    tests/parser_functions/no_exception_in_reduce_with_bignum.rb:60:in `block (4 levels) in run_test'
                    tests/parser_functions/no_exception_in_reduce_with_bignum.rb:59:in `each'
                    tests/parser_functions/no_exception_in_reduce_with_bignum.rb:59:in `block (3 levels) in run_test'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/gems/beaker-2.44.0/lib/beaker/dsl/helpers/puppet_helpers.rb:171:in `with_puppet_running_on'
                    tests/parser_functions/no_exception_in_reduce_with_bignum.rb:58:in `block (2 levels) in run_test'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/gems/beaker-2.44.0/lib/beaker/dsl/structure.rb:58:in `test_name'
                    tests/parser_functions/no_exception_in_reduce_with_bignum.rb:2:in `block in run_test'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/gems/beaker-2.44.0/lib/beaker/test_case.rb:133:in `eval'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/gems/beaker-2.44.0/lib/beaker/test_case.rb:133:in `block in run_test'
                    /usr/local/opt/rbenv/versions/2.1.9/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/gems/beaker-2.44.0/lib/beaker/test_case.rb:130:in `run_test'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/gems/beaker-2.44.0/lib/beaker/test_suite.rb:318:in `block in run'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/gems/beaker-2.44.0/lib/beaker/test_suite.rb:315:in `each'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/gems/beaker-2.44.0/lib/beaker/test_suite.rb:315:in `run'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/gems/beaker-2.44.0/lib/beaker/test_suite.rb:364:in `run_and_raise_on_failure'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/gems/beaker-2.44.0/lib/beaker/cli.rb:173:in `run_suite'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/gems/beaker-2.44.0/lib/beaker/cli.rb:99:in `execute!'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/gems/beaker-2.44.0/bin/beaker:6:in `<top (required)>'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/bin/beaker:23:in `load'
                    /Users/Iristyle/source/puppet/acceptance/.bundle/gems/ruby/2.1.0/bin/beaker:23:in `<main>'
```

The one other thing we'll want to validate is that that *something* errors when the package is configured incorrectly. I believe you should be able to run this suite modification against the SHA with the bad `environment.bat`.  If that suite passes, we should add something additional to prevent against regressions.  Not sure if that's on your radar yet or not for validation, but figured I'd mention in case not.

**Comment by Iristyle** [comment]
I believe a bad SHA that we can use is 2c82928c8b19b5b63168712d337ee4c6e9a34a30

**Comment by Iristyle** [comment]
Sorry, I should have specified a bit more detail on how you invoke... you need to set a couple of env vars:

```
MSI_BASE_URL=https://builds.delivery.puppetlabs.net/puppet-agent/2c82928c8b19b5b63168712d337ee4c6e9a34a30/repos/windows/ MSI_FILENAME=puppet-agent-1.5.3.235.g2c82928-x64.msi
```

I don't believe in that case you have to worry about the `SHA` env var (but there might be some weird validation that requires it - you may have to experiment a little)

**Comment by MosesMendoza** [comment]
fyi related ticket is PA-472

**Comment by MosesMendoza** [comment]
Update commit body to include PA-472 which now tracks explicitly the addition of tests (as opposed to PA-466 which tracked the regression fix). These aren't in the commit subject line because of the check that is done to ensure commit subjects only start with (maint), (packaging), or (pup-)

**Comment by MosesMendoza** [comment]
Validated that the basic module install test against windows 2012r2 fails with this test change using an agent without the certs (agent version 1.5.3):

```
C:/ProgramData/PuppetLabs/code/environments/production/modules ...
	Notice: Downloading from https://forgeapi.puppetlabs.com ...
	Error: Could not connect via HTTPS to https://forgeapi.puppetlabs.com
	  Unable to verify the SSL certificate
	    The certificate may not be signed by a valid CA
	    The CA bundle included with OpenSSL may not be valid or up to date>
    Test line: tests/modules/install/basic_install.rb:22:in `block (2 levels) in run_test'
```
And passes with this test change against agent version 1.6.0
```
End teardown
tests/modules/install/basic_install.rb passed in 45.11 seconds
      Test Suite: tests @ 2016-08-16 17:41:13 -0700
```

**Comment by MosesMendoza** [comment]
fwiw to wrap up the conversation on invoking beaker tests, one command used in validating these test changes was `bundle exec rake ci:test:aio TEST_TARGET='windows2012r2-64a' SHA='1.5.3' TESTS='tests/modules/install/basic_install.rb' SERVER_VERSION='2.4.0'`

**Comment by Iristyle** [comment]
I used a 1.6.0 candidate build (that did not include the cert bundle fix) at 2c82928c8b19b5b63168712d337ee4c6e9a34a30 / https://builds.delivery.puppetlabs.net/puppet-agent/2c82928c8b19b5b63168712d337ee4c6e9a34a30/repos/windows/

I ran the same test through CI like this:

```
bundle exec rake ci:test:aio TEST_TARGET='windows2012r2-64a' SHA='2c82928c8b19b5b63168712d337ee4c6e9a34a30' TESTS='tests/modules/install/basic_install.rb' SERVER_VERSION='2.4.0'
```

And also experienced the failure 

```
Errored Tests Cases:
  Test Case tests/modules/install/basic_install.rb reported: #<Beaker::Host::CommandFailure: Host 'rjz6vjhy6u8gshf.delivery.puppetlabs.net' exited with 1 running:
 cmd.exe /c puppet module install pmtacceptance-nginx
Last 10 lines of output were:
	Notice: Preparing to install into C:/ProgramData/PuppetLabs/code/environments/production/modules ...
	Notice: Downloading from https://forgeapi.puppetlabs.com ...
	Error: Could not connect via HTTPS to https://forgeapi.puppetlabs.com
	  Unable to verify the SSL certificate
	    The certificate may not be signed by a valid CA
	    The CA bundle included with OpenSSL may not be valid or up to date>
```

That is sufficient for me to consider this valid regression prevention.

👍

**Pull request merged**
