### PR TITLE
(PUP-8342) Update report schema to include transaction_completed

### PR DESCRIPTION
**Pull request by kris-bosland**
This update adds transaction_completed to report serialization/deserialization, and schema, and updates the schema version.

### CODE REVIEW

**Comment by joshcooper** [comment]
@jhelwig did you want to review this too?

**Comment by jhelwig** [comment]
jenkins please test this

**Comment by joshcooper** [comment]
@jhelwig I'm not sure what's up with jenkins or if specific permissions are required...?

**Comment by gguillotte** [comment]
This change incremented the report format version, which has a docs impact.

**Pull request merged**
