### PR TITLE
Merge 4.10.x at 7c8e93bc9d41 into 5.3.x 

### PR DESCRIPTION
**Pull request by glennsarti**
* 4.10.x:
  (packaging) Update puppet version to 4.10.8
  (PUP-7933) Remove documentation about last in scheduledtasks type
  (PUP-7848) Simplify Regexp for VAR_NAME and add test for performance
  (PUP-7848) Fix problem with VAR pattern and longer segments
  (PUP-7902) Add test to assert that only one newline is stripped last
  (PUP-7902) Ensure that empty heredoc lines are not trimmed
  (PUP-7902) Add test asserting that empty heredoc lines are not trimmed

### CODE REVIEW

**Comment by glennsarti** [comment]
I used a PR for this as there were some merge commits.  The puppet version and the spec tests in commit 9ac850389e747d66ccd

**Comment by branan** [comment]
PR title says 5.3.x, but target is master - which is correct?

**Comment by glennsarti** [comment]
@branan DOH  Apologies....yes you're right.  changed target to 5.3.x

**Comment by Magisus** [comment]
There is one additional commit on 4.10.x that doesn't come with this mergeup, is it intentional to leave https://github.com/puppetlabs/puppet/commit/8bcaba7d90ea9115f6e89a6805d20f4c866c7f3f behind?

**Comment by glennsarti** [comment]
@Magisus  Wasn't intentional.  I raised the PR 5 days ago, that commit is only 22 hours old.

**Comment by Magisus** [comment]
Alright, it'll come along next time

**Pull request merged**
