### PR TITLE
(maint) Fix typo strfime -> strftime

### PR DESCRIPTION
**Pull request by smortex**

### CODE REVIEW

**Comment by ericldelaney** [comment]
@LarissaLane @ehom Can we update the pot  and po file for things like this

**Comment by LarissaLane** [comment]
The POT should be auto updating. PO updating is blocked by INTL-32

**Comment by smortex** [comment]
@LarissaLane what should I do?  Remove the `*.po` and `*.pot` files from the pull-request or do not touch anything at all :smiley: ?

**Comment by ericldelaney** [comment]
@smortex I think the answer is just update the string, but I'm working to confirm that.

**Comment by smortex** [comment]
@ericldelaney okay, thanks!  I'll be happy to make the requested changes when we know exactly what to do.

**Comment by ericldelaney** [comment]
@smortex I have an answer, please drop the .po and .pot file from the PR. Could you target this against 5.3.x so we can update it there and then it will be merged up to master.

**Comment by LarissaLane** [comment]
@smortex Thanks for the typo fix, and an even bigger thanks for thinking about our translated strings! Whenever we make typo changes like this, we only need to make them in the source code. We have automation set up to update the POT file. When the POT file is updated by our CI job, it triggers a webhook that pushes the POT through to our translation management system. Next time we place a translation order, which we do at least every month, we'll fix this up in the PO file. 
The short answer is, it would be best to remove the POT and PO file changes from this PR and let our automation take care of that. When your PR gets merged, you'll see it reflected in the POT.

**Comment by smortex** [comment]
@ericldelaney, @LarissaLane thank you for the feedback!  I have amended the commit to remove the `.po` and `.pot` files; and move it on top of the `5.3.x` branch before updating the Pull-Request.  I think that's what you requested.  Please let me know if something is wrong :wink:

**Comment by LarissaLane** [comment]
Perfect! Thank you @smortex

**Pull request merged**
