### PR TITLE
[Backport 7.x] (PUP-12031) Consolidate gem depenendencies & metadata into puppet.gemspec

### PR DESCRIPTION
**Pull request by AriaXLi**
Backport of #9325 to 7.x

### CODE REVIEW

**Comment by AriaXLi** [comment]
There are some discrepancies between the runtime dependencies versions in .gemspec and ext/project_data.yaml:

.gemspec:
```
  s.add_runtime_dependency(%q<facter>, [">= 2.4.0", "< 5"])
  s.add_runtime_dependency(%q<multi_json>, "~> 1.13")
```
  
  project_data.yaml:
```
   facter: ['> 2.0.1', '< 5']
   multi_json: '~> 1.10'
```

I followed whatever was used in project_data.yaml since that's what's used on https://rubygems.org/gems/puppet/versions/7.30.0

**Comment by AriaXLi** [comment]
Successfully built puppet gem:
```
❯ gem build puppet.gemspec
  Successfully built RubyGem
  Name: puppet
  Version: 7.31.0
  File: puppet-7.31.0.gem
```

Diff to verify that the standard puppet gem is built correctly:
```
❯ diff <(gem specification puppet-7.30.0.gem) <(gem specification puppet-7.31.0.gem)

4c4
<   version: 7.30.0
---
>   version: 7.31.0
11c11
< date: 2024-04-09 00:00:00.000000000 Z
---
> date: 2012-08-17 00:00:00.000000000 Z
171c171,173
< description: Puppet, an automated configuration management tool
---
> description: |
>   Puppet, an automated administrative engine for your Linux, Unix, and Windows systems, performs administrative tasks
>   (such as adding users, installing packages, and updating server configurations) based on a centralized specification
```

**Comment by AriaXLi** [comment]
Well this is not expected 🤔 

```
❯ gem build puppet.gemspec --platform universal-darwin
gem build puppet.gemspec --platform universal-darwin
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --platform

```

**Comment by AriaXLi** [comment]
> Well this is not expected 🤔
> 
> ```
> ❯ gem build puppet.gemspec --platform universal-darwin
> gem build puppet.gemspec --platform universal-darwin
> ERROR:  While executing gem ... (OptionParser::InvalidOption)
>     invalid option: --platform
> ```

Ah actually, I think the `--platform` flag just isn't supported in Ruby 2.7:
```
puppet on  backport_PUP-12031 [$!?] via 💎 v2.7.3 on ☁️  aria.li@puppet.com
❯ gem help build

Usage: gem build GEMSPEC_FILE [options]

  Options:
        --force                      skip validation of the spec
        --strict                     consider warnings as errors when validating the spec
    -o, --output FILE                output gem with the given filename
    -C PATH
                                     Run as if gem build was started in <PATH> instead of the current working directory.
```

**Comment by AriaXLi** [comment]
Rake task works 🎉 :
```
❯ bundle exec rake pl_ci:gem_build

  Successfully built RubyGem
  Name: puppet
  Version: 7.31.0
  File: puppet-7.31.0-x86-mingw32.gem
  Successfully built RubyGem
  Name: puppet
  Version: 7.31.0
  File: puppet-7.31.0-x64-mingw32.gem
  Successfully built RubyGem
  Name: puppet
  Version: 7.31.0
  File: puppet-7.31.0-universal-darwin.gem
  Successfully built RubyGem
  Name: puppet
  Version: 7.31.0
  File: puppet-7.31.0.gem
```

**Comment by AriaXLi** [comment]
Building gems with `gem build`:
```
❯ gem build puppet.gemspec --platform universal-darwin
gem build puppet.gemspec --platform universal-darwin
  Successfully built RubyGem
  Name: puppet
  Version: 7.31.0
  File: puppet-7.31.0-universal-darwin.gem
```

```
❯ gem build puppet.gemspec --platform x64-mingw32
gem build puppet.gemspec --platform x64-mingw32
  Successfully built RubyGem
  Name: puppet
  Version: 7.31.0
  File: puppet-7.31.0-x64-mingw32.gem
```

```
❯ gem build puppet.gemspec --platform x86-mingw32
gem build puppet.gemspec --platform x86-mingw32
  Successfully built RubyGem
  Name: puppet
  Version: 7.31.0
  File: puppet-7.31.0-x86-mingw32.gem
  ```

**Comment by AriaXLi** [comment]
Successfully built gem using 'gem build puppet.gemspec':

```
❯ gem build puppet.gemspec
gem build puppet.gemspec
  Successfully built RubyGem
  Name: puppet
  Version: 7.31.0
  File: puppet-7.31.0.gem
```

```
❯ gem build puppet.gemspec --platform universal-darwin
gem build puppet.gemspec --platform universal-darwin
  Successfully built RubyGem
  Name: puppet
  Version: 7.31.0
  File: puppet-7.31.0-universal-darwin.gem
```

```
❯ gem build puppet.gemspec --platform x64-mingw32
gem build puppet.gemspec --platform x64-mingw32
  Successfully built RubyGem
  Name: puppet
  Version: 7.31.0
  File: puppet-7.31.0-x64-mingw32.gem
```

```
❯ gem build puppet.gemspec --platform x86-mingw32
gem build puppet.gemspec --platform x86-mingw32
  Successfully built RubyGem
  Name: puppet
  Version: 7.31.0
  File: puppet-7.31.0-x86-mingw32.gem
  ```

**Comment by AriaXLi** [comment]
Diffs to verify that the gems are being built correctly:
```
❯ diff <(gem specification puppet-7.30.0.gem) <(gem specification puppet-7.31.0.gem)
4c4
<   version: 7.30.0
---
>   version: 7.31.0
11c11
< date: 2024-04-09 00:00:00.000000000 Z
---
> date: 2012-08-17 00:00:00.000000000 Z
171c171,173
< description: Puppet, an automated configuration management tool
---
> description: |
>   Puppet, an automated administrative engine for your Linux, Unix, and Windows systems, performs administrative tasks
>   (such as adding users, installing packages, and updating server configurations) based on a centralized specification.
```

```
❯ diff <(gem specification puppet-7.30.0-universal-darwin.gem) <(gem specification puppet-7.31.0-universal-darwin.gem)
4c4
<   version: 7.30.0
---
>   version: 7.31.0
11c11
< date: 2024-04-09 00:00:00.000000000 Z
---
> date: 2012-08-17 00:00:00.000000000 Z
185c185,187
< description: Puppet, an automated configuration management tool
---
> description: |
>   Puppet, an automated administrative engine for your Linux, Unix, and Windows systems, performs administrative tasks
>   (such as adding users, installing packages, and updating server configurations) based on a centralized specification.
```

```
❯ diff <(gem specification puppet-7.30.0-x64-mingw32.gem) <(gem specification puppet-7.31.0-x64-mingw32.gem)
4c4
<   version: 7.30.0
---
>   version: 7.31.0
11c11
< date: 2024-04-09 00:00:00.000000000 Z
---
> date: 2012-08-17 00:00:00.000000000 Z
199c199,201
< description: Puppet, an automated configuration management tool
---
> description: |
>   Puppet, an automated administrative engine for your Linux, Unix, and Windows systems, performs administrative tasks
>   (such as adding users, installing packages, and updating server configurations) based on a centralized specification.
```

```
❯ diff <(gem specification puppet-7.30.0-x86-mingw32.gem) <(gem specification puppet-7.31.0-x86-mingw32.gem)
4c4
<   version: 7.30.0
---
>   version: 7.31.0
11c11
< date: 2024-04-09 00:00:00.000000000 Z
---
> date: 2012-08-17 00:00:00.000000000 Z
199c199,201
< description: Puppet, an automated configuration management tool
---
> description: |
>   Puppet, an automated administrative engine for your Linux, Unix, and Windows systems, performs administrative tasks
>   (such as adding users, installing packages, and updating server configurations) based on a centralized specification.
```

**Comment by AriaXLi** [comment]
Rake task works too!
```
❯ bundle exec rake pl_ci:gem_build

  Successfully built RubyGem
  Name: puppet
  Version: 7.31.0
  File: puppet-7.31.0-x86-mingw32.gem
  Successfully built RubyGem
  Name: puppet
  Version: 7.31.0
  File: puppet-7.31.0-x64-mingw32.gem
  Successfully built RubyGem
  Name: puppet
  Version: 7.31.0
  File: puppet-7.31.0-universal-darwin.gem
  Successfully built RubyGem
  Name: puppet
  Version: 7.31.0
  File: puppet-7.31.0.gem
  ```

**Review by joshcooper — APPROVED** [review]

**Pull request merged**
