### PR TITLE
DOCUMENT-692: Add another reduce example

### PR DESCRIPTION
**Pull request by alexharv074**
This adds an example of how to use the `reduce` function to iteratively
update a Hash of Hashes.

### CODE REVIEW

**Comment by alexharv074** [comment]
@hlindberg

**Comment by alexharv074** [comment]
Note that `CONTRIBUTING.md` does not say which branch to target, so I targeted master.

**Comment by alexharv074** [comment]
I don't believe I caused the AppVeyor build to fail.

**Comment by hlindberg** [comment]
The commits on this PR are about separate things. Suggest making multiple PRs.

**Comment by hlindberg** [comment]
The updated documentation for reduce is ok to merge - the other commits with changes to Rakefile and an acceptance test is for someone else to review.

**Comment by alexharv074** [comment]
@hlindberg updated. Also, I somehow ended up with someone else's commits on my branch, which doesn't make much sense to me. Anyway, should be right now.

**Comment by MosesMendoza** [comment]
Thanks @alexharv074!

**Pull request merged**
