### PR TITLE
(docs) update user resource attributes aix

### PR DESCRIPTION
**Pull request by jbondpdx**

### CODE REVIEW

**Comment by melissa** [comment]
Not related specifically to this change, but I noticed we also have
```
    newproperty(:keys, :parent => Puppet::Property::KeyValue, :required_features => :manages_solaris_rbac) do
      desc "Specify user attributes in an array of key = value pairs."

      def membership
        :key_membership
      end
    end
```
which is either very confusing, or a copy/pasta error

Would you be willing to look into updating that property description as well?

**Comment by jbondpdx** [comment]
> Not related specifically to this change, but I noticed we also have
> 
> ```
>     newproperty(:keys, :parent => Puppet::Property::KeyValue, :required_features => :manages_solaris_rbac) do
>       desc "Specify user attributes in an array of key = value pairs."
> 
>       def membership
>         :key_membership
>       end
>     end
> ```
> 
> which is either very confusing, or a copy/pasta error
> 
> Would you be willing to look into updating that property description as well?

Happy to! What should it be? (This message may be influenced by lack of coffee.)

**Comment by melissa** [comment]
> > Not related specifically to this change, but I noticed we also have
> > ```
> >     newproperty(:keys, :parent => Puppet::Property::KeyValue, :required_features => :manages_solaris_rbac) do
> >       desc "Specify user attributes in an array of key = value pairs."
> > 
> >       def membership
> >         :key_membership
> >       end
> >     end
> > ```
> > which is either very confusing, or a copy/pasta error
> > Would you be willing to look into updating that property description as well?
> 
> Happy to! What should it be? (This message may be influenced by lack of coffee.)

I have no idea, but I feel like what it currently is isn't ideal... Maybe change `user attributes` to `keys`? We should get someone more familiar with AIX to help out! @geoffnichols ?

Also, don't let this line of thought bog down this work. We can always get this in, and open a new PR for any follow up work

**Comment by jbondpdx** [comment]
The ticket for this work is DOC-3872. Maybe the other chunk is better as another PR then. Thank you, @melissa !

**Comment by melissa** [comment]
Thanks for the clarification on the background to this work @jbondpdx ! My approval stands. I'll let @puppetlabs/platform-os merge this in though

**Pull request merged**
