### PR TITLE
fix: Adjust the elapsed method to a more suitable shape.

### PR DESCRIPTION
**Pull request by haroldofurtado**

### CODE REVIEW

**Comment by joshcooper** [comment]
Hi @haroldofurtado thanks for your contribution. Can you amend your git commit to describe what problem you're solving?

We do have an old ticket about using monotonic counters for profiling (https://puppet.atlassian.net/browse/PUP-7520) but I'm not sure if that's similar to the issue you're trying to solve?

**Comment by joshcooper** [comment]
Hi @haroldofurtado could you review my last comment?

**Comment by joshcooper** [comment]
Hi @haroldofurtado we haven't heard from you and will close this in a few weeks if there's still no reply.

**Comment by haroldofurtado** [comment]
If we already have a solution, this PR can be closed. Thanks for reporting it.

**Pull request closed without merging**
