### PR TITLE
(PUP-6945) acceptance: lookup rich data values

### PR DESCRIPTION
**Pull request by er0ck**
(PUP-6945) acceptance: lookup rich data values

    Add an acceptance test assuring lookup of rich data values.
    We test against agent run and lookup cli using a Sensitive data value in
    both ruby and puppet functions

    [skip ci]

    (maint) acceptance: move general lookup test out of parser_function dir

    [skip ci]

### CODE REVIEW

**Comment by er0ck** [comment]
@hlindberg, @thallgren:
this works as-is, but is using hiera v4 configs and produces:
```
      Warning: Defining environment_data_provider='function' in environment.conf is deprecated. A 'lookup.yaml' file should be used instead
         (in /etc/puppetlabs/code/environments/lookup_rich_values_u3a4ni2v/environment.conf)
      Warning: Using of legacy data provider function 'environment::data'. Please convert to a 'data_hash' function
         (file & line not available)
```

can someone point me at howto config in the v5 way?
meanwhile i'll start digging into the spec tests to see how it's done there..

**Comment by thallgren** [comment]
I see two things.
1. This warning message refers to 'lookup.yaml' which means that this PR should be rebased. PUP-6942 removes the lookup.yaml in favor of always using hiera.yaml.

With that in place, change the test to use a version 5 _data_hash_ function:

1. Remove the `environment_data_provider = "function"` setting in _environment.conf_.
2. Change the _hiera.yaml_ file into:
```
---
version: 5
hierarchy:
  - name: Test
    data_hash: rich_data_test
```
3. Rename the function to `rich_data_test` and modify it to take two parameters:
```
Puppet::Functions.create_function(:rich_data_test) do
  def rich_data_test(options, context)
    {
      'environment_key' => Puppet::Pops::Types::PSensitiveType::Sensitive.new("#{sensitive_value_rb}"),
    }
  end
end
```
An alternative to #3 is to remove the Ruby function and instead use a Puppet function, i.e. create a _rich_data_test.pp_ under _/functions_ with the following content:
```
function rich_data_test(options, context) {
  {
    environment_key => Sensitive("#{sensitive_value_rb}")
  }
}
```

**Comment by er0ck** [comment]
thanks Thomas!

yeah, a later build gives:
```
    idosxnpkpepttls.delivery.puppetlabs.net (idosxnpkpepttls.delivery.puppetlabs.net) 16:15:36$ puppet lookup --environment lookup_rich_values_98jklq7t environment_key
      Warning: /etc/puppetlabs/code/environments/lookup_rich_values_98jklq7t/hiera.yaml: Use of 'hiera.yaml' version 4 is deprecated. It should be converted to version 5
         (in /etc/puppetlabs/code/environments/lookup_rich_values_98jklq7t/hiera.yaml)
      Warning: Defining environment_data_provider='function' in environment.conf is deprecated
         (in /etc/puppetlabs/code/environments/lookup_rich_values_98jklq7t/environment.conf)
      Warning: Using of legacy data provider function 'environment::data'. Please convert to a 'data_hash' function
         (file & line not available)
      --- !ruby/object:Puppet::Pops::Types::PSensitiveType::Sensitive
      value: foot, no mouth
```

interesting, however, that puppet agent -t doesn't give the same warnings:
```
    rw8anb6cfzdb44n.delivery.puppetlabs.net (rw8anb6cfzdb44n.delivery.puppetlabs.net) 16:15:48$ puppet agent -t --server idosxnpkpepttls.delivery.puppetlabs.net --environment lookup_rich_values_98jklq7t
      Info: Using configured environment 'lookup_rich_values_98jklq7t'
      Info: Retrieving pluginfacts
      Notice: /File[/opt/puppetlabs/puppet/cache/facts.d]/mode: mode changed '0755' to '0777'
      Info: Retrieving plugin
      Info: Caching catalog for rw8anb6cfzdb44n.delivery.puppetlabs.net
      Info: Applying configuration version '1481213751'
      Notice: foot, no mouth
      Notice: /Stage[main]/Main/Notify[foot, no mouth]/message: defined 'message' as 'foot, no mouth'
      Notice: Applied catalog in 0.07 seconds
```

**Comment by er0ck** [comment]
@thallgren @hlindberg 
anytime we want to lookup values from a function we use the keyword `data_hash`?

any information on reasoning behind this?  i find it surprising and confusing on many levels.

**Comment by thallgren** [comment]
@er0ck , in short there are three types of functions, the `data_hash` is one of them. A `data_hash` function works exactly as the function did in version 4 (it's supposed to return a hash). We also have a `lookup_key` function. It will be called with a key and is supposed to return a value for that key. Its intended use is for forwarding the lookup to some other service like LDAP or a database. There's also a specialization of the `lookup_key` function named `data_dig`. The difference being that a `data_dig` function will "dig into" a dotted key.

**Comment by thallgren** [comment]
The warnings are under control of the `strict` option. Perhaps that's set to `off` in the agent?

**Comment by er0ck** [comment]
cool.  i'm good with those options and recognize their possible usefulness from the user stories.

if i use the data_hash method in a ruby function (i'm also testing with a pp function here) and your setup above i don't get a value on lookup cli for `environment_key`

you are right about the warnings.  i forgot they were under strict

**Comment by thallgren** [comment]
Odd that you don't get the value back. Can you turn on debug? Should give you a full explanation of what's going on.

**Comment by er0ck** [comment]
```
      Test Case tests/lookup/lookup_rich_values.rb reported: #<Beaker::Host::CommandFailure: Host 'idosxnpkpepttls.delivery.puppetlabs.net' exited with 1 running:
     puppet lookup --debug --environment lookup_rich_values_mueq6d0r environment_key
    Last 10 lines of output were:
        Debug: Facter: resolving Xen facts.
        Debug: Evicting cache entry for environment 'lookup_rich_values_mueq6d0r'
        Debug: Caching environment 'lookup_rich_values_mueq6d0r' (ttl = 0 sec)
        Debug: Performing a hiera indirector lookup of lookup_options with options {:variables=>Scope(Class[main]), :merge=>#<Puppet::Pops::HashMergeStrategy:0x000000031d0f80 @options_t=#<Puppet::Pops::Types::PStructType:0x000000031c11
e8 @elements=[#<Puppet::Pops::Types::PStructElement:0x000000031c1210 @key_type=#<Puppet::Pops::Types::POptionalType:0x000000031c1238 @type=#<Puppet::Pops::Types::PStringType:0x000000031c1260 @size_type_or_value="strategy">>, @value_typ
e=#<Puppet::Pops::Types::POptionalType:0x000000031c13c8 @type=#<Puppet::Pops::Types::PPatternType:0x000000031c1440 @patterns=[#<Puppet::Pops::Types::PRegexpType:0x000000031c1558 @pattern="hash", @regexp=/hash/>]>>>]>, @options={}>}
        Debug: hiera(): Hiera YAML backend starting
        Debug: hiera(): Looking up lookup_options in YAML backend
        Debug: hiera(): Looking for data source nodes/idosxnpkpepttls.delivery.puppetlabs.net
        Debug: hiera(): Cannot find datafile /etc/puppetlabs/code/environments/lookup_rich_values_mueq6d0r/hieradata/nodes/idosxnpkpepttls.delivery.puppetlabs.net.yaml, skipping
        Debug: hiera(): Looking for data source common
        Debug: hiera(): Cannot find datafile /etc/puppetlabs/code/environments/lookup_rich_values_mueq6d0r/hieradata/common.yaml, skipping>
```

**Comment by thallgren** [comment]
The default datadir for versions 4 and up is 'data', not 'hieradata'. The problem is probably related to that somehow, given the message:
```
Cannot find datafile /etc/puppetlabs/code/environments/lookup_rich_values_mueq6d0r/hieradata/common.yaml
```

**Comment by er0ck** [comment]
interesting.  i don't think i'm setting that option.  and i'm not using hiera datafiles.  just the functions

**Comment by whopper** [comment]
👍 
tests/lookup/lookup_rich_values.rb passed in 26.97 seconds
      Test Suite: tests @ 2016-12-12 10:58:43 -0800

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 26.97 seconds
      Average Test Time: 26.97 seconds
              Attempted: 1
                 Passed: 1
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 1

      - Specific Test Case Status -

**Pull request merged**
