### PR TITLE
(PUP-6823) Filebucket should evaluate server_list

### PR DESCRIPTION
**Pull request by melissa**
Prior to this commit, the filebucket app would ignore server_list if a
user had set it. It would only honor server. This commit updates
filebucket to take the first entry from server_list if set, otherwise
take server.

### CODE REVIEW

**Comment by melissa** [comment]
Currently running beaker tests now

**Comment by melissa** [comment]
Successfully ran testing against el7 using a one-off build of puppet-agent that contains these changes

```
be rake ci:test:aio SHA=89b4364e3b128a9f7ce82275d10069c44320659a SUITE_VERSION=5.3.3.310.g89b4364 TEST_TARGET=redhat7-64a OPTIONS='--preserve-hosts=always'
```

**Comment by melissa** [comment]
I want to ask about integration tests for this change. I was talking to @ericldelaney, and this does seem like something we'd want a bit more test coverage on to make sure it is doing the right thing, and is consistent about it in the future. Thoughts?

**Comment by ericldelaney** [comment]
@melissa the tests and what they cover look good to me for this ticket.

**Pull request merged**
