### PR TITLE
(PUP-10446) Remove application orchestration

### PR DESCRIPTION
**Pull request by joshcooper**
Remove the `environment` catalog rest API

Remove application, site, produces and consumes from the grammar. Any use of those keywords will produce a syntax error.

/cc @Magisus @justinstoller this may affect puppetserver due to the removed environment catalog API

### CODE REVIEW

**Comment by joshcooper** [comment]
Prior to making any changes, I found that running `bundle exec rake gen_eparser` produced a different `eparser.rb` than was checked in. I'm not sure why that is? Presumably the grammar was updated but the parser wasn't? Or there's some non-deterministic behavior. So there are two "Generate eparser..." commits. One to update the eparser to bring it up to date. And another after I made the grammar changes.

**Comment by joshcooper** [comment]
PR https://github.com/puppetlabs/puppetserver/pull/2411 should be merged first so that we don't break puppetserver.

**Review by hlindberg — APPROVED** [review]
App orchestration R.I.P ! Great to see all this baggage go away.
PR looks fine to me (I looked especially at lexer, and parser). Good to keep the keywords as reserved.

**Comment by Magisus** [comment]
Jenkins, please test this

**Comment by joshcooper** [comment]
jenkins please test this

**Comment by Magisus** [comment]
Do we know if the auto-Jenkins trigger works with puppetserver on this branch?

**Comment by joshcooper** [comment]
jenkins please test this with servertests

**Comment by justinstoller** [comment]
This looks good, though I don't think I'm _super_ qualified to say it doesn't have farther reaching implications. A couple things I did note:

1. It looks like [add_mapping](https://github.com/puppetlabs/puppet/blob/main/lib/puppet/pops/parser/parser_support.rb#L181) is now orphaned.
2. We should remove the [relevant routes](https://github.com/puppetlabs/puppetserver/blob/6.x/src/clj/puppetlabs/services/master/master_core.clj#L1133-L1137) in puppetserver.

**Comment by joshcooper** [comment]
> 1. add_mapping

I'll look into this/amend this PR

> 2. remove relevant routes

I missed those in my earlier puppetserver PR. I have a new PR for that https://github.com/puppetlabs/puppetserver/pull/2414

**Comment by joshcooper** [comment]
jenkins please test this with servertests

**Comment by joshcooper** [comment]
jenkins please test this with servertests

**Pull request merged**
