### PR TITLE
(PUP-11666) Mark resources type as valid for hosts and devices

### PR DESCRIPTION
**Pull request by seanmil**
The resources type is useful on both hosts and devices and is compatible as is in both modes.

### CODE REVIEW

**Comment by joshcooper** [comment]
rspec-mocks published a new gem that broke puppet tests. You'll need to rebase on https://github.com/puppetlabs/puppet/commit/95291a93d81b701dd4937b83a5829946ea4645de for tests to pass. Otherwise, change looks good.

**Comment by seanmil** [comment]
@joshcooper Thanks! Rebased.

**Comment by joshcooper** [comment]
@seanmil could you rebase on 7.x if needed?

**Review by joshcooper — APPROVED** [review]

**Comment by seanmil** [comment]
> @seanmil could you rebase on 7.x if needed?

@joshcooper  Rebased from `7.x` & Pushed.  Do I need to open a new PR with a different target branch?  7.x?

**Comment by mhashizume** [comment]
@seanmil I've edited your PR to target 7.x, I will close and reopen this PR to retrigger checks. Thank you!

**Comment by mhashizume** [comment]
Thanks for your contribution @seanmil !

**Pull request merged**
