### PR TITLE
(docs)(DOC-5035) Remove "master" in generated docs

### PR DESCRIPTION
**Pull request by clairecadman**

### CODE REVIEW

**Comment by GabrielNagy** [comment]
This looks good to me @clairecadman, thanks!

PR tests are failing because of the commit message:
```
	The commit summary (i.e. the first line of the commit message) should start with one of:
		(PUP-<digits>) # this is most common and should be a ticket at tickets.puppet.com
		(docs)
		(docs)(DOCUMENT-<digits>)
		(maint)
		(packaging)
		(L10n)
```

Tests should pass if you change your commit message to something like `(docs)(DOC-5035) Remove "master" in generated docs`. Let me know if you need any help with that.

**Comment by clairecadman** [comment]
@GabrielNagy does that work?

**Review by GabrielNagy — APPROVED** [review]

**Comment by clairecadman** [comment]
Please let me know when the merge to main happens. Thanks!

**Review by joshcooper — APPROVED** [review]
I'll merge when checks pass

**Pull request merged**
