### PR TITLE
(docs) exec resources are non-isomorphic (duplicate namevars allowed)

### PR DESCRIPTION
**Pull request by nfagerlund**
hi. :)

I can't believe this wasn't written down anywhere before, but anyway, I was actually using it in anger and had to double-check that it worked like I remembered.

### CODE REVIEW

**Comment by melissa** [comment]
Hey @nfagerlund! Good to hear from you!

This change looks fine to me, but travis is failing because of the commit format. Could you change `docs:` to `(docs)` in the commit title?

**Comment by nfagerlund** [comment]
@melissa no prob. Good to see you too :)

**Comment by joshcooper** [comment]
Thanks @nfagerlund! I rekicked appveyor, transient failure was unrelated to your PR

**Comment by melissa** [comment]
Oh, should we retarget this at 5.5.x?

**Comment by jtappa** [comment]
Just going to ping @hestonhoffman so these changes make it into 5.5.x docs. I'm pretty sure he said those docs aren't being re-generated any longer, so I'll merge this now as it is.

**Comment by hestonhoffman** [comment]
Here's a ticket so I don't forget :) https://tickets.puppetlabs.com/browse/DOCUMENT-994

**Comment by jbondpdx** [comment]
Yeah, @jtappa , we are generating only new versions as much as possible, because of reasons. We certainly CAN regenerate them if needed though. I think 5.5 is the only 5.x version I could see doing that for.

**Pull request merged**
