### PR TITLE
(PUP-8699) puppet device supports --facts

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by tphoney** [comment]
@joshcooper Another one 😓  look ok ? @DavidS @davidmalloncares  @shermdog

**Comment by tphoney** [comment]
nice @DavidS panos 😮

**Comment by DavidS** [comment]
All @da-ar 's fault :-D

**Comment by tphoney** [comment]
Sorry to be a pain @joshcooper 👀

**Comment by DavidS** [comment]
@puppetlabs/platform-core are y'all fine with the networking team merging code in this area on our own?

**Pull request merged**
