### PR TITLE
(PUP-6269) Backport PUP-3341 to 3.x

### PR DESCRIPTION
**Pull request by robmbrooks**
[PUP-6269](https://tickets.puppetlabs.com/browse/PUP-6269) backporting fix from [PUP-3341](https://tickets.puppetlabs.com/browse/PUP-3341) to 3.x branch

### CODE REVIEW

**Comment by hlindberg** [comment]
There were test failures for Ruby 1.8.7 - respun the spec test run in case it was temporary. It may be a difference in rspec version used on 3.x and 4.x that causes this.
It helps to get it running locally on a ruby 1.8.7 to see if what is going on, and to debug the problem. Maybe original author of tests can spot the problems immediately...

**Comment by robmbrooks** [comment]
I kicked up an Ubuntu 12.04 as this ships with Ruby 1.8.7 and it looks like I have the same failures, not immediately obvious to me why though.

**Comment by hlindberg** [comment]
The first thing to look at is the difference in rspec version (much newer on 4.x vs 3.x). Ping @er0ck - do we need to include backported tests?

**Comment by robmbrooks** [comment]
@hlindberg does the 4.x branch get tested against Ruby 1.8.7?

**Comment by hlindberg** [comment]
We dropped support for Ruby 1.8.7 in 4.x. So... No 4.x testing does not run against Ruby 1.8.7. Puppet 4.x simply does not work on Ruby 1.8.7.
We also updated several gems in 4.x (rspec and mocha specifically).

**Comment by robmbrooks** [comment]
@hlindberg bizarrely the inline scripts appear to have caused the failures with Ruby 1.8.7.

Fixed!

**Comment by branan** [comment]
@robmbrooks This looks good to me, and I think we're nearly ready to merge it in.

One more quick change: would you mind squashing your test fixes into the backport commit to keep the history a bit cleaner? After that I can hit the big green button

**Comment by robmbrooks** [comment]
@branan I think this is correct.

I rebased, squashed the two commits into one and force pushed.

**Comment by robmbrooks** [comment]
@branan the requested commit squash has been done, I think "waiting on contributor" can be removed?

**Comment by HAIL9000** [comment]
Merged, thank you for the contribution @robmbrooks!

**Pull request merged**
