### PR TITLE
Revert "(PUP-4742) Switch to use semantic_puppet gem"

### PR DESCRIPTION
**Pull request by kylog**
Reverts puppetlabs/puppet#4977

### CODE REVIEW

**Comment by kylog** [comment]
IIUC there are two dependencies that need fixing before we can remove the vendored version of the gem:
* puppetserver changes (fuzzy on what this entails)
* the msi needs to include the gem

/cc @justinstoller @haus @joshcooper @hlindberg @geoffnichols 

You've all been involved with different threads about this entangement.

**Comment by joshcooper** [comment]
👍  pending CI

**Comment by haus** [comment]
:+1: from me

**Comment by justinstoller** [comment]
👍 , wrt @joshcooper's comment, is this going through an ad-hoc pipeline?

**Comment by joshcooper** [comment]
Oh I just meant travis/appveyor

**Pull request merged**
