### PR TITLE
(PUP-5004) Add node definitions for Fedora 22 to the source repos

### PR DESCRIPTION
**Pull request by er0ck**

### CODE REVIEW

**Comment by johnduarte** [comment]
@er0ck is this PR against the correct branch? These should be added 4.2.x, so I would expect to be based against `master`

**Comment by kylog** [comment]
stable is for 4.2.x, master is for 4.3.x

**Comment by kylog** [comment]
@er0ck the previous PR also dropped the fedora21.yaml config (which I didn't realize existed). Should we do the same here?

**Comment by er0ck** [comment]
on it...

On Thu, Aug 6, 2015 at 11:36 AM, Kylo Ginsberg <notifications@github.com>
wrote:

> @er0ck <https://github.com/er0ck> the previous PR also dropped the
> fedora21.yaml config (which I didn't realize existed). Should we do the
> same here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/puppetlabs/puppet/pull/4139#issuecomment-128469102>.
>



-- 
Eric Thompson
eric.thompson@puppetlabs.com <erict@puppetlabs.com>
Senior Software Quality Assurance Engineer

**Comment by johnduarte** [comment]
LGTM :+1:

**Pull request merged**
