### PR TITLE
(PUP-10583) Change default digest_algorithm to SHA256

### PR DESCRIPTION
**Pull request by GabrielNagy**
Puppet's `digest_algorithm` setting defaults to `md5`, which is outdated. This commit switches it to to `sha256`.

Update spec tests accordingly.

### CODE REVIEW

**Comment by GabrielNagy** [comment]
@joshcooper I skipped the following test https://github.com/puppetlabs/puppet/blob/537b0849c2bca6001b6927ca90c23aa3235606f4/spec/unit/indirector/file_bucket_file/file_spec.rb#L42 since there are no known SHA256 collisions. Should we change the default digest for this test to `md5` and still run it?

**Comment by joshcooper** [comment]
The `puppet agent multiple agents running exits if an agent is already running` transient seems to be failing often on Windows Ruby 2.7. Not sure what's up with that, maybe ruby is raising a different exception when the error happens?

**Comment by joshcooper** [comment]
Looks good! I forgot about a couple of other areas where md5 is still referenced/used:

* lib/puppet/application/filebucket.rb: the help still references md5. Maybe better to say it defaults to `Puppet[:default_digest]`?
* lib/puppet/defaults.rb: We should move `md5` to the last position in the `valid_digest_algorithms` array (when fips is disabled) as it is also used to define the agent's `Puppet[:supported_checksum_types]`, which is the agent's list of preferred algorithms when it requests a catalog.
* lib/puppet/file_serving/http_metadata.rb: the `collect` method should prefer `sha256` over `md5`.
* lib/puppet/http/service/compiler.rb: the `post_catalog` method references the default checksum types. Maybe delete the "currently defaults to part"?
* lib/puppet/http/service/fileserver.rb: `checksum_type` parameter in the `get_file_metadata` comments need updating
* lib/puppet/type/file/checksum.rb: description needs updating

**Comment by GabrielNagy** [comment]
@joshcooper I pushed a separate commit with the latest changes so it's easier to review. Let me know if I missed anything.

There was some non-ASCII whitespace at https://github.com/puppetlabs/puppet/pull/8315/commits/5ceb33c0cb3a1b02cee14b7a9c96793fc42b1209#diff-908b50f77db1b5645f5c125514deccd3R798 which I removed.

**Comment by Dorin-Pleava** [comment]
LGTM, also locally tested filebucket, and it works as expected.

**Review by Dorin-Pleava — APPROVED** [review]

**Review by joshcooper — APPROVED** [review]
LGTM. One nit, could you update the commit message for 5ceb33c0cb3a1b02cee14b7a9c96793fc42b1209 to mention that it changes the checksum precedence.

**Comment by joshcooper** [comment]
jenkins please test this on redhat7-64a,ubuntu1804-64a,windows2019-64a with servertests

**Comment by GabrielNagy** [comment]
jenkins please test this on redhat7-64a,ubuntu1804-64a,windows2019-64a with servertests

**Comment by joshcooper** [comment]
Dang, I forgot there were some CI failures when running `medium` tests manually. Could you update these tests?

```
bx rake ci:test:aio TESTS=tests/parser_functions/calling_all_functions.rb,tests/puppet_apply_a_file_should_create_a_file_and_report_the_md5.rb,tests/resource/file/content_attribute.rb,tests/resource/file/source_attribute.rb,tests/ticket_6541_invalid_filebucket_files.rb SHA=e6c176914d8a1effe6920843fd05b755def07ed0 SERVER_VERSION=6.13.1.SNAPSHOT.2020.09.04T1735 TEST_TARGET=redhat7-64a OPTIONS='--preserve-hosts=always'
...
Failed Tests Cases:
 Test Case tests/parser_functions/calling_all_functions.rb reported: #<Minitest::Assertion: digest output didn't match expected value...
  Test Case tests/puppet_apply_a_file_should_create_a_file_and_report_the_md5.rb reported ...
  Test Case tests/ticket_6541_invalid_filebucket_files.rb reported:...
```

**Pull request merged**
