### PR TITLE
(maint) Remove dead method and add unit tests

### PR DESCRIPTION
**Pull request by joshcooper**
These commits were part of a different PR that became obsolete once we changed how file metadata was generated. Submitting these separately as I think they're still relevant.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Still blocked?

**Comment by joshcooper** [comment]
I'm thinking we should resolve PUP-4748 first as there may be some changes to code this PR adds tests for.

**Comment by joshcooper** [comment]
Needs to be retargeted to stable

**Comment by MikaelSmith** [comment]
You planning to do that?

**Comment by joshcooper** [comment]
yep, working on that now

**Pull request closed without merging**
