### PR TITLE
(PUP-5032) Change configured_environment behavior

### PR DESCRIPTION
**Pull request by MikaelSmith**

### CODE REVIEW

**Comment by joshcooper** [comment]
minor nit, can we change the environment related log messages:

```
Info: Using configured environment "qa"
Notice: Local environment: "production" doesn't match server specified node environment "dev", switching agent to "dev".
```

to use single quotes like we do for other quoted output:

```
Debug: Failed to load library 'selinux' for feature 'selinux'
Debug: Evicting cache entry for environment 'production'
Info: Applying configuration version '1441921914'
```

**Comment by MikaelSmith** [comment]
Yup.

**Comment by MikaelSmith** [comment]
Updated.

**Comment by joshcooper** [comment]
cool thanks, waiting for appveyor, will merge after.

**Pull request merged**
