### PR TITLE
(PUP-6806) Update beaker version to 3.1.0 to allow for MacOS Sierra t…

### PR DESCRIPTION
**Pull request by McdonaldSeanp**
…esting

### CODE REVIEW

**Comment by Magisus** [comment]
👍

**Comment by McdonaldSeanp** [comment]
This will wait on some manual validation from myself and @Magisus . will update if those go green

**Comment by Magisus** [comment]
All puppet tests run as expected on EL4 with beaker 3.1.0.

**Comment by McdonaldSeanp** [comment]
Blocked on https://github.com/puppetlabs/puppet/pull/5323

**Comment by McdonaldSeanp** [comment]
We have manually validated el Ubuntu and (current) windows targets, this is free to merge now.

**Comment by MosesMendoza** [comment]
@McdonaldSeanp or @Magisus do you happen to still have the output from those runs lying around somewhere? If so, want to link a gist?

**Comment by McdonaldSeanp** [comment]
@MosesMendoza , https://tickets.puppetlabs.com/secure/attachment/37543/windows.log is available as the log for the passing windows-2012r2 test run.

**Comment by MosesMendoza** [comment]
I plan to merge this Tues AM PDT (and then we can watch it go through acceptance)

**Comment by Magisus** [comment]
The log for a Centos 4 run: https://tickets.puppetlabs.com/secure/attachment/37544/el4-beaker3.1.0-test_result.txt

**Pull request merged**
