### PR TITLE
(PUP-5520) Exclude Yocto init scripts from service init provider

### PR DESCRIPTION
**Pull request by shermdog**
Yocto Linux ships a series of init scripts that are not safe to execute.  This creates unintended consequences such as sending shutdown signals to daemons.
This commit excludes the known list of unsafe scripts so that Puppet does not try to execute them via the service init provider.

### CODE REVIEW

**Comment by glennmatthews** [comment]
They do not - thanks for checking. :+1: from me.

**Comment by shermdog** [comment]
For reference:  https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/recipes-core/initscripts/initscripts-1.0

**Comment by joshcooper** [comment]
Is this targeting the right branch? Currently, stable is for 4.3.x and master will eventually be 4.4.x

**Comment by shermdog** [comment]
@joshcooper if that's the case I need to re-issue the PR against stable.  We're targeting 4.3.2.

**Pull request closed without merging**
