### PR TITLE
(maint) fixing a typo: :slize_size to :slice_size

### PR DESCRIPTION
**Pull request by mschuchard**
Fairly certain from searching the codebase and google that this is fixing a typo in the slice function.

I did not conform to the contributing guidelines on this because it was such a trivial fix, but I can cancel the PR and go through the process if need be.

### CODE REVIEW

**Comment by mschuchard** [comment]
Side comment: there seems to be a problem with a deprecated check specified in the rubocop.yml in the project as of rubocop 0.36.0.

```
Error: /home/matt/git_repos/puppet/.rubocop.yml: Lint/SpaceBeforeFirstArg has the wrong namespace - should be Style Error: The Style/TrailingComma cop no longer exists. Please use Style/TrailingCommaInLiteral and/or Style/TrailingCommaInArguments instead. (configuration found in /home/matt/git_repos/puppet/.rubocop.yml)
```

I am unsure which of the checks you actually want here so I am not making the fix myself.

**Comment by kylog** [comment]
@mschuchard puppet is still on rubocop 0.26: https://github.com/puppetlabs/puppet/blob/4f3a383d44c2f46283d09a2ec7399e35e4edd072/Gemfile#L49

Not that we aren't interested in updating btw, just haven't gotten to it :)

**Comment by hlindberg** [comment]
Fine - the param names are only used in error messages and documentation. Does not alter any behavior. I am merging this.

**Comment by hlindberg** [comment]
@mschuchard - one small thing, can you modify the commit so its first line says:
```
(maint) Fix typo :slize_size to :slice_size
```
It will otherwise set of alarm bells when we do the release :-)

**Comment by mschuchard** [comment]
> @mschuchard puppet is still on rubocop 0.26: https://github.com/puppetlabs/puppet/blob/4f3a383d44c2f46283d09a2ec7399e35e4edd072/Gemfile#L49

Thanks for the clarification.

> Fine - the param names are only used in error messages and documentation. Does not alter any behavior. I am merging this.

Makes sense.  RSpec would probably have caught an actual problem with 'slice.'

> @mschuchard - one small thing, can you modify the commit so its first line says:

Sure thing.  Amended the commit and pushed the changed commit message.  Also edited the PR title for good measure.

**Comment by kylog** [comment]
@mschuchard you picked up another commit along the way. Can you rebase/squash back to your one commit (but keep the amended commit message :))?

Thanks!

**Comment by mschuchard** [comment]
Apologies: I clicked 'update branch' without thinking.  Redid the force push and everything should be good now.

**Comment by kylog** [comment]
Thanks @mschuchard!!!

**Pull request merged**
