### PR TITLE
(PUP-9928) Cleanup puppetres.dll

### PR DESCRIPTION
**Pull request by Dorin-Pleava**
New installers no longer use puppetres.dll, so the file won't be copied
when installing puppet-agent.

### CODE REVIEW

**Comment by Dorin-Pleava** [comment]
Puppetres.dll is no longer present on a fresh installation of puppet-agent, so when uninstalling puppet agent, `%PROGRAMDIR%\Puppet Labs\..` is deleted entirely.

**Comment by Dorin-Pleava** [comment]
If puppetres.dll is present from an older version of puppet-agent, the uninstaller will not delete the file. 
Investigating if a cleanup script can delete the file without any issues.

**Comment by Dorin-Pleava** [comment]
As the new version no longer overrides puppetres.dll, even if puppetres.dll is loaded and locked, the installer won't trigger the DHCP restart, but the file still cannot be deleted(maybe moved using the workaround solution).

**Comment by Dorin-Pleava** [comment]
A simple solution would be to keep the file there and not interfere with it if it is loaded/locked.
Another solution would be that upon install/uninstall to delete the file if it is not loaded, but if it is loaded,do nothing.

**Comment by Dorin-Pleava** [comment]
Using the first solution, so the installer will not interfere with puppetres.dll for the moment.

**Comment by joshcooper** [comment]
jenkins please test this on windows2012r2-64a,windows10ent-32a

**Comment by jcoconnor** [comment]
Putting DNM back on as this *must* not merge until https://github.com/puppetlabs/puppet-agent/pull/1749 is merged.

**Pull request merged**
