### PR TITLE
Maint/master/revert waitforlock

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by johnduarte** [comment]
The changes to the unit test file do not appear in this PR????

It looks like another revert is needed to remove the unit tests associated with https://github.com/puppetlabs/puppet/commit/b6095ea9d91647362c6a44a4f15098e88d8787b9

https://github.com/puppetlabs/puppet/commit/b6095ea9d91647362c6a44a4f15098e88d8787b9#diff-4182e2d80f6f6fd20e3fac1bcf36dbe0

Also changes from https://github.com/puppetlabs/puppet/pull/8103

**Comment by melissa** [comment]
@johnduarte I removed the unit tests in https://github.com/puppetlabs/puppet/pull/8104/commits/e5f34e3eecb0465bdb7b3d75c32580135ceac041, so the two main waitforlock commits combined means there were no changes to the unit test files.

https://github.com/puppetlabs/puppet/pull/8104/commits/bd81952891a842452cacd6fc163d82300d7837de takes care of the changes from  #8103, which were primarily whitespace changes

**Comment by melissa** [comment]
I can push up changes with the merge commits reverted if you'd prefer. I just grabbed the three commits introduced in both prs because it was faster for me to do

**Comment by joshcooper** [comment]
I don't have a preference here, but more for future reference. Reverting the merge also makes sure you don't miss a commit

**Pull request merged**
