### PR TITLE
(PUP-8581) Move zone to vendored module directory

### PR DESCRIPTION
**Pull request by joshcooper**
Moves zone type, provider and tests to vendored module directory in preparation for extraction.

### CODE REVIEW

**Comment by joshcooper** [comment]
PR https://github.com/puppetlabs/puppet/pull/6782 needs to be merged first.

**Comment by jhelwig** [comment]
@joshcooper The acceptance test related things appear to be partially moved into spec related directories in the module? Won't that mean that we'll try to run the beaker/acceptance test as though it's an rspec test?

**Comment by joshcooper** [comment]
Good question. I realized PR#6782 isn't quite right as we need to exclude `spec/acceptance` for rspec tests.

I was thinking of not running beaker tests in puppet CI. Instead focus on extracting the module and reworking the beaker tests (post extraction) to conform to modules best practices. Thoughts?

**Comment by jhelwig** [comment]
I'm not sure what the module best practices are, but from a Ruby standpoint, I'd be really surprised to find anything other than rspec tests under the `spec` directory. I would expect the beaker tests to live in an `acceptance` directory along side of the spec directory (or at least not under the spec directory itself). Though, it looks like that ship has already sailed, as it looks like [beaker-rspec](https://github.com/puppetlabs/beaker-rspec) expects things to be under `spec/acceptance`, so... ¯\\(º_o)/¯

Whether I'm worried about being able to run the beaker tests from within the `lib/puppet/vendor` directory really depends on how long things will end up living there. If we're going to be vendoring things in there only to remove them in effectively the next commit, then I'm not concerned about it. If we're going to have things in there across one or more release boundaries, then I think it's important that we be able to run the beaker tests from there.

**Comment by joshcooper** [comment]
We decided this wasn't needed.

**Pull request closed without merging**
