### PR TITLE
(PUP-4123) MASTER (caution) Add infrastructure for migration support

### PR DESCRIPTION
**Pull request by hlindberg**
MERGE AFTER #3738 has been merged to 3.8 to merge those changes and a revert of the functionality that should not be present on master.

### CODE REVIEW

**Comment by kylog** [comment]
@hlindberg as far as when to merge to master, is this something we actually don't want until 4.1?

**Comment by hlindberg** [comment]
@kylog Does not matter actually (this merge only cleans up what will be in 3.8). If we however merge stable -> 3.8 -> master before 4.0 is released, and the PR #3738 has gone into 3.8, then this should be merged. If it is not merged (but 3.8 merged to master before 4.0) performance is slightly worse.

**Comment by hlindberg** [comment]
Hold off on merging this until master is for 4.x

**Comment by kylog** [comment]
@hlindberg or @thallgren: puppet#master is now for 4.1 so we don't need to hold off on merging this any longer. I haven't reviewed this so can't really thumbs-up it but just wanted to confirm that puppet#master is available for 4.1 changes.

**Comment by hlindberg** [comment]
This PR should help in merging 3.x to master. Do this merge first, then merge 3x on top. (There has been additional changes on 3.x. causing conflicts after this PR was made). @thallgren feel free to merge this and rest of 3.x to master

**Pull request merged**
