### PR TITLE
(docs) Minor updates to API docs

### PR DESCRIPTION
**Pull request by nfagerlund**
Hey @dankreek, a note about this showed up in an otherwise unrelated docs ticket. Could you verify that this is true, and Puppet Server CA doesn't support the pluralized version of this? 

When this PR gets merged, please resolve https://tickets.puppetlabs.com/browse/DOC-864!

### CODE REVIEW

**Comment by dankreek** [comment]
That is correct, this endpoint no longer works.

**Comment by nfagerlund** [comment]
Thanks!

**Comment by joshcooper** [comment]
@dankreek by "no longer works" I assume that means "no longer supported by design" (and should be documented as such), as opposed to "no longer works due to a bug and will be fixed"?

**Comment by dankreek** [comment]
That is correct, @joshcooper. Sorry for the poor wording.

**Comment by nfagerlund** [comment]
Ping. I'm pretty sure the test failures here are not a problem with these commits. :)

**Comment by joshcooper** [comment]
Will merge once CI clears

**Pull request merged**
