### PR TITLE
(PUP-10418) Unify service return values

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by melissa** [comment]
@joshcooper the one question I have is about https://github.com/puppetlabs/puppet/blob/master/lib/puppet/indirector/report/rest.rb#L20-L21

It looks like that could probably call `Puppet::HTTP::Service#deserialize(response, Array)` in `Puppet::HTTP::Service::Report#put_report`, then return both the response and the deserialized response body like the other service methods do.

The main difference is how the formatter is found. `Puppet::Network::FormatHandler.format_for(content_type)` versus `Puppet::Network::FormatHandler.mime(header)`. It looks like both methods should return the same thing, since they're both being passed the Content-Type header.

```
  # Return a format capable of handling the provided mime type.
  def self.mime(mimetype)
    mimetype = mimetype.to_s.downcase
    @formats.values.find { |format| format.mime == mimetype }
  end
```
```
  def self.format_for(name)
    name = format_to_canonical_name(name)
    format(name)
  end

  # Return a format name given:
  #  * a format name
  #  * a mime-type
  #  * a format instance
  def self.format_to_canonical_name(format)
    case format
    when Puppet::Network::Format
      out = format
    when %r{\w+/\w+}
      out = mime(format)
    else
      out = format(format)
    end

    if out.nil?
      raise ArgumentError, _("No format matches the given format name or mime-type (%{format})") % {format: format}
    end

    out.name
  end
```

thoughts?

**Comment by melissa** [comment]
Also, it looks like the spec tests are stalling out, so I need to track that down

**Comment by melissa** [comment]
Looks like it starts spinning at https://github.com/puppetlabs/puppet/blob/master/spec/unit/ssl/state_machine_spec.rb#L132

**Comment by joshcooper** [comment]
Looks good! I was thinking since the response is part of the API, we should test that each services' `(get|put|etc)_*` method returns a response object, either as the sole return value or the first entry in the array, like you're doing in https://github.com/puppetlabs/puppet/pull/8096/files#diff-19cc679713d12558cf0da9c8295fa4abR373https://github.com/puppetlabs/puppet/pull/8096/files#diff-19cc679713d12558cf0da9c8295fa4abR373

**Comment by melissa** [comment]
@joshcooper updated

**Comment by joshcooper** [comment]
jenkins please test this with servertests

**Pull request merged**
