### PR TITLE
(PUP-9651) Delete low risk acceptance tests

### PR DESCRIPTION
**Pull request by johnduarte**
This commit removes all acceptance tests that have been audited and
assessed as mitigating a low risk regression.

### CODE REVIEW

**Comment by hlindberg** [comment]
Tests that deal with language related things / functions are certainly fine to delete - those are in minority though so I leave it to someone else to approve.

**Comment by melissa** [comment]
jenkins please test this

**Comment by melissa** [comment]
We'll probably have to modify https://github.com/puppetlabs/puppet/blob/master/acceptance/Rakefile#L36-L48 since some of these tests are going to be removed

**Comment by johnduarte** [comment]
Thanks for pointing out the rake task @melissa I have added a commit to remove the test affected from the Rakefile.

**Comment by melissa** [comment]
jenkins please test this

**Pull request merged**
