### PR TITLE
(WIP) ci:test:git for SLES11

### PR DESCRIPTION
**Pull request by Iristyle**

### CODE REVIEW

**Comment by Iristyle** [comment]
Builds on #5971

**Comment by joshcooper** [comment]
Need to retarget base branch

**Comment by McdonaldSeanp** [comment]
Need to retarget to either the 4.10.x or the 5.3.x branch

**Comment by MosesMendoza** [comment]
@Iristyle is this still in progress or blocked?

**Comment by Iristyle** [comment]
* Installing Git - https://gist.github.com/orctom/902e9c00e48f0e8d4e7f#file-git-suse-L9
* Installing Ruby - https://www.suse.com/c/installing-ruby-19-slex-10/

This PR probably dies and gets replaced with the new proposal to drop platform-specific precompiled tars with Ruby onto hosts.

**Comment by melissa** [comment]
This work is now happening in beaker-puppet as a part of PUP-8305

**Pull request closed without merging**
