### PR TITLE
(PUP-7597) Add Hiera5 default yaml file

### PR DESCRIPTION
**Pull request by jcoconnor**
This is installed by PA instead of the previous hiera3 format file.

### CODE REVIEW

**Comment by jcoconnor** [comment]
This is the other half of PR https://github.com/puppetlabs/puppet-agent/pull/1058

Ping @Iristyle

**Comment by jcoconnor** [comment]
@Iristyle @branan - Have built this successfully locally and the updated hiera.yaml file is being installed.

Any idea why I'm seeing the ```appveyorer``` issue above.

/cc @McdonaldSeanp

**Comment by branan** [comment]
I think there's some sort of Appveyor bug - see the chatter in our HipChat room.

If that failure is the expected appveyor issue, I'm :+1: here

**Comment by McdonaldSeanp** [comment]
This should be retargeted at the stable branch, so the fix can land in the next agent 1.10.x

**Comment by jcoconnor** [comment]
Closing in favour of #5927

**Pull request closed without merging**
